name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
inputs:
  upload:
    description: Whether to upload the extractor pack
    default: true
runs:
  using: composite
  steps:
    - uses: bazelbuild/setup-bazelisk@v2
    - uses: actions/setup-python@v4
      with:
        python-version-file: 'swift/.python-version'
    - name: Configure bazel
      shell: bash
      run: |
        echo > local.bazelrc
        echo test --test_output=errors >> local.bazelrc
    - name: Build Swift extractor
      shell: bash
      run: |
        bazel run //swift:create-extractor-pack
    - name: Run codegen tests
      if : ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        bazel test //misc/codegen/...
    - name: Run Swift tests
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: |
        bazel test //swift/...
    - name: Upload
      if: inputs.upload == 'true'
      uses: ./swift/actions/upload-extractor-pack
