[package]
name = "tree-sitter-blame"
description = "blame grammar for the tree-sitter parsing library"
version = "0.0.1"
keywords = ["incremental", "parsing", "blame"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-blame"
edition = "2021"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1.0"
tree-sitter = ">= 0.23"

[build-dependencies]
cc = "1.0"
