// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `AnyBuiltinIntegerType`.
 */

private import AnyBuiltinIntegerTypeImpl
import codeql.swift.elements.type.BuiltinType

final class AnyBuiltinIntegerType = Impl::AnyBuiltinIntegerType;
