// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AnyMetatypeType`.
 */

private import codeql.swift.generated.type.AnyMetatypeType

class AnyMetatypeType extends Generated::AnyMetatypeType { }
