// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ArraySliceType`.
 */

private import ArraySliceTypeImpl
import codeql.swift.elements.type.UnarySyntaxSugarType

final class ArraySliceType = Impl::ArraySliceType;
