// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BuiltinUnsafeValueBufferType`.
 */

private import codeql.swift.generated.type.BuiltinUnsafeValueBufferType

class BuiltinUnsafeValueBufferType extends Generated::BuiltinUnsafeValueBufferType { }
