// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `BuiltinIntegerLiteralType`.
 */

private import internal.BuiltinIntegerLiteralTypeImpl
import codeql.swift.elements.type.AnyBuiltinIntegerType

final class BuiltinIntegerLiteralType = Impl::BuiltinIntegerLiteralType;
