// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ClassType`.
 */

private import ClassTypeImpl
import codeql.swift.elements.type.NominalType

final class ClassType = Impl::ClassType;
