// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `DependentMemberType`.
 */

private import internal.DependentMemberTypeImpl
import codeql.swift.elements.decl.AssociatedTypeDecl
import codeql.swift.elements.type.Type

final class DependentMemberType = Impl::DependentMemberType;
