// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ElementArchetypeType`.
 */

private import internal.ElementArchetypeTypeImpl
import codeql.swift.elements.type.LocalArchetypeType

/**
 * An archetype type of PackElementType.
 */
final class ElementArchetypeType = Impl::ElementArchetypeType;
