// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `EnumType`.
 */

private import internal.EnumTypeImpl
import codeql.swift.elements.type.NominalType

final class EnumType = Impl::EnumType;
