// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ExistentialMetatypeType`.
 */

private import internal.ExistentialMetatypeTypeImpl
import codeql.swift.elements.type.AnyMetatypeType

final class ExistentialMetatypeType = Impl::ExistentialMetatypeType;
