// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `FunctionType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.FunctionType

/**
 * INTERNAL: This module contains the customizable definition of `FunctionType` and should not
 * be referenced directly.
 */
module Impl {
  class FunctionType extends Generated::FunctionType { }
}
