// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ModuleType`.
 */

private import internal.ModuleTypeImpl
import codeql.swift.elements.decl.ModuleDecl
import codeql.swift.elements.type.Type

final class ModuleType = Impl::ModuleType;
