// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `NominalType`.
 */

private import internal.NominalTypeImpl
import codeql.swift.elements.type.NominalOrBoundGenericNominalType

final class NominalType = Impl::NominalType;
