// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `OpaqueTypeArchetypeType`.
 */

private import internal.OpaqueTypeArchetypeTypeImpl
import codeql.swift.elements.type.ArchetypeType
import codeql.swift.elements.decl.OpaqueTypeDecl

/**
 * An opaque type, that is a type formally equivalent to an underlying type but abstracting it away.
 *
 * See https://docs.swift.org/swift-book/LanguageGuide/OpaqueTypes.html.
 */
final class OpaqueTypeArchetypeType = Impl::OpaqueTypeArchetypeType;
