// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `OpenedArchetypeType`.
 */

private import OpenedArchetypeTypeImpl
import codeql.swift.elements.type.LocalArchetypeType

final class OpenedArchetypeType = Impl::OpenedArchetypeType;
