// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `PackElementType`.
 */

private import PackElementTypeImpl
import codeql.swift.elements.type.Type

/**
 * A type of PackElementExpr, see PackElementExpr for more information.
 */
final class PackElementType = Impl::PackElementType;
