// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `PrimaryArchetypeType`.
 */

private import PrimaryArchetypeTypeImpl
import codeql.swift.elements.type.ArchetypeType

final class PrimaryArchetypeType = Impl::PrimaryArchetypeType;
