// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ProtocolCompositionType`.
 */

private import internal.ProtocolCompositionTypeImpl
import codeql.swift.elements.type.Type

final class ProtocolCompositionType = Impl::ProtocolCompositionType;
