// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ReferenceStorageType`.
 */

private import internal.ReferenceStorageTypeImpl
import codeql.swift.elements.type.Type

final class ReferenceStorageType = Impl::ReferenceStorageType;
