// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `SyntaxSugarType`.
 */

private import internal.SyntaxSugarTypeImpl
import codeql.swift.elements.type.SugarType

final class SyntaxSugarType = Impl::SyntaxSugarType;
