// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnmanagedStorageType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.UnmanagedStorageType

/**
 * INTERNAL: This module contains the customizable definition of `UnmanagedStorageType` and should not
 * be referenced directly.
 */
module Impl {
  class UnmanagedStorageType extends Generated::UnmanagedStorageType { }
}
