// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `UnmanagedStorageType`.
 */

private import internal.UnmanagedStorageTypeImpl
import codeql.swift.elements.type.ReferenceStorageType

final class UnmanagedStorageType = Impl::UnmanagedStorageType;
