// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `UnresolvedType`.
 */

private import UnresolvedTypeImpl
import codeql.swift.elements.ErrorElement
import codeql.swift.elements.type.Type

final class UnresolvedType = Impl::UnresolvedType;
