// Generated automatically from javafx.scene.AccessibleRole for testing purposes

package javafx.scene;


public enum AccessibleRole
{
    BUTTON, CHECK_BOX, CHECK_MENU_ITEM, COMBO_BOX, CONTEXT_MENU, DATE_PICKER, DECREMENT_BUTTON, DIALOG, HYPERLINK, IMAGE_VIEW, INCREMENT_BUTTON, LIST_ITEM, LIST_VIEW, MENU, MENU_BAR, MENU_BUTTON, MENU_ITEM, NODE, PAGE_ITEM, PAGINATION, PARENT, PASSWORD_FIELD, PROGRESS_INDICATOR, RADIO_BUTTON, RADIO_MENU_ITEM, SCROLL_BAR, SCROLL_PANE, SLIDER, SPINNER, SPLIT_MENU_BUTTON, TABLE_CELL, TABLE_COLUMN, TABLE_ROW, TABLE_VIEW, TAB_ITEM, TAB_PANE, TEXT, TEXT_AREA, TEXT_FIELD, THUMB, TITLED_PANE, TOGGLE_BUTTON, TOOLTIP, TOOL_BAR, TREE_ITEM, TREE_TABLE_CELL, TREE_TABLE_ROW, TREE_TABLE_VIEW, TREE_VIEW;
    private AccessibleRole() {}
}
