// Generated automatically from javafx.scene.AccessibleAttribute for testing purposes

package javafx.scene;


public enum AccessibleAttribute
{
    ACCELERATOR, BOUNDS, BOUNDS_FOR_RANGE, CARET_OFFSET, CELL_AT_ROW_COLUMN, CHILDREN, COLUMN_AT_INDEX, COLUMN_COUNT, COLUMN_INDEX, CONTENTS, DATE, DISABLED, DISCLOSURE_LEVEL, EDITABLE, EXPANDED, FOCUSED, FOCUS_ITEM, FOCUS_NODE, FONT, HEADER, HELP, HORIZONTAL_SCROLLBAR, INDETERMINATE, INDEX, ITEM_AT_INDEX, ITEM_COUNT, LABELED_BY, LEAF, LINE_END, LINE_FOR_OFFSET, LINE_START, MAX_VALUE, MIN_VALUE, MNEMONIC, MULTIPLE_SELECTION, NODE_AT_POINT, OFFSET_AT_POINT, ORIENTATION, OVERFLOW_BUTTON, PARENT, PARENT_MENU, ROLE, ROLE_DESCRIPTION, ROW_AT_INDEX, ROW_COUNT, ROW_INDEX, SCENE, SELECTED, SELECTED_ITEMS, SELECTION_END, SELECTION_START, SUBMENU, TEXT, TREE_ITEM_AT_INDEX, TREE_ITEM_COUNT, TREE_ITEM_PARENT, VALUE, VERTICAL_SCROLLBAR, VISIBLE, VISITED;
    private AccessibleAttribute() {}
    public Class<? extends Object> getReturnType(){ return null; }
}
