
import "../../../lib.just"


[no-cd]
test *ARGS=".": (_if_not_on_ci_just "generate" source_dir()) (_integration_test ARGS)

# TODO in separate PR
# [no-cd]
# format *ARGS=".": (_ql_format ARGS) (_black ARGS)
