import "../justfile"

base_flags := []

all_checks := default_db_checks ++ ['--consistency-queries=' + consistency_queries]

[no-cd]
test *ARGS=".": (_codeql_test "rust" (base_flags ++ prepend('--all-checks=', all_checks) ++ ARGS))
