description: Downgrade rust-analyzer to 0.0.352
compatibility: partial

cfg_pred_exprs.rel: delete
cfg_pred_expr_cfg_predicates.rel: delete
cfg_pred_pats.rel: delete
cfg_pred_pat_cfg_predicates.rel: delete
locatable_locations.rel: run downgrade.ql new_locatable_locations
