// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ConditionalCheckedCastExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.ConditionalCheckedCastExpr

/**
 * INTERNAL: This module contains the customizable definition of `ConditionalCheckedCastExpr` and should not
 * be referenced directly.
 */
module Impl {
  class ConditionalCheckedCastExpr extends Generated::ConditionalCheckedCastExpr { }
}
