private import codeql.swift.generated.expr.ExplicitClosureExpr

module Impl {
  /**
   * A Swift explicit closure expr, that is, a closure written using
   * `{ ... -> ... in ... }` syntax rather than automatically generated by the
   * compiler.
   */
  class ExplicitClosureExpr extends Generated::ExplicitClosureExpr { }
}
