// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `LinearFunctionExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.LinearFunctionExpr

/**
 * INTERNAL: This module contains the customizable definition of `LinearFunctionExpr` and should not
 * be referenced directly.
 */
module Impl {
  class LinearFunctionExpr extends Generated::LinearFunctionExpr { }
}
