// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `PackElementExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.PackElementExpr

/**
 * INTERNAL: This module contains the customizable definition of `PackElementExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A pack element expression is a child of PackExpansionExpr.
   *
   * In the following example, `each t` on the second line is the pack element expression:
   * ```
   * func makeTuple<each T>(_ t: repeat each T) -> (repeat each T) {
   *   return (repeat each t)
   * }
   * ```
   *
   * More details:
   * https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md
   */
  class PackElementExpr extends Generated::PackElementExpr { }
}
