// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `PropertyWrapperValuePlaceholderExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.PropertyWrapperValuePlaceholderExpr

/**
 * INTERNAL: This module contains the customizable definition of `PropertyWrapperValuePlaceholderExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A placeholder substituting property initializations with `=` when the property has a property
   * wrapper with an initializer.
   */
  class PropertyWrapperValuePlaceholderExpr extends Generated::PropertyWrapperValuePlaceholderExpr {
  }
}
