// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `TypeValueExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.TypeValueExpr

/**
 * INTERNAL: This module contains the customizable definition of `TypeValueExpr` and should not
 * be referenced directly.
 */
module Impl {
  class TypeValueExpr extends Generated::TypeValueExpr { }
}
