// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnresolvedMemberChainResultExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.UnresolvedMemberChainResultExpr

/**
 * INTERNAL: This module contains the customizable definition of `UnresolvedMemberChainResultExpr` and should not
 * be referenced directly.
 */
module Impl {
  class UnresolvedMemberChainResultExpr extends Generated::UnresolvedMemberChainResultExpr { }
}
