description: Downgrade from rust-analyzer 0.0.328 to 0.0.301
compatibility: partial

block_expr_try_block_modifiers.rel: delete
cfg_atoms.rel: delete
cfg_attr_meta.rel: delete
cfg_attr_meta_cfg_predicates.rel: delete
cfg_attr_meta_metas.rel: delete
cfg_composites.rel: delete
cfg_composite_cfg_predicates.rel: delete
cfg_meta.rel: delete
cfg_meta_cfg_predicates.rel: delete
format_args_arg_arg_names.rel: delete
key_value_meta.rel: delete
key_value_meta_exprs.rel: delete
key_value_meta_paths.rel: delete
path_meta.rel: delete
path_meta_paths.rel: delete
struct_field_default_vals.rel: delete
token_tree_meta.rel: delete
token_tree_meta_paths.rel: delete
token_tree_meta_token_trees.rel: delete
try_block_modifier_is_try.rel: delete
try_block_modifiers.rel: delete
try_block_modifier_type_reprs.rel: delete
unsafe_meta.rel: delete
unsafe_meta_is_unsafe.rel: delete
unsafe_meta_meta.rel: delete
variant_const_args.rel: delete
