/**
 * @name Autogenerated lines of code
 * @kind treemap
 * @id cpp/autogenerated-loc
 * @description Measures the number of lines in autogenerated files that
 *              contain code (rather than lines that only contain
 *              comments or are blank).
 * @treemap.warnOn highValues
 * @metricType file
 * @metricAggregate sum
 * @tags maintainability
 */

import cpp
import semmle.code.cpp.AutogeneratedFile

from AutogeneratedFile af
where af.fromSource()
select af, af.getMetrics().getNumberOfLinesOfCode() as n order by n desc
