// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

package main

import "github.com/gofiber/fiber"

// Package github.com/gofiber/fiber@v1.14.6
func Redirect_GithubComGofiberFiberV1146() {
	// Redirect via method calls.
	{
		// Redirect via method calls on github.com/gofiber/fiber.Ctx.
		{
			// func (*Ctx).Redirect(location string, status ...int)
			{
				urlString832 := source().(string)
				var rece fiber.Ctx
				rece.Redirect(urlString832, 0) // $ redirectUrl=urlString832
			}
		}
	}
}
