name: Find Latest CodeQL Bundle
description: Finds the URL of the latest released version of the CodeQL bundle.
outputs:
  url:
    description: The download URL of the latest CodeQL bundle release
    value: ${{ steps.find-latest.outputs.url }}
runs:
  using: composite
  steps:
    - name: Find Latest Release
      id: find-latest
      shell: pwsh
      run: |
        $Latest = gh release list --repo github/codeql-action --exclude-drafts --limit 1000 |
          ForEach-Object { $C = $_ -split "`t"; return @{ type = $C[1]; tag = $C[2]; } } |
          Where-Object { $_.type -eq 'Latest' }

        $Tag = $Latest.tag
        if ($Tag -eq '') {
          throw 'Failed to find latest bundle release.'
        }

        Write-Output "Latest bundle tag is '${Tag}'."
        "url=https://github.com/github/codeql-action/releases/download/${Tag}/codeql-bundle-linux64.tar.gz" >> $env:GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}
