name: Cache query compilation
description: Caches CodeQL compilation caches - should be run both on PRs and pushes to main.

inputs:
  key:
    description: 'The cache key to use - should be unique to the workflow'
    required: true

outputs:
  cache-dir:
    description: "The directory where the cache was stored"
    value: ${{ steps.fill-compilation-dir.outputs.compdir }}

runs:
  using: composite
  steps:
    - name: Cache the query compilation caches
      uses: ./.github/actions/incremental-cache
      with:
        cached_path: '**/.cache'
        cached_key: codeql-compile-${{ inputs.key }}
    - name: Fill compilation cache directory
      id: fill-compilation-dir
      shell: bash
      run: |
        # Move all the existing cache into another folder, so we only preserve the cache for the current queries.
        mkdir -p ${COMBINED_CACHE_DIR}
        rm -f **/.cache/{lock,size} # -f to avoid errors if the cache is empty.
        # copy the contents of the .cache folders into the combined cache folder.
        cp -r **/.cache/* ${COMBINED_CACHE_DIR}/ || : # ignore missing files
        # clean up the .cache folders
        rm -rf **/.cache/*

        echo "compdir=${COMBINED_CACHE_DIR}" >> $GITHUB_OUTPUT
      env:
        COMBINED_CACHE_DIR: ${{ github.workspace }}/compilation-dir
