import "../justfile"

base_flags := ""

all_checks := f"""\
    {{default_db_checks}}\
    --check-undefined-labels \
    --check-unused-labels \
    --check-repeated-labels \
    --check-redefined-labels \
    --check-use-before-definition \
    --consistency-queries={{consistency_queries}}"""

[no-cd]
test *ARGS=".": (_codeql_test "go" base_flags all_checks ARGS)
