// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AbstractStorageDecl`.
 */

private import codeql.swift.generated.decl.AbstractStorageDecl

class AbstractStorageDecl extends Generated::AbstractStorageDecl { }
