// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `AbstractTypeParamDecl`.
 */

private import internal.AbstractTypeParamDeclImpl
import codeql.swift.elements.decl.TypeDecl

final class AbstractTypeParamDecl = Impl::AbstractTypeParamDecl;
