// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AbstractTypeParamDecl`.
 */

private import codeql.swift.generated.decl.AbstractTypeParamDecl

class AbstractTypeParamDecl extends Generated::AbstractTypeParamDecl { }
