// generated by codegen/codegen.py, remove this comment if you wish to edit this file
private import codeql.swift.generated.decl.EnumElementDecl

class EnumElementDecl extends EnumElementDeclBase { }
