// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `EnumCaseDecl`.
 */

private import internal.EnumCaseDeclImpl
import codeql.swift.elements.decl.Decl
import codeql.swift.elements.decl.EnumElementDecl

final class EnumCaseDecl = Impl::EnumCaseDecl;
