// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `NamedFunction`.
 */

private import codeql.swift.generated.decl.NamedFunction

class NamedFunction extends Generated::NamedFunction { }
