// generated by codegen/codegen.py, remove this comment if you wish to edit this file
private import codeql.swift.generated.decl.NominalTypeDecl

class NominalTypeDecl extends NominalTypeDeclBase { }
