// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ParamDecl`.
 */

private import internal.ParamDeclImpl
import codeql.swift.elements.decl.PatternBindingDecl
import codeql.swift.elements.decl.VarDecl

final class ParamDecl = Impl::ParamDecl;
