// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `PrecedenceGroupDecl`.
 */

private import internal.PrecedenceGroupDeclImpl
import codeql.swift.elements.decl.Decl

final class PrecedenceGroupDecl = Impl::PrecedenceGroupDecl;
