// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `SubscriptDecl`.
 */

private import internal.SubscriptDeclImpl
import codeql.swift.elements.decl.AbstractStorageDecl
import codeql.swift.elements.decl.GenericContext
import codeql.swift.elements.decl.ParamDecl
import codeql.swift.elements.type.Type

final class SubscriptDecl = Impl::SubscriptDecl;
