// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `TypeDecl`.
 */

private import internal.TypeDeclImpl
import codeql.swift.elements.type.Type
import codeql.swift.elements.decl.ValueDecl

final class TypeDecl = Impl::TypeDecl;
