// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `UsingDecl`.
 */

private import internal.UsingDeclImpl
import codeql.swift.elements.decl.Decl

final class UsingDecl = Impl::UsingDecl;
