path_classifiers:
  library:
  - javascript/externs
  - javascript/extractor/lib

  test:
  - csharp/ql/src
  - csharp/ql/test
  - go/ql/test
  - javascript/extractor/parser-tests
  - javascript/extractor/tests
  - javascript/ql/src
  - javascript/ql/test
  - python/ql/src
  - python/ql/test

  example:
  - go/ql/src

queries:
  - include: "*"

extraction:
  python:
    python_setup:
      version: 3
  javascript:
    index:
      exclude:
        - javascript/ql/test
        - javascript/extractor/tests
