import "../justfile"

# A whole language test suite is slow, so it only runs when asked for by name.
explicit_verbs := ['test']

base_flags := []

all_checks := default_db_checks

[no-cd]
test *ARGS=".": (_codeql_test "javascript" (base_flags ++ prepend('--all-checks=', all_checks) ++ ARGS))
