description: Downgrade rust-analyzer to 0.0.328
compatibility: partial

visibility_paths.rel: run downgrade.ql new_visibility_paths
visibility_visibility_inners.rel: delete
visibility_inners.rel: delete
visibility_inner_paths.rel: delete

format_args_arg_names.rel: run downgrade.ql new_format_args_arg_names
format_args_arg_arg_names.rel: run downgrade.ql new_format_args_arg_arg_names
names.rel: run downgrade.ql new_names
name_texts.rel: run downgrade.ql new_name_texts

locatable_locations.rel: run downgrade.ql new_locatable_locations
macro_call_macro_call_expansions.rel: run downgrade.ql new_macro_call_macro_call_expansions
comments.rel: run downgrade.ql new_comments

deref_pats.rel: delete
deref_pat_pats.rel: delete
not_nulls.rel: delete
include_bytes_exprs.rel: delete
pattern_type_reprs.rel: delete
pattern_type_repr_pats.rel: delete
pattern_type_repr_type_reprs.rel: delete
impl_restrictions.rel: delete
impl_restriction_visibility_inners.rel: delete
mut_restrictions.rel: delete
mut_restriction_is_mut.rel: delete
mut_restriction_visibility_inners.rel: delete
asm_clobber_abi_attrs.rel: delete
asm_operand_named_attrs.rel: delete
asm_options_list_attrs.rel: delete
struct_field_mut_restrictions.rel: delete
tuple_field_mut_restrictions.rel: delete
trait_impl_restrictions.rel: delete
