// Generated automatically from javax.jdo.metadata.MemberMetadata for testing purposes

package javax.jdo.metadata;

import javax.jdo.AttributeConverter;
import javax.jdo.annotations.ForeignKeyAction;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.NullValue;
import javax.jdo.annotations.PersistenceModifier;
import javax.jdo.metadata.ArrayMetadata;
import javax.jdo.metadata.CollectionMetadata;
import javax.jdo.metadata.ColumnMetadata;
import javax.jdo.metadata.ElementMetadata;
import javax.jdo.metadata.EmbeddedMetadata;
import javax.jdo.metadata.ForeignKeyMetadata;
import javax.jdo.metadata.IndexMetadata;
import javax.jdo.metadata.JoinMetadata;
import javax.jdo.metadata.KeyMetadata;
import javax.jdo.metadata.MapMetadata;
import javax.jdo.metadata.Metadata;
import javax.jdo.metadata.OrderMetadata;
import javax.jdo.metadata.UniqueMetadata;
import javax.jdo.metadata.ValueMetadata;

public interface MemberMetadata extends Metadata
{
    ArrayMetadata getArrayMetadata();
    ArrayMetadata newArrayMetadata();
    AttributeConverter<? extends Object, ? extends Object> getConverter();
    Boolean getDefaultFetchGroup();
    Boolean getDependent();
    Boolean getEmbedded();
    Boolean getIndexed();
    Boolean getSerialized();
    Boolean getUnique();
    Boolean getUseDefaultConversion();
    CollectionMetadata getCollectionMetadata();
    CollectionMetadata newCollectionMetadata();
    ColumnMetadata newColumnMetadata();
    ColumnMetadata[] getColumns();
    ElementMetadata getElementMetadata();
    ElementMetadata newElementMetadata();
    EmbeddedMetadata getEmbeddedMetadata();
    EmbeddedMetadata newEmbeddedMetadata();
    ForeignKeyAction getDeleteAction();
    ForeignKeyMetadata getForeignKeyMetadata();
    ForeignKeyMetadata newForeignKeyMetadata();
    IdGeneratorStrategy getValueStrategy();
    IndexMetadata getIndexMetadata();
    IndexMetadata newIndexMetadata();
    JoinMetadata getJoinMetadata();
    JoinMetadata newJoinMetadata();
    KeyMetadata getKeyMetadata();
    KeyMetadata newKeyMetadata();
    MapMetadata getMapMetadata();
    MapMetadata newMapMetadata();
    MemberMetadata setCacheable(boolean p0);
    MemberMetadata setColumn(String p0);
    MemberMetadata setConverter(AttributeConverter<? extends Object, ? extends Object> p0);
    MemberMetadata setCustomStrategy(String p0);
    MemberMetadata setDefaultFetchGroup(boolean p0);
    MemberMetadata setDeleteAction(ForeignKeyAction p0);
    MemberMetadata setDependent(boolean p0);
    MemberMetadata setEmbedded(boolean p0);
    MemberMetadata setFieldType(String p0);
    MemberMetadata setIndexed(boolean p0);
    MemberMetadata setLoadFetchGroup(String p0);
    MemberMetadata setMappedBy(String p0);
    MemberMetadata setName(String p0);
    MemberMetadata setNullValue(NullValue p0);
    MemberMetadata setPersistenceModifier(PersistenceModifier p0);
    MemberMetadata setPrimaryKey(boolean p0);
    MemberMetadata setRecursionDepth(int p0);
    MemberMetadata setSequence(String p0);
    MemberMetadata setSerialized(boolean p0);
    MemberMetadata setTable(String p0);
    MemberMetadata setUnique(boolean p0);
    MemberMetadata setUseDefaultConversion(Boolean p0);
    MemberMetadata setValueStrategy(IdGeneratorStrategy p0);
    NullValue getNullValue();
    OrderMetadata getOrderMetadata();
    OrderMetadata newOrderMetadata();
    PersistenceModifier getPersistenceModifier();
    String getColumn();
    String getCustomStrategy();
    String getFieldType();
    String getLoadFetchGroup();
    String getMappedBy();
    String getName();
    String getSequence();
    String getTable();
    UniqueMetadata getUniqueMetadata();
    UniqueMetadata newUniqueMetadata();
    ValueMetadata getValueMetadata();
    ValueMetadata newValueMetadata();
    boolean getCacheable();
    boolean getPrimaryKey();
    int getNumberOfColumns();
    int getRecursionDepth();
}
