// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `CaseLabelItem`.
 */

private import internal.CaseLabelItemImpl
import codeql.swift.elements.AstNode
import codeql.swift.elements.expr.Expr
import codeql.swift.elements.pattern.Pattern

final class CaseLabelItem = Impl::CaseLabelItem;
