// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `DeferStmt`.
 */

private import DeferStmtImpl
import codeql.swift.elements.stmt.BraceStmt
import codeql.swift.elements.stmt.Stmt

final class DeferStmt = Impl::DeferStmt;
