// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `FailStmt`.
 */

private import internal.FailStmtImpl
import codeql.swift.elements.stmt.Stmt

final class FailStmt = Impl::FailStmt;
