// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `LabeledStmt`.
 */

private import internal.LabeledStmtImpl
import codeql.swift.elements.stmt.Stmt

final class LabeledStmt = Impl::LabeledStmt;
