// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `LabeledConditionalStmt`.
 */

private import internal.LabeledConditionalStmtImpl
import codeql.swift.elements.stmt.LabeledStmt
import codeql.swift.elements.stmt.StmtCondition

final class LabeledConditionalStmt = Impl::LabeledConditionalStmt;
