// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `StmtCondition`.
 */

private import StmtConditionImpl
import codeql.swift.elements.AstNode
import codeql.swift.elements.stmt.ConditionElement

final class StmtCondition = Impl::StmtCondition;
