// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ThenStmt`.
 */

private import internal.ThenStmtImpl
import codeql.swift.elements.expr.Expr
import codeql.swift.elements.stmt.Stmt

/**
 * A statement implicitly wrapping values to be used in branches of if/switch expressions. For example in:
 * ```
 * let rank = switch value {
 *     case 0..<0x80: 1
 *     case 0x80..<0x0800: 2
 *     default: 3
 * }
 * ```
 * the literal expressions `1`, `2` and `3` are wrapped in `ThenStmt`.
 */
final class ThenStmt = Impl::ThenStmt;
