import "../justfile"

base_flags := ""

all_checks := f"""\
    {{default_db_checks}}\
    --check-undefined-labels \
    --check-repeated-labels \
    --check-redefined-labels \
    --additional-packs=ql \
    --consistency-queries={{consistency_queries}}"""

[no-cd]
test *ARGS=".": (_codeql_test "csharp" base_flags all_checks ARGS)
