// Generated automatically from javafx.scene.input.KeyCode for testing purposes

package javafx.scene.input;


public enum KeyCode
{
    A, ACCEPT, ADD, AGAIN, ALL_CANDIDATES, ALPHANUMERIC, ALT, ALT_GRAPH, AMPERSAND, ASTERISK, AT, B, BACK_QUOTE, BACK_SLASH, BACK_SPACE, BEGIN, BRACELEFT, BRACERIGHT, C, CANCEL, CAPS, CHANNEL_DOWN, CHANNEL_UP, CIRCUMFLEX, CLEAR, CLOSE_BRACKET, CODE_INPUT, COLON, COLORED_KEY_0, COLORED_KEY_1, COLORED_KEY_2, COLORED_KEY_3, COMMA, COMMAND, COMPOSE, CONTEXT_MENU, CONTROL, CONVERT, COPY, CUT, D, DEAD_ABOVEDOT, DEAD_ABOVERING, DEAD_ACUTE, DEAD_BREVE, DEAD_CARON, DEAD_CEDILLA, DEAD_CIRCUMFLEX, DEAD_DIAERESIS, DEAD_DOUBLEACUTE, DEAD_GRAVE, DEAD_IOTA, DEAD_MACRON, DEAD_OGONEK, DEAD_SEMIVOICED_SOUND, DEAD_TILDE, DEAD_VOICED_SOUND, DECIMAL, DELETE, DIGIT0, DIGIT1, DIGIT2, DIGIT3, DIGIT4, DIGIT5, DIGIT6, DIGIT7, DIGIT8, DIGIT9, DIVIDE, DOLLAR, DOWN, E, EJECT_TOGGLE, END, ENTER, EQUALS, ESCAPE, EURO_SIGN, EXCLAMATION_MARK, F, F1, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F2, F20, F21, F22, F23, F24, F3, F4, F5, F6, F7, F8, F9, FAST_FWD, FINAL, FIND, FULL_WIDTH, G, GAME_A, GAME_B, GAME_C, GAME_D, GREATER, H, HALF_WIDTH, HELP, HIRAGANA, HOME, I, INFO, INPUT_METHOD_ON_OFF, INSERT, INVERTED_EXCLAMATION_MARK, J, JAPANESE_HIRAGANA, JAPANESE_KATAKANA, JAPANESE_ROMAN, K, KANA, KANA_LOCK, KANJI, KATAKANA, KP_DOWN, KP_LEFT, KP_RIGHT, KP_UP, L, LEFT, LEFT_PARENTHESIS, LESS, M, META, MINUS, MODECHANGE, MULTIPLY, MUTE, N, NONCONVERT, NUMBER_SIGN, NUMPAD0, NUMPAD1, NUMPAD2, NUMPAD3, NUMPAD4, NUMPAD5, NUMPAD6, NUMPAD7, NUMPAD8, NUMPAD9, NUM_LOCK, O, OPEN_BRACKET, P, PAGE_DOWN, PAGE_UP, PASTE, PAUSE, PERIOD, PLAY, PLUS, POUND, POWER, PREVIOUS_CANDIDATE, PRINTSCREEN, PROPS, Q, QUOTE, QUOTEDBL, R, RECORD, REWIND, RIGHT, RIGHT_PARENTHESIS, ROMAN_CHARACTERS, S, SCROLL_LOCK, SEMICOLON, SEPARATOR, SHIFT, SHORTCUT, SLASH, SOFTKEY_0, SOFTKEY_1, SOFTKEY_2, SOFTKEY_3, SOFTKEY_4, SOFTKEY_5, SOFTKEY_6, SOFTKEY_7, SOFTKEY_8, SOFTKEY_9, SPACE, STAR, STOP, SUBTRACT, T, TAB, TRACK_NEXT, TRACK_PREV, U, UNDEFINED, UNDERSCORE, UNDO, UP, V, VOLUME_DOWN, VOLUME_UP, W, WINDOWS, X, Y, Z;
    private KeyCode() {}
    public final String getChar(){ return null; }
    public final String getName(){ return null; }
    public final boolean isArrowKey(){ return false; }
    public final boolean isDigitKey(){ return false; }
    public final boolean isFunctionKey(){ return false; }
    public final boolean isKeypadKey(){ return false; }
    public final boolean isLetterKey(){ return false; }
    public final boolean isMediaKey(){ return false; }
    public final boolean isModifierKey(){ return false; }
    public final boolean isNavigationKey(){ return false; }
    public final boolean isWhitespaceKey(){ return false; }
    public final int getCode(){ return 0; }
    public static KeyCode getKeyCode(String p0){ return null; }
}
