// generated by codegen, do not edit
/**
 * This module provides the public class `ArrayTypeRepr`.
 */

private import internal.ArrayTypeReprImpl
import codeql.rust.elements.ConstArg
import codeql.rust.elements.TypeRepr

/**
 * An array type representation.
 *
 * For example:
 * ```rust
 * let arr: [i32; 4];
 * //       ^^^^^^^^
 * ```
 */
final class ArrayTypeRepr = Impl::ArrayTypeRepr;
