// generated by codegen
/**
 * This module provides the AST class  `ArrayExpr`.
 */

private import codeql.rust.generated.ArrayExpr
private import ArrayExprImpl

final private class ArrayExprImplFinal = ArrayExprImpl;

final class ArrayExpr extends ArrayExprImplFinal, Generated::ArrayExpr { }
