// generated by codegen, do not edit
/**
 * This module provides the public class `ArrayExpr`.
 */

private import internal.ArrayExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr

/**
 * The base class for array expressions. For example:
 * ```rust
 * [1, 2, 3];
 * [1; 10];
 * ```
 */
final class ArrayExpr = Impl::ArrayExpr;
