// generated by codegen, do not edit
/**
 * This module provides the public class `AsmExpr`.
 */

private import internal.AsmExprImpl
import codeql.rust.elements.AsmPiece
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr
import codeql.rust.elements.Item

/**
 * An inline assembly expression. For example:
 * ```rust
 * unsafe {
 *     #[inline(always)]
 *     builtin # asm("cmp {0}, {1}", in(reg) a, in(reg) b);
 * }
 * ```
 */
final class AsmExpr = Impl::AsmExpr;
