// generated by codegen, do not edit
/**
 * This module provides the public class `AsmRegSpec`.
 */

private import internal.AsmRegSpecImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.NameRef

final class AsmRegSpec = Impl::AsmRegSpec;
