// generated by codegen, do not edit
/**
 * This module provides the public class `AssocItemList`.
 */

private import internal.AssocItemListImpl
import codeql.rust.elements.AnyAttr
import codeql.rust.elements.AssocItem
import codeql.rust.elements.AstNode

/**
 * A list of `AssocItem` elements, as appearing in a `Trait` or `Impl`.
 */
final class AssocItemList = Impl::AssocItemList;
