// generated by codegen, do not edit
/**
 * This module provides the public class `AssocItem`.
 */

private import internal.AssocItemImpl
import codeql.rust.elements.AstNode

/**
 * An associated item in a `Trait` or `Impl`.
 *
 * For example:
 * ```rust
 * trait T {fn foo(&self);}
 * //       ^^^^^^^^^^^^^
 * ```
 */
final class AssocItem = Impl::AssocItem;
