// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AsyncBlock`.
 */

private import codeql.rust.generated.AsyncBlock

class AsyncBlock extends Generated::AsyncBlock { }
