// generated by codegen, do not edit
/**
 * This module provides the public class `Attr`.
 */

private import internal.AttrImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Meta

/**
 * A Attr. For example:
 * ```rust
 * todo!()
 * ```
 */
final class Attr = Impl::Attr;
