// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AwaitExpr`.
 */

private import codeql.rust.generated.AwaitExpr

class AwaitExpr extends Generated::AwaitExpr { }
