// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Become`.
 */

private import codeql.rust.generated.Become

class Become extends Generated::Become { }
