// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BecomeExpr`.
 */

private import codeql.rust.generated.BecomeExpr

/**
 * A `become` expression. For example:
 * ```
 * fn fact_a(n: i32, a: i32) -> i32 {
 *      if n == 0 {
 *          a
 *      } else {
 *          become fact_a(n - 1, n * a)
 *      }
 *  }    ```
 */
class BecomeExpr extends Generated::BecomeExpr { }
