// generated by codegen, remove this comment if you wish to edit this file
/**
 *  This module defines the hook used internally to tweak the characteristic predicate of
 *  `BinaryOpExpr` synthesized instances.
 *  INTERNAL: Do not use.
 */

private import codeql.rust.generated.Raw

/**
 *  The characteristic predicate of `BinaryOpExpr` synthesized instances.
 *  INTERNAL: Do not use.
 */
predicate constructBinaryOpExpr(Raw::BinaryOpExpr id) { any() }
