// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BinaryOpExpr`.
 */

private import codeql.rust.generated.BinaryOpExpr

/**
 * A binary operation expression. For example:
 * ```
 * x + y;
 * x && y;
 * x <= y;
 * x = y;
 * x += y;
 * ```
 */
class BinaryOpExpr extends Generated::BinaryOpExpr { }
