// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BinaryOpExpr`.
 */

private import codeql.rust.generated.BinaryOpExpr

class BinaryOpExprImpl extends Generated::BinaryOpExprImpl { }

final private class BinaryOpExprImplFinal = BinaryOpExprImpl;

final class BinaryOpExpr extends BinaryOpExprImplFinal, Generated::BinaryOpExpr { }
