// generated by codegen
/**
 * This module provides the AST class  `BlockExpr`.
 */

private import codeql.rust.generated.BlockExpr
private import BlockExprImpl

final private class BlockExprImplFinal = BlockExprImpl;

final class BlockExpr extends BlockExprImplFinal, Generated::BlockExpr { }
