// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BlockExpr`.
 */

private import codeql.rust.generated.BlockExpr

/**
 * A block expression. For example:
 * ```
 * {
 *     let x = 42;
 * }
 * ```
 * ```
 * 'label: {
 *     let x = 42;
 *     x
 * }
 * ```
 */
class BlockExpr extends Generated::BlockExpr { }
