// generated by codegen, remove this comment if you wish to edit this file
/**
 *  This module defines the hook used internally to tweak the characteristic predicate of
 *  `Block` synthesized instances.
 *  INTERNAL: Do not use.
 */

private import codeql.rust.generated.Raw

/**
 *  The characteristic predicate of `Block` synthesized instances.
 *  INTERNAL: Do not use.
 */
predicate constructBlock(Raw::Block id) { any() }
