// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BlockExprBase`.
 */

private import codeql.rust.generated.BlockExprBase

class BlockExprBase extends Generated::BlockExprBase { }
