// generated by codegen, do not edit
/**
 * This module provides the public class `BlockExprBase`.
 */

private import BlockExprBaseImpl
import codeql.rust.elements.Expr
import codeql.rust.elements.Stmt

final class BlockExprBase = Impl::BlockExprBase;
