// generated by codegen, do not edit
/**
 * This module provides the public class `BreakExpr`.
 */

private import internal.BreakExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr
import codeql.rust.elements.Lifetime

final class BreakExpr = Impl::BreakExpr;
