// generated by codegen, do not edit
/**
 * This module provides the public class `CallExpr`.
 */

private import internal.CallExprImpl
import codeql.rust.elements.ArgList
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr

/**
 * NOTE: Consider using `Call` instead, as that includes all kinds of calls to
 * functions, and excludes instantiations of tuple structs and tuple enum variants.
 *
 * A call expression. For example:
 * ```rust
 * foo(42);
 * foo::<u32, u64>(42);
 * foo[0](42);
 * foo(1) = 4;
 * Option::Some(42); // tuple enum variant instantiation
 * ```
 */
final class CallExpr = Impl::CallExpr;
