// generated by codegen, do not edit
/**
 * This module provides the public class `CallExpr`.
 */

private import internal.CallExprImpl
import codeql.rust.elements.ArgList
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr

final class CallExpr = Impl::CallExpr;
