// generated by codegen, do not edit
/**
 * This module provides the public class `CfgMeta`.
 */

private import internal.CfgMetaImpl
import codeql.rust.elements.CfgPredicate
import codeql.rust.elements.Meta

final class CfgMeta = Impl::CfgMeta;
