// generated by codegen, do not edit
/**
 * This module provides the public class `ClosureBinder`.
 */

private import internal.ClosureBinderImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.GenericParamList

/**
 * A closure binder, specifying lifetime or type parameters for a closure.
 *
 * For example:
 * ```rust
 * for <'a> |x: &'a u32 | x
 * // ^^^^^^
 * ```
 */
final class ClosureBinder = Impl::ClosureBinder;
