// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ConstExpr`.
 */

private import codeql.rust.generated.ConstExpr

/**
 * A `const` block expression. For example:
 * ```
 * if const { SRC::IS_ZST || DEST::IS_ZST || mem::align_of::<SRC>() != mem::align_of::<DEST>() } {
 *     return false;
 * }
 * ```
 */
class ConstExpr extends Generated::ConstExpr { }
