// generated by codegen
/**
 * This module provides the AST class  `ConstExpr`.
 */

private import codeql.rust.generated.ConstExpr
private import ConstExprImpl

final private class ConstExprImplFinal = ConstExprImpl;

final class ConstExpr extends ConstExprImplFinal, Generated::ConstExpr { }
