// generated by codegen, do not edit
/**
 * This module provides the public class `ContinueExpr`.
 */

private import internal.ContinueExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr
import codeql.rust.elements.Lifetime

final class ContinueExpr = Impl::ContinueExpr;
