// generated by codegen, do not edit
/**
 * This module provides the public class `Crate`.
 */

private import internal.CrateImpl
import codeql.rust.elements.Element
import codeql.rust.elements.Module

final class Crate = Impl::Crate;
