// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `DbFile`.
 */

private import codeql.rust.generated.DbFile

class DbFileImpl extends Generated::DbFileImpl { }

final private class DbFileImplFinal = DbFileImpl;

final class DbFile extends DbFileImplFinal, Generated::DbFile { }
