// generated by codegen
/**
 * This module provides the AST class  `DbFile`.
 */

private import codeql.rust.generated.DbFile
private import DbFileImpl

final private class DbFileImplFinal = DbFileImpl;

final class DbFile extends DbFileImplFinal, Generated::DbFile { }
