// generated by codegen, do not edit
/**
 * This module provides the public class `DerefPat`.
 */

private import internal.DerefPatImpl
import codeql.rust.elements.Pat

final class DerefPat = Impl::DerefPat;
