// generated by codegen, do not edit
/**
 * This module provides the public class `DynTraitTypeRef`.
 */

private import internal.DynTraitTypeRefImpl
import codeql.rust.elements.TypeBoundList
import codeql.rust.elements.TypeRef

/**
 * A DynTraitTypeRef. For example:
 * ```rust
 * todo!()
 * ```
 */
final class DynTraitTypeRef = Impl::DynTraitTypeRef;
