// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ElementListExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.generated.ElementListExpr

/**
 * INTERNAL: This module contains the customizable definition of `ElementListExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * An element list expression. For example:
   * ```
   * [1, 2, 3, 4, 5];
   * [1, 2, 3, 4, 5][0] = 6;
   * ```
   */
  class ElementListExpr extends Generated::ElementListExpr { }
}
