// generated by codegen
/**
 * This module provides the AST class  `Element`.
 */

private import codeql.rust.generated.Element
private import ElementImpl

final private class ElementImplFinal = ElementImpl;

final class Element extends ElementImplFinal, Generated::Element { }
