// generated by codegen, do not edit
/**
 * This module provides the public class `EnumVariant`.
 */

private import internal.EnumVariantImpl
import codeql.rust.elements.Element
import codeql.rust.elements.VariantData

final class EnumVariant = Impl::EnumVariant;
