// generated by codegen, do not edit
/**
 * This module provides the public class `Enum`.
 */

private import internal.EnumImpl
import codeql.rust.elements.Adt
import codeql.rust.elements.Attr
import codeql.rust.elements.GenericParamList
import codeql.rust.elements.Item
import codeql.rust.elements.Name
import codeql.rust.elements.VariantList
import codeql.rust.elements.Visibility
import codeql.rust.elements.WhereClause

/**
 * An enum declaration.
 *
 * For example:
 * ```rust
 * enum E {A, B(i32), C {x: i32}}
 * ```
 */
final class Enum = Impl::Enum;
