// generated by codegen, do not edit
/**
 * This module provides the public class `ExprStmt`.
 */

private import internal.ExprStmtImpl
import codeql.rust.elements.Expr
import codeql.rust.elements.Stmt

/**
 * An expression statement. For example:
 * ```rust
 * start();
 * finish();
 * use std::env;
 * ```
 */
final class ExprStmt = Impl::ExprStmt;
