// generated by codegen
/**
 * This module provides the AST class  `Expr`.
 */

private import codeql.rust.generated.Expr
private import ExprImpl

final private class ExprImplFinal = ExprImpl;

final class Expr extends ExprImplFinal, Generated::Expr { }
