// generated by codegen, do not edit
/**
 * This module provides the public class `ExternItem`.
 */

private import internal.ExternItemImpl
import codeql.rust.elements.AstNode

/**
 * A ExternItem. For example:
 * ```rust
 * todo!()
 * ```
 */
final class ExternItem = Impl::ExternItem;
