// generated by codegen, do not edit
/**
 * This module provides the public class `ExternItemList`.
 */

private import internal.ExternItemListImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Attr
import codeql.rust.elements.ExternItem

/**
 * A ExternItemList. For example:
 * ```rust
 * todo!()
 * ```
 */
final class ExternItemList = Impl::ExternItemList;
