// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `FieldExpr`.
 */

private import codeql.rust.generated.FieldExpr

class FieldExprImpl extends Generated::FieldExprImpl { }

final private class FieldExprImplFinal = FieldExprImpl;

final class FieldExpr extends FieldExprImplFinal, Generated::FieldExpr { }
