// generated by codegen
/**
 * This module provides the AST class  `File`.
 */

private import codeql.rust.generated.File
private import FileImpl

final private class FileImplFinal = FileImpl;

final class File extends FileImplFinal, Generated::File { }
