// generated by codegen, do not edit
/**
 * This module provides the public class `FnPtrTypeRef`.
 */

private import internal.FnPtrTypeRefImpl
import codeql.rust.elements.Abi
import codeql.rust.elements.ParamList
import codeql.rust.elements.RetTypeRef
import codeql.rust.elements.TypeRef

/**
 * A FnPtrTypeRef. For example:
 * ```rust
 * todo!()
 * ```
 */
final class FnPtrTypeRef = Impl::FnPtrTypeRef;
