// generated by codegen, do not edit
/**
 * This module provides the public class `ForExpr`.
 */

private import internal.ForExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr
import codeql.rust.elements.LoopingExpr
import codeql.rust.elements.Pat

/**
 * A for loop expression.
 *
 * For example:
 * ```rust
 * for x in 0..10 {
 *     println!("{}", x);
 * }
 * ```
 */
final class ForExpr = Impl::ForExpr;
