// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Function`.
 */

private import codeql.rust.generated.Function

class Function extends Generated::Function { }
