// generated by codegen, do not edit
/**
 * This module provides the public class `GenericArg`.
 */

private import internal.GenericArgImpl
import codeql.rust.elements.AstNode

/**
 * A GenericArg. For example:
 * ```rust
 * todo!()
 * ```
 */
final class GenericArg = Impl::GenericArg;
