// generated by codegen
/**
 * This module provides the AST class  `IfExpr`.
 */

private import codeql.rust.generated.IfExpr
private import IfExprImpl

final private class IfExprImplFinal = IfExprImpl;

final class IfExpr extends IfExprImplFinal, Generated::IfExpr { }
