// generated by codegen, do not edit
/**
 * This module provides the public class `IfExpr`.
 */

private import internal.IfExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.BlockExpr
import codeql.rust.elements.Expr

final class IfExpr = Impl::IfExpr;
