// generated by codegen, do not edit
/**
 * This module provides the public class `ImplTraitType`.
 */

private import internal.ImplTraitTypeImpl
import codeql.rust.elements.TypeBoundList
import codeql.rust.elements.TypeRef

/**
 * A ImplTraitType. For example:
 * ```rust
 * todo!()
 * ```
 */
final class ImplTraitType = Impl::ImplTraitType;
