// generated by codegen, do not edit
/**
 * This module provides the public class `ImplTraitTypeRef`.
 */

private import internal.ImplTraitTypeRefImpl
import codeql.rust.elements.TypeBoundList
import codeql.rust.elements.TypeRef

/**
 * A ImplTraitTypeRef. For example:
 * ```rust
 * todo!()
 * ```
 */
final class ImplTraitTypeRef = Impl::ImplTraitTypeRef;
