// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Index`.
 */

private import codeql.rust.generated.Index

class Index extends Generated::Index { }
