// generated by codegen, do not edit
/**
 * This module provides the public class `IndexExpr`.
 */

private import internal.IndexExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr

final class IndexExpr = Impl::IndexExpr;
