// generated by codegen, do not edit
/**
 * This module provides the public class `InferType`.
 */

private import internal.InferTypeImpl
import codeql.rust.elements.TypeRef

final class InferType = Impl::InferType;
