// generated by codegen
/**
 * This module provides the AST class  `InlineAsmExpr`.
 */

private import codeql.rust.generated.InlineAsmExpr
private import InlineAsmExprImpl

final private class InlineAsmExprImplFinal = InlineAsmExprImpl;

final class InlineAsmExpr extends InlineAsmExprImplFinal, Generated::InlineAsmExpr { }
