// generated by codegen, do not edit
/**
 * This module provides the public class `LetElse`.
 */

private import internal.LetElseImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.BlockExpr

final class LetElse = Impl::LetElse;
