// generated by codegen, do not edit
/**
 * This module provides the public class `LifetimeTypeBound`.
 */

private import internal.LifetimeTypeBoundImpl
import codeql.rust.elements.TypeBoundType

final class LifetimeTypeBound = Impl::LifetimeTypeBound;
