// generated by codegen, do not edit
/**
 * This module provides the public class `LifetimeArg`.
 */

private import internal.LifetimeArgImpl
import codeql.rust.elements.GenericArg
import codeql.rust.elements.Lifetime

final class LifetimeArg = Impl::LifetimeArg;
