// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Literal`.
 */

private import codeql.rust.generated.Literal

/**
 * A literal expression. For example:
 * ```
 * 42;
 * 42.0;
 * "Hello, world!";
 * b"Hello, world!";
 * 'x';
 * b'x';
 * r"Hello, world!";
 * true;
 */
class Literal extends Generated::Literal { }
