// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `LitPat`.
 */

private import codeql.rust.generated.LitPat

/**
 * A literal pattern. For example:
 * ```
 * match x {
 *     42 => "ok",
 *     _ => "fail",
 * }
 * ```
 */
class LitPat extends Generated::LitPat { }
