// generated by codegen
/**
 * This module provides the AST class  `Location`.
 */

private import codeql.rust.generated.Location
private import LocationImpl

final private class LocationImplFinal = LocationImpl;

final class Location extends LocationImplFinal, Generated::Location { }
