// generated by codegen, do not edit
/**
 * This module provides the public class `MacroTypeRef`.
 */

private import internal.MacroTypeRefImpl
import codeql.rust.elements.MacroCall
import codeql.rust.elements.TypeRef

/**
 * A MacroTypeRef. For example:
 * ```rust
 * todo!()
 * ```
 */
final class MacroTypeRef = Impl::MacroTypeRef;
