// generated by codegen, do not edit
/**
 * This module provides the public class `MacroRules`.
 */

private import internal.MacroRulesImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Item
import codeql.rust.elements.Name
import codeql.rust.elements.TokenTree
import codeql.rust.elements.Visibility

/**
 * A MacroRules. For example:
 * ```rust
 * todo!()
 * ```
 */
final class MacroRules = Impl::MacroRules;
