// generated by codegen, do not edit
/**
 * This module provides the public class `Meta`.
 */

private import internal.MetaImpl
import codeql.rust.elements.AstNode

/**
 * A meta item in an attribute.
 *
 * For example:
 * ```rust
 * #[unsafe(lint::name = "reason_for_bypass")]
 * //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 * #[deprecated(since = "1.2.0", note = "Use bar instead", unsafe=true)]
 * //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 * fn foo() {
 *     // ...
 * }
 * ```
 */
final class Meta = Impl::Meta;
