// generated by codegen
/**
 * This module provides the AST class  `MethodCallExpr`.
 */

private import codeql.rust.generated.MethodCallExpr
private import MethodCallExprImpl

final private class MethodCallExprImplFinal = MethodCallExprImpl;

final class MethodCallExpr extends MethodCallExprImplFinal, Generated::MethodCallExpr { }
