// generated by codegen
/**
 * This module provides the AST class  `MissingExpr`.
 */

private import codeql.rust.generated.MissingExpr
private import MissingExprImpl

final private class MissingExprImplFinal = MissingExprImpl;

final class MissingExpr extends MissingExprImplFinal, Generated::MissingExpr { }
