// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `MissingExpr`.
 */

private import codeql.rust.generated.MissingExpr

class MissingExpr extends Generated::MissingExpr { }
