// generated by codegen, do not edit
/**
 * This module provides the public class `Module`.
 */

private import ModuleImpl
import codeql.rust.elements.Declaration

/**
 * A module declaration. For example:
 * ```
 * mod foo;
 * ```
 * ```
 * mod bar {
 *     pub fn baz() {}
 * }
 * ```
 */
final class Module = Impl::Module;
