// generated by codegen, do not edit
/**
 * This module provides the public class `Name`.
 */

private import internal.NameImpl
import codeql.rust.elements.AstNode

/**
 * A Name. For example:
 * ```rust
 * todo!()
 * ```
 */
final class Name = Impl::Name;
