// generated by codegen, do not edit
/**
 * This module provides the public class `ParamList`.
 */

private import internal.ParamListImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Param
import codeql.rust.elements.SelfParam

/**
 * A list of parameters in a function, method, or closure declaration.
 *
 * For example:
 * ```rust
 * fn foo(x: i32, y: i32) {}
 * //      ^^^^^^^^^^^^^
 * ```
 */
final class ParamList = Impl::ParamList;
