// generated by codegen, do not edit
/**
 * This module provides the public class `ParenPat`.
 */

private import internal.ParenPatImpl
import codeql.rust.elements.Pat

/**
 * A ParenPat. For example:
 * ```rust
 * todo!()
 * ```
 */
final class ParenPat = Impl::ParenPat;
