// generated by codegen, do not edit
/**
 * This module provides the public class `PathSegment`.
 */

private import internal.PathSegmentImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.GenericArgList
import codeql.rust.elements.NameRef
import codeql.rust.elements.ParamList
import codeql.rust.elements.PathType
import codeql.rust.elements.RetType
import codeql.rust.elements.ReturnTypeSyntax
import codeql.rust.elements.TypeRef

/**
 * A PathSegment. For example:
 * ```rust
 * todo!()
 * ```
 */
final class PathSegment = Impl::PathSegment;
