// generated by codegen, do not edit
/**
 * This module provides the public class `PathExprBase`.
 */

private import internal.PathExprBaseImpl
import codeql.rust.elements.Expr

/**
 * A path expression or a variable access in a formatting template. See `PathExpr` and `FormatTemplateVariableAccess` for further details.
 */
final class PathExprBase = Impl::PathExprBase;
