// generated by codegen, do not edit
/**
 * This module provides the public class `Path`.
 */

private import internal.PathImpl
import codeql.rust.elements.PathSegment
import codeql.rust.elements.Resolvable

/**
 * A path. For example:
 * ```rust
 * foo::bar;
 * ```
 */
final class Path = Impl::Path;
