// generated by codegen, do not edit
/**
 * This module provides the public class `PathMeta`.
 */

private import internal.PathMetaImpl
import codeql.rust.elements.Meta
import codeql.rust.elements.Path

final class PathMeta = Impl::PathMeta;
