// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `PathPat`.
 */

private import codeql.rust.generated.PathPat

class PathPatImpl extends Generated::PathPatImpl { }

final private class PathPatImplFinal = PathPatImpl;

final class PathPat extends PathPatImplFinal, Generated::PathPat { }
