// generated by codegen, do not edit
/**
 * This module provides the public class `PatternTypeRepr`.
 */

private import internal.PatternTypeReprImpl
import codeql.rust.elements.Pat
import codeql.rust.elements.TypeRepr

final class PatternTypeRepr = Impl::PatternTypeRepr;
