// generated by codegen, do not edit
/**
 * This module provides the public class `PrefixExpr`.
 */

private import PrefixExprImpl
import codeql.rust.elements.Expr

/**
 * A unary operation expression. For example:
 * ```
 * let x = -42
 * let y = !true
 * let z = *ptr
 * ```
 */
final class PrefixExpr = Impl::PrefixExpr;
