// generated by codegen, do not edit
/**
 * This module provides the public class `PtrTypeRepr`.
 */

private import internal.PtrTypeReprImpl
import codeql.rust.elements.TypeRepr

/**
 * A PtrTypeRepr. For example:
 * ```rust
 * todo!()
 * ```
 */
final class PtrTypeRepr = Impl::PtrTypeRepr;
