// generated by codegen, do not edit
/**
 * This module provides the public class `RangeExpr`.
 */

private import internal.RangeExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr

final class RangeExpr = Impl::RangeExpr;
