// generated by codegen
/**
 * This module provides the AST class  `RangeExpr`.
 */

private import codeql.rust.generated.RangeExpr
private import RangeExprImpl

final private class RangeExprImplFinal = RangeExprImpl;

final class RangeExpr extends RangeExprImplFinal, Generated::RangeExpr { }
