// generated by codegen, do not edit
/**
 * This module provides the public class `RangePat`.
 */

private import internal.RangePatImpl
import codeql.rust.elements.Pat

final class RangePat = Impl::RangePat;
