// generated by codegen, do not edit
/**
 * This module provides the public class `RawPtrType`.
 */

private import internal.RawPtrTypeImpl
import codeql.rust.elements.Type

final class RawPtrType = Impl::RawPtrType;
