// generated by codegen, do not edit
/**
 * This module provides the public class `RecordFieldList`.
 */

private import internal.RecordFieldListImpl
import codeql.rust.elements.FieldList
import codeql.rust.elements.RecordField

/**
 * A RecordFieldList. For example:
 * ```rust
 * todo!()
 * ```
 */
final class RecordFieldList = Impl::RecordFieldList;
