// generated by codegen
/**
 * This module provides the AST class  `RecordPat`.
 */

private import codeql.rust.generated.RecordPat
private import RecordPatImpl

final private class RecordPatImplFinal = RecordPatImpl;

final class RecordPat extends RecordPatImplFinal, Generated::RecordPat { }
