// generated by codegen, do not edit
/**
 * This module provides the public class `RecordPat`.
 */

private import internal.RecordPatImpl
import codeql.rust.elements.Pat
import codeql.rust.elements.PathAstNode
import codeql.rust.elements.RecordPatFieldList

/**
 * A record pattern. For example:
 * ```rust
 * match x {
 *     Foo { a: 1, b: 2 } => "ok",
 *     Foo { .. } => "fail",
 * }
 * ```
 */
final class RecordPat = Impl::RecordPat;
