// generated by codegen
/**
 * This module provides the AST class  `RecordLitExpr`.
 */

private import codeql.rust.generated.RecordLitExpr
private import RecordLitExprImpl

final private class RecordLitExprImplFinal = RecordLitExprImpl;

final class RecordLitExpr extends RecordLitExprImplFinal, Generated::RecordLitExpr { }
