// generated by codegen, do not edit
/**
 * This module provides the public class `RecordPat`.
 */

private import internal.RecordPatImpl
import codeql.rust.elements.Pat
import codeql.rust.elements.Path
import codeql.rust.elements.RecordPatFieldList

final class RecordPat = Impl::RecordPat;
