// generated by codegen, do not edit
/**
 * This module provides the public class `ReferenceType`.
 */

private import internal.ReferenceTypeImpl
import codeql.rust.elements.Type

final class ReferenceType = Impl::ReferenceType;
