// generated by codegen, do not edit
/**
 * This module provides the public class `RefPat`.
 */

private import internal.RefPatImpl
import codeql.rust.elements.Pat

final class RefPat = Impl::RefPat;
