// generated by codegen, do not edit
/**
 * This module provides the public class `RestPat`.
 */

private import internal.RestPatImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Pat

/**
 * A rest pattern (`..`) in a tuple, slice, or struct pattern.
 *
 * For example:
 * ```rust
 * let (a, .., z) = (1, 2, 3);
 * //      ^^
 * ```
 */
final class RestPat = Impl::RestPat;
