// generated by codegen, do not edit
/**
 * This module provides the public class `ReturnTypeSyntax`.
 */

private import internal.ReturnTypeSyntaxImpl
import codeql.rust.elements.AstNode

final class ReturnTypeSyntax = Impl::ReturnTypeSyntax;
