// generated by codegen
/**
 * This module provides the AST class  `SlicePat`.
 */

private import codeql.rust.generated.SlicePat
private import SlicePatImpl

final private class SlicePatImplFinal = SlicePatImpl;

final class SlicePat extends SlicePatImplFinal, Generated::SlicePat { }
