// generated by codegen, do not edit
/**
 * This module provides the public class `SourceFile`.
 */

private import internal.SourceFileImpl
import codeql.rust.elements.AnyAttr
import codeql.rust.elements.AstNode
import codeql.rust.elements.Item

/**
 * A source file.
 *
 * For example:
 * ```rust
 * // main.rs
 * fn main() {}
 * ```
 */
final class SourceFile = Impl::SourceFile;
