// generated by codegen, do not edit
/**
 * This module provides the public class `SourceFile`.
 */

private import internal.SourceFileImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Attr
import codeql.rust.elements.Item

/**
 * A SourceFile. For example:
 * ```rust
 * todo!()
 * ```
 */
final class SourceFile = Impl::SourceFile;
