// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Stmt`.
 */

private import codeql.rust.generated.Stmt

class StmtImpl extends Generated::StmtImpl { }

final private class StmtImplFinal = StmtImpl;

final class Stmt extends StmtImplFinal, Generated::Stmt { }
