// generated by codegen, do not edit
/**
 * This module provides the public class `StructPatField`.
 */

private import internal.StructPatFieldImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Attr
import codeql.rust.elements.NameRef
import codeql.rust.elements.Pat

/**
 * A field in a struct pattern. For example `a: 1` in:
 * ```rust
 * let Foo { a: 1, b: 2 } = foo;
 * ```
 */
final class StructPatField = Impl::StructPatField;
