// generated by codegen, do not edit
/**
 * This module provides the public class `TokenTree`.
 */

private import internal.TokenTreeImpl
import codeql.rust.elements.AstNode

/**
 * A token tree in a macro definition or invocation.
 *
 * For example:
 * ```rust
 * println!("{} {}!", "Hello", "world");
 * //      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 * ```
 * ```
 * macro_rules! foo { ($x:expr) => { $x + 1 }; }
 * //                 ^^^^^^^^^^^^^^^^^^^^^^^
 * ```
 */
final class TokenTree = Impl::TokenTree;
