// generated by codegen, do not edit
/**
 * This module provides the public class `TraitItem`.
 */

private import internal.TraitItemImpl
import codeql.rust.elements.FunctionType
import codeql.rust.elements.TypeItem

final class TraitItem = Impl::TraitItem;
