// generated by codegen, do not edit
/**
 * This module provides the public class `TypeArg`.
 */

private import internal.TypeArgImpl
import codeql.rust.elements.GenericArg
import codeql.rust.elements.TypeRepr

/**
 * A TypeArg. For example:
 * ```rust
 * todo!()
 * ```
 */
final class TypeArg = Impl::TypeArg;
