// generated by codegen, do not edit
/**
 * This module provides the public class `TypeRef`.
 */

private import internal.TypeRefImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Unimplemented

/**
 * The base class for type references.
 * ```
 * let x: i32;
 * let y: Vec<i32>;
 * let z: Option<i32>;
 * ```
 */
final class TypeRef = Impl::TypeRef;
