// generated by codegen, do not edit
/**
 * This module provides the public class `UnderscoreExpr`.
 */

private import internal.UnderscoreExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr

final class UnderscoreExpr = Impl::UnderscoreExpr;
