// generated by codegen, do not edit
/**
 * This module provides the public class `Unextracted`.
 */

private import internal.UnextractedImpl
import codeql.rust.elements.Element

/**
 * The base class marking everything that was not properly extracted for some reason, such as:
 * * syntax errors
 * * insufficient context information
 * * yet unimplemented parts of the extractor
 */
final class Unextracted = Impl::Unextracted;
