// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnimplementedDeclaration`.
 */

private import codeql.rust.generated.UnimplementedDeclaration

class UnimplementedDeclaration extends Generated::UnimplementedDeclaration { }
