// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnknownLocation`.
 */

private import codeql.rust.generated.UnknownLocation

class UnknownLocation extends Generated::UnknownLocation { }
