// generated by codegen, do not edit
/**
 * This module provides the public class `UseTree`.
 */

private import internal.UseTreeImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Path
import codeql.rust.elements.Rename
import codeql.rust.elements.UseTreeList

/**
 * A UseTree. For example:
 * ```rust
 * use std::collections::HashMap;
 * use std::collections::*;
 * use std::collections::HashMap as MyHashMap;
 * use std::collections::{self, HashMap, HashSet};
 * ```
 */
final class UseTree = Impl::UseTree;
