// generated by codegen, do not edit
/**
 * This module provides the public class `Visibility`.
 */

private import internal.VisibilityImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.Path

/**
 * A Visibility. For example:
 * ```rust
 * todo!()
 * ```
 */
final class Visibility = Impl::Visibility;
