// generated by codegen, do not edit
/**
 * This module provides the public class `WhereClause`.
 */

private import internal.WhereClauseImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.WherePred

/**
 * A WhereClause. For example:
 * ```rust
 * todo!()
 * ```
 */
final class WhereClause = Impl::WhereClause;
