// generated by codegen, do not edit
/**
 * This module provides the public class `WherePred`.
 */

private import internal.WherePredImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.GenericParamList
import codeql.rust.elements.Lifetime
import codeql.rust.elements.TypeBoundList
import codeql.rust.elements.TypeRepr

/**
 * A WherePred. For example:
 * ```rust
 * todo!()
 * ```
 */
final class WherePred = Impl::WherePred;
