// generated by codegen, do not edit
/**
 * This module provides the public class `WhereClause`.
 */

private import internal.WhereClauseImpl
import codeql.rust.elements.AstNode
import codeql.rust.elements.WherePred

/**
 * A where clause in a generic declaration.
 *
 * For example:
 * ```rust
 * fn foo<T>(t: T) where T: Debug {}
 * //              ^^^^^^^^^^^^^^
 * ```
 */
final class WhereClause = Impl::WhereClause;
