// generated by codegen, do not edit
/**
 * This module provides the public class `WhileExpr`.
 */

private import internal.WhileExprImpl
import codeql.rust.elements.Attr
import codeql.rust.elements.Expr
import codeql.rust.elements.LoopingExpr

/**
 * A WhileExpr. For example:
 * ```rust
 * todo!()
 * ```
 */
final class WhileExpr = Impl::WhileExpr;
