// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `YeetExpr`.
 */

private import codeql.rust.generated.YeetExpr

/**
 * A `yeet` expression. For example:
 * ```
 * if x < size {
 *    do yeet "index out of bounds";
 * }
 * ```
 */
class YeetExpr extends Generated::YeetExpr { }
