// generated by codegen, do not edit
/**
 * This module provides the public class `YeetExpr`.
 */

private import YeetExprImpl
import codeql.rust.elements.Expr

/**
 * A `yeet` expression. For example:
 * ```
 * if x < size {
 *    do yeet "index out of bounds";
 * }
 * ```
 */
final class YeetExpr = Impl::YeetExpr;
