// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `YieldExpr`.
 */

private import codeql.rust.generated.YieldExpr

/**
 * A `yield` expression. For example:
 * ```
 * let one = #[coroutine]
 *     || {
 *         yield 1;
 *     };
 * ```
 */
class YieldExpr extends Generated::YieldExpr { }
