// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `YieldExpr`.
 */

private import codeql.rust.generated.YieldExpr

class YieldExprImpl extends Generated::YieldExprImpl { }

final private class YieldExprImplFinal = YieldExprImpl;

final class YieldExpr extends YieldExprImplFinal, Generated::YieldExpr { }
