// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

//go:generate depstubber --vendor --auto
package main

import "clevergo.tech/clevergo"

func main() {}
func source() interface{} {
	return nil
}

// Package clevergo.tech/clevergo@v0.5.2
func ClevergoTechClevergov052() {
	// Header write via method calls.
	{
		// Header write via method calls on clevergo.tech/clevergo.Context.
		{
			// func (*Context).SetHeader(key string, value string)
			{
				keyString839 := source().(string)
				valString273 := source().(string)
				var rece clevergo.Context
				rece.SetHeader(keyString839, valString273) // $headerKey=keyString839 $headerVal=valString273
			}
		}
	}
}
