// generated by codegen, do not edit
/**
 * This module provides the public class `ConcreteTypeCanonicalPath`.
 */

private import internal.ConcreteTypeCanonicalPathImpl
import codeql.rust.elements.canonical_paths.ParametrizedCanonicalPath
import codeql.rust.elements.canonical_paths.TypeCanonicalPath

/**
 * A canonical path for an actual type.
 */
final class ConcreteTypeCanonicalPath = Impl::ConcreteTypeCanonicalPath;
