// generated by codegen, do not edit
/**
 * This module provides the public class `ImplItemCanonicalPath`.
 */

private import internal.ImplItemCanonicalPathImpl
import codeql.rust.elements.canonical_paths.CanonicalPath
import codeql.rust.elements.canonical_paths.ParametrizedCanonicalPath
import codeql.rust.elements.canonical_paths.TypeCanonicalPath

/**
 * A canonical path for an item defined in an impl (a method or associated type).
 */
final class ImplItemCanonicalPath = Impl::ImplItemCanonicalPath;
