// generated by codegen, do not edit
/**
 * This module provides the public class `TypeGenericTypeArg`.
 */

private import internal.TypeGenericTypeArgImpl
import codeql.rust.elements.canonical_paths.TypeCanonicalPath
import codeql.rust.elements.canonical_paths.TypeGenericArg

/**
 * A generic argument for a type that is a type.
 */
final class TypeGenericTypeArg = Impl::TypeGenericTypeArg;
