name: Build Swift CodeQL pack
description: Builds the Swift CodeQL pack
runs:
  using: composite
  steps:
    - uses: ./swift/actions/share-extractor-pack
    - uses: actions/setup-python@v4
      with:
        python-version-file: 'swift/.python-version'
    - uses: redsun82/setup-swift@b2b6f77ab14f6a9b136b520dc53ec8eca27d2b99
      with:
        swift-version: "5.8"
    - uses: ./.github/actions/fetch-codeql
    - id: query-cache
      uses: ./.github/actions/cache-query-compilation
      with:
        key: swift-integration
    - name: Run integration tests
      shell: bash
      run: |
        python swift/ql/integration-tests/runner.py --compilation-cache "${{ steps.query-cache.outputs.cache-dir }}"
      env:
        SEMMLE_DEBUG_TRACER: 10000
    - name: Upload test logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: swift-integration-tests-logs-${{ runner.os }}
        path: |
          swift/ql/integration-tests/**/*db/log
        retention-days: 1
