// generated by codegen/codegen.py, do not edit
/**
 * This module provides the class `AccessorOrNamedFunction`.
 */

private import AccessorOrNamedFunctionImpl
import codeql.swift.elements.decl.Function

/**
 * INTERNAL: Do not use.
 */
final class AccessorOrNamedFunction = Impl::AccessorOrNamedFunction;
