// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BoundGenericType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.BoundGenericType

/**
 * INTERNAL: This module contains the customizable definition of `BoundGenericType` and should not
 * be referenced directly.
 */
module Impl {
  class BoundGenericType extends Generated::BoundGenericType { }
}
