// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BuiltinFixedArrayType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.BuiltinFixedArrayType

/**
 * INTERNAL: This module contains the customizable definition of `BuiltinFixedArrayType` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A builtin type representing N values stored contiguously.
   */
  class BuiltinFixedArrayType extends Generated::BuiltinFixedArrayType { }
}
