// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BuiltinUnsafeValueBufferType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.BuiltinUnsafeValueBufferType

/**
 * INTERNAL: This module contains the customizable definition of `BuiltinUnsafeValueBufferType` and should not
 * be referenced directly.
 */
module Impl {
  class BuiltinUnsafeValueBufferType extends Generated::BuiltinUnsafeValueBufferType { }
}
