// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BuiltinRawPointerType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.BuiltinRawPointerType

/**
 * INTERNAL: This module contains the customizable definition of `BuiltinRawPointerType` and should not
 * be referenced directly.
 */
module Impl {
  class BuiltinRawPointerType extends Generated::BuiltinRawPointerType { }
}
