// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ExistentialArchetypeType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.ExistentialArchetypeType

/**
 * INTERNAL: This module contains the customizable definition of `ExistentialArchetypeType` and should not
 * be referenced directly.
 */
module Impl {
  class ExistentialArchetypeType extends Generated::ExistentialArchetypeType { }
}
