// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `PackExpansionType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.PackExpansionType

/**
 * INTERNAL: This module contains the customizable definition of `PackExpansionType` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A type of PackExpansionExpr, see PackExpansionExpr for more information.
   */
  class PackExpansionType extends Generated::PackExpansionType { }
}
