// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ProtocolCompositionType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.ProtocolCompositionType

/**
 * INTERNAL: This module contains the customizable definition of `ProtocolCompositionType` and should not
 * be referenced directly.
 */
module Impl {
  class ProtocolCompositionType extends Generated::ProtocolCompositionType { }
}
