// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ReferenceStorageType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.ReferenceStorageType

/**
 * INTERNAL: This module contains the customizable definition of `ReferenceStorageType` and should not
 * be referenced directly.
 */
module Impl {
  class ReferenceStorageType extends Generated::ReferenceStorageType { }
}
