// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnownedStorageType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.UnownedStorageType

/**
 * INTERNAL: This module contains the customizable definition of `UnownedStorageType` and should not
 * be referenced directly.
 */
module Impl {
  class UnownedStorageType extends Generated::UnownedStorageType { }
}
