// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `WeakStorageType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.type.WeakStorageType

/**
 * INTERNAL: This module contains the customizable definition of `WeakStorageType` and should not
 * be referenced directly.
 */
module Impl {
  class WeakStorageType extends Generated::WeakStorageType { }
}
