import "../../misc/just/lib.just"

[no-cd]
format *ARGS=".": (_ql_format ARGS)

db_checks := default_db_checks + """\
    --check-repeated-labels \
    --check-redefined-labels \
    --check-use-before-definition \
"""

consistency := "--consistency-queries=" + source_dir() / "consistency-queries"

[no-cd]
test *ARGS=".": (_codeql_test "swift" ARGS db_checks consistency)
