import '../lib.just'

install: (_bazel ['run', '@codeql//swift:install'])

[group('build')]
build: (_build_dist "swift")

generate: (_bazel ['run', '@codeql//swift/codegen'])

format *ARGS=".": (_format_cpp ARGS)

roots := [source_dir() / 'ql/test']

[group('test')]
language-tests *EXTRA_ARGS: (_language_tests (roots ++ EXTRA_ARGS))

[group('test')]
extra-tests: (_sembuild "target/test/check-queries-swift") (_sembuild "target/test/check-db-upgrades-swift") (_sembuild "target/test/check-db-downgrades-swift")
