...
  umask(0); // BAD
...
  cmusk = umask(S_IRWXG | S_IRWXO); // GOOD
  ...
  fchmod(fileno(fp), 0555 - cmusk); // BAD 
  ...
  fchmod(fileno(fp), 0555 & ~curumsk); // GOOD
...
  umask(0666);
  chmod(0666); // BAD
...
  umask(0022);
  chmod(0666); // GOOD
...
