// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

package main

import "clevergo.tech/clevergo"

func main()                 {}
func sink(v ...interface{}) {}

// Package clevergo.tech/clevergo@v0.5.2
func ClevergoTechClevergov052() {
	// Untrusted flow sources from method calls.
	{
		// Untrusted flow sources from method calls on clevergo.tech/clevergo.Context.
		{
			// func (*Context).BasicAuth() (username string, password string, ok bool)
			{
				var receiverContext656 clevergo.Context
				resultUsername414, resultPassword518, _ := receiverContext656.BasicAuth()
				sink(
					resultUsername414, // $SinkingUntrustedFlowSource
					resultPassword518, // $SinkingUntrustedFlowSource
				)
			}
			// func (*Context).Decode(v interface{}) (err error)
			{
				var receiverContext650 clevergo.Context
				var paramV784 interface{}
				receiverContext650.Decode(paramV784)
				sink(paramV784) // $SinkingUntrustedFlowSource
			}
			// func (*Context).DefaultQuery(key string, defaultVlue string) string
			{
				var receiverContext957 clevergo.Context
				result520 := receiverContext957.DefaultQuery("", "")
				sink(result520) // $SinkingUntrustedFlowSource
			}
			// func (*Context).FormValue(key string) string
			{
				var receiverContext443 clevergo.Context
				result127 := receiverContext443.FormValue("")
				sink(result127) // $SinkingUntrustedFlowSource
			}
			// func (*Context).GetHeader(name string) string
			{
				var receiverContext483 clevergo.Context
				result989 := receiverContext483.GetHeader("")
				sink(result989) // $SinkingUntrustedFlowSource
			}
			// func (*Context).PostFormValue(key string) string
			{
				var receiverContext982 clevergo.Context
				result417 := receiverContext982.PostFormValue("")
				sink(result417) // $SinkingUntrustedFlowSource
			}
			// func (*Context).QueryParam(key string) string
			{
				var receiverContext584 clevergo.Context
				result991 := receiverContext584.QueryParam("")
				sink(result991) // $SinkingUntrustedFlowSource
			}
			// func (*Context).QueryString() string
			{
				var receiverContext881 clevergo.Context
				result186 := receiverContext881.QueryString()
				sink(result186) // $SinkingUntrustedFlowSource
			}
		}
		// Untrusted flow sources from method calls on clevergo.tech/clevergo.Params.
		{
			// func (Params).String(name string) string
			{
				var receiverParams284 clevergo.Params
				result908 := receiverParams284.String("")
				sink(result908) // $SinkingUntrustedFlowSource
			}
		}
	}
	// Untrusted flow sources from struct fields.
	{
		// Untrusted flow sources from clevergo.tech/clevergo.Context struct fields.
		{
			structContext137 := new(clevergo.Context)
			sink(structContext137.Params) // $SinkingUntrustedFlowSource
		}
		// Untrusted flow sources from clevergo.tech/clevergo.Param struct fields.
		{
			structParam494 := new(clevergo.Param)
			sink(
				structParam494.Value, // $SinkingUntrustedFlowSource
				structParam494.Key,   // $SinkingUntrustedFlowSource
			)
		}
	}
	// Untrusted flow sources from types.
	{
		{
			var typeParams873 clevergo.Params
			sink(typeParams873) // $SinkingUntrustedFlowSource
		}
	}
}

//go:generate depstubber -vendor clevergo.tech/clevergo Context,Param,Params
//go:generate depstubber -write_module_txt
