// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `AbiSafeConversionExpr`.
 */

private import internal.AbiSafeConversionExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class AbiSafeConversionExpr = Impl::AbiSafeConversionExpr;
