// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ArrayToPointerExpr`.
 */

private import ArrayToPointerExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class ArrayToPointerExpr = Impl::ArrayToPointerExpr;
