// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `AutoClosureExpr`.
 */

private import AutoClosureExprImpl
import codeql.swift.elements.expr.ClosureExpr

final class AutoClosureExpr = Impl::AutoClosureExpr;
