// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `AwaitExpr`.
 */

private import internal.AwaitExprImpl
import codeql.swift.elements.expr.IdentityExpr

final class AwaitExpr = Impl::AwaitExpr;
