// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `BinaryExpr`.
 */

private import internal.BinaryExprImpl
import codeql.swift.elements.expr.ApplyExpr

final class BinaryExpr = Impl::BinaryExpr;
