// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BridgeFromObjCExpr`.
 */

private import codeql.swift.generated.expr.BridgeFromObjCExpr

class BridgeFromObjCExpr extends Generated::BridgeFromObjCExpr { }
