// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `CallExpr`.
 */

private import codeql.swift.generated.expr.CallExpr

class CallExpr extends Generated::CallExpr { }
