// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `CoerceExpr`.
 */

private import codeql.swift.generated.expr.CoerceExpr

class CoerceExpr extends Generated::CoerceExpr { }
