// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `CollectionUpcastConversionExpr`.
 */

private import CollectionUpcastConversionExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class CollectionUpcastConversionExpr = Impl::CollectionUpcastConversionExpr;
