// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ConditionalCheckedCastExpr`.
 */

private import internal.ConditionalCheckedCastExprImpl
import codeql.swift.elements.expr.CheckedCastExpr

final class ConditionalCheckedCastExpr = Impl::ConditionalCheckedCastExpr;
