// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `DictionaryExpr`.
 */

private import internal.DictionaryExprImpl
import codeql.swift.elements.expr.CollectionExpr
import codeql.swift.elements.expr.Expr

final class DictionaryExpr = Impl::DictionaryExpr;
