// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `DotSelfExpr`.
 */

private import internal.DotSelfExprImpl
import codeql.swift.elements.expr.IdentityExpr

final class DotSelfExpr = Impl::DotSelfExpr;
