// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `DynamicMemberRefExpr`.
 */

private import internal.DynamicMemberRefExprImpl
import codeql.swift.elements.expr.DynamicLookupExpr

final class DynamicMemberRefExpr = Impl::DynamicMemberRefExpr;
