// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `DynamicLookupExpr`.
 */

private import DynamicLookupExprImpl
import codeql.swift.elements.expr.LookupExpr

final class DynamicLookupExpr = Impl::DynamicLookupExpr;
