// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ErasureExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.ErasureExpr

/**
 * INTERNAL: This module contains the customizable definition of `ErasureExpr` and should not
 * be referenced directly.
 */
module Impl {
  class ErasureExpr extends Generated::ErasureExpr { }
}
