// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ErrorExpr`.
 */

private import internal.ErrorExprImpl
import codeql.swift.elements.ErrorElement
import codeql.swift.elements.expr.Expr

final class ErrorExpr = Impl::ErrorExpr;
