// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ExistentialMetatypeToObjectExpr`.
 */

private import codeql.swift.generated.expr.ExistentialMetatypeToObjectExpr

class ExistentialMetatypeToObjectExpr extends Generated::ExistentialMetatypeToObjectExpr { }
