// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `FloatLiteralExpr`.
 */

private import internal.FloatLiteralExprImpl
import codeql.swift.elements.expr.NumberLiteralExpr

final class FloatLiteralExpr = Impl::FloatLiteralExpr;
