// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ImplicitConversionExpr`.
 */

private import internal.ImplicitConversionExprImpl
import codeql.swift.elements.expr.Expr

final class ImplicitConversionExpr = Impl::ImplicitConversionExpr;
