// generated by codegen/codegen.py, remove this comment if you wish to edit this file
private import codeql.swift.generated.expr.InitializerRefCallExpr

class InitializerRefCallExpr extends Generated::InitializerRefCallExpr { }
