// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `InitializerRefCallExpr`.
 */

private import InitializerRefCallExprImpl
import codeql.swift.elements.expr.SelfApplyExpr

/**
 * INTERNAL: Do not use.
 */
final class InitializerRefCallExpr = Impl::InitializerRefCallExpr;
