// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `InOutExpr`.
 */

private import internal.InOutExprImpl
import codeql.swift.elements.expr.Expr

final class InOutExpr = Impl::InOutExpr;
