// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 *  This module defines the hook used internally to tweak the characteristic predicate of
 *  `IsExpr` synthesized instances.
 *  INTERNAL: Do not use.
 */

private import codeql.swift.generated.Raw

/**
 *  The characteristic predicate of `IsExpr` synthesized instances.
 *  INTERNAL: Do not use.
 */
predicate constructIsExpr(Raw::IsExpr id) { any() }
