// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `KeyPathApplicationExpr`.
 */

private import internal.KeyPathApplicationExprImpl
import codeql.swift.elements.expr.Expr

final class KeyPathApplicationExpr = Impl::KeyPathApplicationExpr;
