// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `LinearFunctionExpr`.
 */

private import internal.LinearFunctionExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class LinearFunctionExpr = Impl::LinearFunctionExpr;
