// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `LoadExpr`.
 */

private import internal.LoadExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class LoadExpr = Impl::LoadExpr;
