// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `MaterializePackExpr`.
 */

private import codeql.swift.generated.expr.MaterializePackExpr

/**
 * An expression that materializes a pack during expansion. Appears around PackExpansionExpr.
 *
 * More details:
 * https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md
 */
class MaterializePackExpr extends Generated::MaterializePackExpr { }
