// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `MaterializePackExpr`.
 */

private import internal.MaterializePackExprImpl
import codeql.swift.elements.expr.Expr

/**
 * An expression that materializes a pack during expansion. Appears around PackExpansionExpr.
 *
 * More details:
 * https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md
 */
final class MaterializePackExpr = Impl::MaterializePackExpr;
