// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `MetatypeConversionExpr`.
 */

private import codeql.swift.generated.expr.MetatypeConversionExpr

class MetatypeConversionExpr extends Generated::MetatypeConversionExpr { }
