// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `MetatypeConversionExpr`.
 */

private import MetatypeConversionExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class MetatypeConversionExpr = Impl::MetatypeConversionExpr;
