// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `ObjCSelectorExpr`.
 */

private import internal.ObjCSelectorExprImpl
import codeql.swift.elements.expr.Expr
import codeql.swift.elements.decl.Function

final class ObjCSelectorExpr = Impl::ObjCSelectorExpr;
