// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `OpaqueValueExpr`.
 */

private import OpaqueValueExprImpl
import codeql.swift.elements.expr.Expr

final class OpaqueValueExpr = Impl::OpaqueValueExpr;
