// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `OverloadedDeclRefExpr`.
 */

private import internal.OverloadedDeclRefExprImpl
import codeql.swift.elements.ErrorElement
import codeql.swift.elements.expr.Expr
import codeql.swift.elements.decl.ValueDecl

/**
 * An ambiguous expression that might refer to multiple declarations. This will be present only
 * for failing compilations.
 */
final class OverloadedDeclRefExpr = Impl::OverloadedDeclRefExpr;
