// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `PointerToPointerExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.expr.PointerToPointerExpr

/**
 * INTERNAL: This module contains the customizable definition of `PointerToPointerExpr` and should not
 * be referenced directly.
 */
module Impl {
  class PointerToPointerExpr extends Generated::PointerToPointerExpr { }
}
