// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `PostfixUnaryExpr`.
 */

private import internal.PostfixUnaryExprImpl
import codeql.swift.elements.expr.ApplyExpr

final class PostfixUnaryExpr = Impl::PostfixUnaryExpr;
