// generated by codegen/codegen.py, remove this comment if you wish to edit this file
private import codeql.swift.generated.Raw

predicate constructRebindSelfInInitializerExpr(Raw::RebindSelfInInitializerExpr id) { any() }
