// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `RegexLiteralExpr`.
 */

private import internal.RegexLiteralExprImpl
import codeql.swift.elements.expr.LiteralExpr

/**
 * A regular expression literal which is checked at compile time, for example `/a(a|b)*b/`.
 */
final class RegexLiteralExpr = Impl::RegexLiteralExpr;
