// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `StringLiteralExpr`.
 */

private import internal.StringLiteralExprImpl
import codeql.swift.elements.expr.BuiltinLiteralExpr

final class StringLiteralExpr = Impl::StringLiteralExpr;
