// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `UnderlyingToOpaqueExpr`.
 */

private import UnderlyingToOpaqueExprImpl
import codeql.swift.elements.expr.ImplicitConversionExpr

final class UnderlyingToOpaqueExpr = Impl::UnderlyingToOpaqueExpr;
