// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `UnresolvedTypeConversionExpr`.
 */

private import UnresolvedTypeConversionExprImpl
import codeql.swift.elements.ErrorElement
import codeql.swift.elements.expr.ImplicitConversionExpr

final class UnresolvedTypeConversionExpr = Impl::UnresolvedTypeConversionExpr;
