// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `VarargExpansionExpr`.
 */

private import internal.VarargExpansionExprImpl
import codeql.swift.elements.expr.Expr

final class VarargExpansionExpr = Impl::VarargExpansionExpr;
