import "../../misc/just/lib.just"

[no-cd]
format *ARGS=".": (_ql_format ARGS)

db_checks := default_db_checks

consistency := "--consistency-queries=" + source_dir() / "consistency-queries"

[no-cd]
test *ARGS=".": (_codeql_test "rust" ARGS db_checks consistency)