import "../../lib.just"

[no-cd]
format *ARGS=".": (_ql_format ARGS)

all_checks := default_db_checks + """\
     --consistency-queries=""" + source_dir() / "consistency-queries"

[no-cd]
test *ARGS=".": (_just "generate") (_codeql_test "rust" "" all_checks ARGS)
