/**
 * Provides models for the `javax.json` package.
 */

import java
private import semmle.code.java.dataflow.ExternalFlow

private class FlowSummaries extends SummaryModelCsv {
  override predicate row(string row) {
    row =
      ["javax", "jakarta"] + ".json;" +
        [
          "Json;false;createArrayBuilder;(JsonArray);;Argument[0];ReturnValue;taint",
          "Json;false;createArrayBuilder;(Collection);;Element of Argument[0];ReturnValue;taint",
          "Json;false;createDiff;;;Argument[0..1];ReturnValue;taint",
          "Json;false;createMergeDiff;;;Argument[0..1];ReturnValue;taint",
          "Json;false;createMergePatch;;;Argument[0];ReturnValue;taint",
          "Json;false;createObjectBuilder;(JsonObject);;Argument[0];ReturnValue;taint",
          "Json;false;createObjectBuilder;(Map);;MapKey of Argument[0];ReturnValue;taint",
          "Json;false;createObjectBuilder;(Map);;MapValue of Argument[0];ReturnValue;taint",
          "Json;false;createPatch;;;Argument[0];ReturnValue;taint",
          "Json;false;createReader;;;Argument[0];ReturnValue;taint",
          "Json;false;createWriter;;;Argument[0];ReturnValue;taint",
          "JsonArray;false;getBoolean;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getBoolean;;;Argument[1];ReturnValue;value",
          "JsonArray;false;getInt;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getInt;;;Argument[1];ReturnValue;value",
          "JsonArray;false;getJsonArray;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getJsonNumber;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getJsonObject;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getJsonString;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getString;;;Argument[-1];ReturnValue;taint",
          "JsonArray;false;getString;;;Argument[1];ReturnValue;value",
          "JsonArray;false;getValuesAs;;;Argument[-1];ReturnValue;taint",
          "JsonArrayBuilder;false;add;;;Argument[-1];ReturnValue;value",
          "JsonArrayBuilder;false;add;(boolean);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(double);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(long);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(JsonArrayBuilder);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(JsonObjectBuilder);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(JsonValue);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(String);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(BigDecimal);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(BigInteger);;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,boolean);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,double);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,int);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,long);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,JsonArrayBuilder);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,JsonObjectBuilder);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,JsonValue);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,String);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,BigDecimal);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;add;(int,BigInteger);;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;addAll;;;Argument[0];Argument[-1];taint",
          "JsonArrayBuilder;false;addAll;;;Argument[-1];ReturnValue;value",
          "JsonArrayBuilder;false;addNull;;;Argument[-1];ReturnValue;value",
          "JsonArrayBuilder;false;build;;;Argument[-1];ReturnValue;taint",
          "JsonArrayBuilder;false;remove;;;Argument[-1];ReturnValue;value",
          "JsonArrayBuilder;false;set;;;Argument[1];Argument[-1];taint",
          "JsonArrayBuilder;false;set;;;Argument[-1];ReturnValue;value",
          "JsonArrayBuilder;false;setNull;;;Argument[-1];ReturnValue;value",
          "JsonNumber;false;bigDecimalValue;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;bigIntegerValue;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;bigIntegerValueExact;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;doubleValue;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;intValue;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;intValueExact;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;longValue;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;longValueExact;;;Argument[-1];ReturnValue;taint",
          "JsonNumber;false;numberValue;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getBoolean;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getBoolean;;;Argument[1];ReturnValue;value",
          "JsonObject;false;getInt;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getInt;;;Argument[1];ReturnValue;value",
          "JsonObject;false;getJsonArray;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getJsonNumber;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getJsonObject;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getJsonString;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getString;;;Argument[-1];ReturnValue;taint",
          "JsonObject;false;getString;;;Argument[1];ReturnValue;value",
          "JsonObjectBuilder;false;add;;;Argument[-1];ReturnValue;value",
          "JsonObjectBuilder;false;add;;;Argument[1];Argument[-1];taint",
          "JsonObjectBuilder;false;addAll;;;Argument[0];ReturnValue;value",
          "JsonObjectBuilder;false;addAll;;;Argument[-1];ReturnValue;value",
          "JsonObjectBuilder;false;addNull;;;Argument[-1];ReturnValue;value",
          "JsonObjectBuilder;false;build;;;Argument[-1];ReturnValue;taint",
          "JsonParserFactory;false;createParser;;;Argument[0];ReturnValue;taint",
          "JsonPatch;false;apply;;;Argument[-1];ReturnValue;taint",
          "JsonPatch;false;apply;;;Argument[0];ReturnValue;taint",
          "JsonPatch;false;toJsonArray;;;Argument[-1];ReturnValue;taint",
          "JsonReader;false;read;;;Argument[-1];ReturnValue;taint",
          "JsonReader;false;readArray;;;Argument[-1];ReturnValue;taint",
          "JsonReader;false;readObject;;;Argument[-1];ReturnValue;taint",
          "JsonReader;false;readValue;;;Argument[-1];ReturnValue;taint",
          "JsonReaderFactory;false;createReader;;;Argument[0];ReturnValue;taint",
          "JsonString;false;getChars;;;Argument[-1];ReturnValue;taint",
          "JsonString;false;getString;;;Argument[-1];ReturnValue;taint",
          "JsonStructure;true;getValue;;;Argument[-1];ReturnValue;taint",
          "JsonValue;true;asJsonArray;;;Argument[-1];ReturnValue;taint",
          "JsonValue;true;asJsonObject;;;Argument[-1];ReturnValue;taint",
          "JsonValue;true;toString;;;Argument[-1];ReturnValue;taint",
          "JsonWriter;false;write;;;Argument[0];Argument[-1];taint",
          "JsonWriter;false;writeArray;;;Argument[0];Argument[-1];taint",
          "JsonWriter;false;writeObject;;;Argument[0];Argument[-1];taint",
          "JsonWriterFactory;false;createWriter;;;Argument[-1];Argument[0];taint"
        ]
  }
}
