load("//misc/bazel:rust.bzl", "codeql_rust_binary")
load("//misc/bazel/3rdparty/tree_sitter_extractors_deps:defs.bzl", "aliases", "all_crate_deps")
load("//unified:platforms.bzl", "UNIFIED_SUPPORTED_PLATFORMS")

exports_files(["Cargo.toml"])

codeql_rust_binary(
    name = "extractor",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [
        "ast_types.yml",
        "swift_node_types.yml",
    ],
    data = select({
        "@platforms//os:linux": ["//unified/swift-syntax-rs:swift_runtime_libs"],
        "//conditions:default": [],
    }),
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    target_compatible_with = UNIFIED_SUPPORTED_PLATFORMS,
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//shared/tree-sitter-extractor",
        "//shared/yeast",
        "//unified/swift-syntax-rs:swift_syntax_rs",
    ],
)
