package tsparser

// GetStaticTS7Metadata returns hardcoded metadata for TypeScript 7.
// This must be kept in sync with the TypeScript compiler's SyntaxKind and
// NodeFlags enums.
//
// The SyntaxKind values here correspond to the TypeScript 7 (Go port)
// compiler. The Java extractor uses the string names (not numeric IDs)
// to identify node kinds, so the exact numeric values only matter for
// the metadata response.
func GetStaticTS7Metadata() *Metadata {
	return &Metadata{
		SyntaxKinds: syntaxKinds,
		NodeFlags:   nodeFlags,
	}
}

// GetSyntaxKinds returns the raw SyntaxKind name→number map.
func GetSyntaxKinds() map[string]int {
	return syntaxKinds
}

// BuildKindToNameMap returns a number→name reverse map for SyntaxKinds.
func BuildKindToNameMap() map[uint32]string {
	m := make(map[uint32]string, len(syntaxKinds))
	for name, num := range syntaxKinds {
		key := uint32(num)
		if existing, ok := m[key]; !ok || len(name) < len(existing) {
			m[key] = name
		}
	}
	return m
}

// syntaxKinds maps SyntaxKind names to their numeric values in TypeScript 7.
// Generated from microsoft/typescript-go/internal/ast/kind.go (iota enum).
var syntaxKinds = map[string]int{
	"Unknown":                       0,
	"EndOfFileToken":                1,
	"SingleLineCommentTrivia":       2,
	"MultiLineCommentTrivia":        3,
	"NewLineTrivia":                 4,
	"WhitespaceTrivia":              5,
	"ShebangTrivia":                 6,
	"ConflictMarkerTrivia":          7,
	"NumericLiteral":                8,
	"BigIntLiteral":                 9,
	"StringLiteral":                 10,
	"JsxText":                       11,
	"JsxTextAllWhiteSpaces":         12,
	"RegularExpressionLiteral":      13,
	"NoSubstitutionTemplateLiteral": 14,
	"TemplateHead":                  15,
	"TemplateMiddle":                16,
	"TemplateTail":                  17,
	"OpenBraceToken":                18,
	"CloseBraceToken":               19,
	"OpenParenToken":                20,
	"CloseParenToken":               21,
	"OpenBracketToken":              22,
	"CloseBracketToken":             23,
	"DotToken":                      24,
	"DotDotDotToken":                25,
	"SemicolonToken":                26,
	"CommaToken":                    27,
	"QuestionDotToken":              28,
	"LessThanToken":                 29,
	"LessThanSlashToken":            30,
	"GreaterThanToken":              31,
	"LessThanEqualsToken":           32,
	"GreaterThanEqualsToken":        33,
	"EqualsEqualsToken":             34,
	"ExclamationEqualsToken":        35,
	"EqualsEqualsEqualsToken":       36,
	"ExclamationEqualsEqualsToken":  37,
	"EqualsGreaterThanToken":        38,
	"PlusToken":                     39,
	"MinusToken":                    40,
	"AsteriskToken":                 41,
	"AsteriskAsteriskToken":         42,
	"SlashToken":                    43,
	"PercentToken":                  44,
	"PlusPlusToken":                 45,
	"MinusMinusToken":               46,
	"LessThanLessThanToken":         47,
	"GreaterThanGreaterThanToken":   48,
	"GreaterThanGreaterThanGreaterThanToken": 49,
	"AmpersandToken":               50,
	"BarToken":                      51,
	"CaretToken":                    52,
	"ExclamationToken":              53,
	"TildeToken":                    54,
	"AmpersandAmpersandToken":       55,
	"BarBarToken":                    56,
	"QuestionToken":                 57,
	"ColonToken":                    58,
	"AtToken":                       59,
	"QuestionQuestionToken":          60,
	"HashToken":                      62,
	"EqualsToken":                   63,
	"PlusEqualsToken":                64,
	"MinusEqualsToken":               65,
	"AsteriskEqualsToken":            66,
	"AsteriskAsteriskEqualsToken":    67,
	"SlashEqualsToken":               68,
	"PercentEqualsToken":             69,
	"LessThanLessThanEqualsToken":    70,
	"GreaterThanGreaterThanEqualsToken":      71,
	"GreaterThanGreaterThanGreaterThanEqualsToken": 72,
	"AmpersandEqualsToken":           73,
	"BarEqualsToken":                 74,
	"BarBarEqualsToken":              75,
	"AmpersandAmpersandEqualsToken":  76,
	"QuestionQuestionEqualsToken":    77,
	"CaretEqualsToken":               78,
	"Identifier":                    79,
	"PrivateIdentifier":             80,
	"BreakKeyword":                  82,
	"CaseKeyword":                   83,
	"CatchKeyword":                  84,
	"ClassKeyword":                  85,
	"ConstKeyword":                  86,
	"ContinueKeyword":               87,
	"DebuggerKeyword":               88,
	"DefaultKeyword":                89,
	"DeleteKeyword":                 90,
	"DoKeyword":                     91,
	"ElseKeyword":                   92,
	"EnumKeyword":                   93,
	"ExportKeyword":                 94,
	"ExtendsKeyword":                95,
	"FalseKeyword":                  96,
	"FinallyKeyword":                97,
	"ForKeyword":                    98,
	"FunctionKeyword":               99,
	"IfKeyword":                     100,
	"ImportKeyword":                 101,
	"InKeyword":                     102,
	"InstanceOfKeyword":             103,
	"NewKeyword":                    104,
	"NullKeyword":                   105,
	"ReturnKeyword":                 106,
	"SuperKeyword":                  107,
	"SwitchKeyword":                 108,
	"ThisKeyword":                   109,
	"ThrowKeyword":                  110,
	"TrueKeyword":                   111,
	"TryKeyword":                    112,
	"TypeOfKeyword":                 113,
	"VarKeyword":                    114,
	"VoidKeyword":                   115,
	"WhileKeyword":                  116,
	"WithKeyword":                   117,
	"ImplementsKeyword":             118,
	"InterfaceKeyword":              119,
	"LetKeyword":                    120,
	"PackageKeyword":                121,
	"PrivateKeyword":                122,
	"ProtectedKeyword":              123,
	"PublicKeyword":                 124,
	"StaticKeyword":                 125,
	"YieldKeyword":                  126,
	"AbstractKeyword":               127,
	"AccessorKeyword":               128,
	"AsKeyword":                     129,
	"AssertsKeyword":                130,
	"AssertKeyword":                 131,
	"AnyKeyword":                    132,
	"AsyncKeyword":                  133,
	"AwaitKeyword":                  134,
	"BooleanKeyword":                135,
	"ConstructorKeyword":            136,
	"DeclareKeyword":                137,
	"GetKeyword":                    138,
	"InferKeyword":                  140,
	"IntrinsicKeyword":              141,
	"IsKeyword":                     142,
	"KeyOfKeyword":                  143,
	"ModuleKeyword":                 144,
	"NamespaceKeyword":              145,
	"NeverKeyword":                  146,
	"ReadonlyKeyword":               148,
	"RequireKeyword":                149,
	"NumberKeyword":                 150,
	"ObjectKeyword":                 151,
	"SetKeyword":                    153,
	"StringKeyword":                 154,
	"SymbolKeyword":                 155,
	"TypeKeyword":                   156,
	"UndefinedKeyword":              157,
	"UniqueKeyword":                 158,
	"UnknownKeyword":                159,
	"FromKeyword":                   161,
	"BigIntKeyword":                 163,
	"OverrideKeyword":               164,
	"OfKeyword":                     165,
	"DeferKeyword":                  166,
	"QualifiedName":                 167,
	"ComputedPropertyName":          168,
	"TypeParameter":                 169,
	"Parameter":                     170,
	"Decorator":                     171,
	"PropertySignature":             172,
	"PropertyDeclaration":           173,
	"MethodSignature":               174,
	"MethodDeclaration":             175,
	"ClassStaticBlockDeclaration":   176,
	"Constructor":                   177,
	"GetAccessor":                   178,
	"SetAccessor":                   179,
	"CallSignature":                 180,
	"ConstructSignature":            181,
	"IndexSignature":                182,
	"TypePredicate":                 183,
	"TypeReference":                 184,
	"FunctionType":                  185,
	"ConstructorType":               186,
	"TypeQuery":                     187,
	"TypeLiteral":                   188,
	"ArrayType":                     189,
	"TupleType":                     190,
	"OptionalType":                  191,
	"RestType":                      192,
	"UnionType":                     193,
	"IntersectionType":              194,
	"ConditionalType":               195,
	"InferType":                     196,
	"ParenthesizedType":             197,
	"ThisType":                      198,
	"TypeOperator":                  199,
	"IndexedAccessType":             200,
	"MappedType":                    201,
	"LiteralType":                   202,
	"NamedTupleMember":              203,
	"TemplateLiteralType":           204,
	"TemplateLiteralTypeSpan":       205,
	"ImportType":                    206,
	"ObjectBindingPattern":          207,
	"ArrayBindingPattern":           208,
	"BindingElement":                209,
	"ArrayLiteralExpression":        210,
	"ObjectLiteralExpression":       211,
	"PropertyAccessExpression":      212,
	"ElementAccessExpression":       213,
	"CallExpression":                214,
	"NewExpression":                 215,
	"TaggedTemplateExpression":      216,
	"TypeAssertionExpression":       217,
	"ParenthesizedExpression":       218,
	"FunctionExpression":            219,
	"ArrowFunction":                 220,
	"DeleteExpression":              221,
	"TypeOfExpression":              222,
	"VoidExpression":                223,
	"AwaitExpression":               224,
	"PrefixUnaryExpression":         225,
	"PostfixUnaryExpression":        226,
	"BinaryExpression":              227,
	"ConditionalExpression":         228,
	"TemplateExpression":            229,
	"YieldExpression":               230,
	"SpreadElement":                 231,
	"ClassExpression":               232,
	"OmittedExpression":             233,
	"ExpressionWithTypeArguments":   234,
	"AsExpression":                  235,
	"NonNullExpression":             236,
	"MetaProperty":                  237,
	"SatisfiesExpression":           239,
	"TemplateSpan":                  240,
	"SemicolonClassElement":         241,
	"Block":                         242,
	"EmptyStatement":                243,
	"VariableStatement":             244,
	"ExpressionStatement":           245,
	"IfStatement":                   246,
	"DoStatement":                   247,
	"WhileStatement":                248,
	"ForStatement":                  249,
	"ForInStatement":                250,
	"ForOfStatement":                251,
	"ContinueStatement":             252,
	"BreakStatement":                253,
	"ReturnStatement":               254,
	"WithStatement":                 255,
	"SwitchStatement":               256,
	"LabeledStatement":              257,
	"ThrowStatement":                258,
	"TryStatement":                  259,
	"DebuggerStatement":             260,
	"VariableDeclaration":           261,
	"VariableDeclarationList":       262,
	"FunctionDeclaration":           263,
	"ClassDeclaration":              264,
	"InterfaceDeclaration":          265,
	"TypeAliasDeclaration":          266,
	"EnumDeclaration":               267,
	"ModuleDeclaration":             268,
	"ModuleBlock":                   269,
	"CaseBlock":                     270,
	"NamespaceExportDeclaration":    271,
	"ImportEqualsDeclaration":       272,
	"ImportDeclaration":             273,
	"ImportClause":                  274,
	"NamespaceImport":               275,
	"NamedImports":                  276,
	"ImportSpecifier":               277,
	"ExportAssignment":              278,
	"ExportDeclaration":             279,
	"NamedExports":                  280,
	"NamespaceExport":               281,
	"ExportSpecifier":               282,
	"MissingDeclaration":            283,
	"ExternalModuleReference":       284,
	"JsxElement":                    285,
	"JsxSelfClosingElement":         286,
	"JsxOpeningElement":             287,
	"JsxClosingElement":             288,
	"JsxFragment":                   289,
	"JsxOpeningFragment":            290,
	"JsxClosingFragment":            291,
	"JsxAttribute":                  292,
	"JsxAttributes":                 293,
	"JsxSpreadAttribute":            294,
	"JsxExpression":                 295,
	"JsxNamespacedName":             296,
	"CaseClause":                    297,
	"DefaultClause":                 298,
	"HeritageClause":                299,
	"CatchClause":                   300,
	"ImportAttributes":              301,
	"ImportAttribute":               302,
	"PropertyAssignment":            303,
	"ShorthandPropertyAssignment":   304,
	"SpreadAssignment":              305,
	"EnumMember":                    306,
	"SourceFile":                    307,
	"JSDocTypeExpression":           308,
	"JSDocNameReference":            309,
	"JSDocNullableType":             312,
	"JSDocNonNullableType":          313,
	"JSDocOptionalType":             314,
	"JSDocVariadicType":             315,
	"JSDoc":                         316,
	"JSDocText":                     317,
	"JSDocTypeLiteral":              318,
	"JSDocSignature":                319,
	"JSDocLink":                     320,
	"JSDocLinkCode":                 321,
	"JSDocLinkPlain":                322,
	"JSDocTag":                      323,
	"JSDocAugmentsTag":              324,
	"JSDocImplementsTag":            325,
	"JSDocDeprecatedTag":            326,
	"JSDocPublicTag":                327,
	"JSDocPrivateTag":               328,
	"JSDocProtectedTag":             329,
	"JSDocReadonlyTag":              330,
	"JSDocOverrideTag":              331,
	"JSDocCallbackTag":              332,
	"JSDocOverloadTag":              333,
	"JSDocParameterTag":             334,
	"JSDocReturnTag":                335,
	"JSDocThisTag":                  336,
	"JSDocTypeTag":                  337,
	"JSDocTemplateTag":              338,
	"JSDocTypedefTag":               339,
	"JSDocSeeTag":                   340,
	"JSDocPropertyTag":              341,
	"JSDocThrowsTag":                342,
	"JSDocSatisfiesTag":             343,
	"JSDocImportTag":                344,
}

// nodeFlags maps NodeFlags names to their numeric values sent to the Java extractor.
// The Java extractor only checks Using, NestedNamespace, and GlobalAugmentation.
//
// TS7 binary AST flag layout (differs from TS5):
//   bit 0: Let, bit 1: Const, bit 2: Using, bit 3: NestedNamespace (not set in binary),
//   bit 4: Namespace, bit 5: OptionalChain, bit 6: ExportContext (was GlobalAugmentation
//   in TS5 at bit 11), bit 7: ContainsThis, ...
//
// GlobalAugmentation is NOT a flag in the TS7 binary format. We use a synthetic bit (30)
// that the converter sets on `declare global {}` nodes so the Java extractor can detect them.
var nodeFlags = map[string]int{
	"None":               0,
	"Let":                1,
	"Const":              2,
	"Using":              4,    // Let | Const
	"AwaitUsing":         6,    // Using | Const
	"NestedNamespace":    8,    // bit 3 — synthetic, set by converter
	"Namespace":          16,   // bit 4
	"OptionalChain":      32,   // bit 5
	"ExportContext":       64,   // bit 6
	"GlobalAugmentation": 1 << 30, // synthetic — set by converter for `declare global {}`
	"ContainsThis":       128,  // bit 7
	"HasImplicitReturn":  256,  // bit 8
	"HasExplicitReturn":  512,  // bit 9
	"HasAsyncFunctions":  1024, // bit 10
	"DisallowInContext":  2048, // bit 11
	"YieldContext":       4096, // bit 12
	"DecoratorContext":   8192, // bit 13
	"AwaitContext":       16384, // bit 14
	"DisallowConditionalTypesContext": 32768, // bit 15
	"ThisNodeHasError":   65536, // bit 16
	"JavaScriptFile":     131072, // bit 17
	"ThisNodeOrAnySubNodesHasError": 262144, // bit 18
	"HasAggregatedChildData":        524288, // bit 19
	"JSDoc":              8388608, // bit 23
	"JsonFile":           67108864, // bit 26
}
