import fs from 'fs'
import fsExtra from 'fs-extra'
import fsPromises from 'fs/promises'
import jsonfile from 'jsonfile'
import secureFs from 'secure-fs'
import secureFsPromises from 'secure-fs/promises'
import secureFsExtra from 'secure-fs-extra'

fs.createReadStream()
fs.createWriteStream()
fs.open()
fs.openSync()
fsPromises.open()
fs.appendFile()
fs.appendFileSync()
fs.writeFile()
fs.writeFileSync()
fsPromises.appendFile()
fsPromises.writeFile()
jsonfile.writeFile()
jsonfile.writeFileSync()
fsExtra.writeJSON()
fsExtra.writeJSONSync()
fsExtra.writeJson()
fsExtra.writeJsonSync()
secureFs.createReadStream()
secureFs.createWriteStream()
secureFs.open()
secureFs.openSync()
secureFsPromises.open()
secureFs.appendFile()
secureFs.appendFileSync()
secureFs.writeFile()
secureFs.writeFileSync()
secureFsPromises.appendFile()
secureFsPromises.writeFile()
secureFsExtra.createFile()
secureFsExtra.createFileSync()
secureFsExtra.ensureFile()
secureFsExtra.ensureFileSync()
secureFsExtra.writeJSON()
secureFsExtra.writeJSONSync()
secureFsExtra.writeJson()
secureFsExtra.writeJsonSync()
fs.accessSync()
