/** Provides definitions related to the `Microsoft.Extensions.Primitives` namespace. */

private import semmle.code.csharp.dataflow.ExternalFlow

/** Data flow for `Microsoft.Extensions.Primitives.StringValues`. */
private class MicrosoftExtensionsPrimitivesStringValuesFlowModelCsv extends SummaryModelCsv {
  override predicate row(string row) {
    row =
      [
        "Microsoft.Extensions.Primitives;StringValues;false;Add;(System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Add;(System.String);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Concat;(Microsoft.Extensions.Primitives.StringValues,Microsoft.Extensions.Primitives.StringValues);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Concat;(Microsoft.Extensions.Primitives.StringValues,Microsoft.Extensions.Primitives.StringValues);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Concat;(Microsoft.Extensions.Primitives.StringValues,System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Concat;(Microsoft.Extensions.Primitives.StringValues,System.String);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Concat;(System.String,Microsoft.Extensions.Primitives.StringValues);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Concat;(System.String,Microsoft.Extensions.Primitives.StringValues);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Contains;(System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Contains;(System.String);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;CopyTo;(System.String[],System.Int32);;Argument[0].Element;ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;CopyTo;(System.String[],System.Int32);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;CopyTo;(System.String[],System.Int32);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues,Microsoft.Extensions.Primitives.StringValues);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues,Microsoft.Extensions.Primitives.StringValues);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues,System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues,System.String);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues,System.String[]);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(Microsoft.Extensions.Primitives.StringValues,System.String[]);;Argument[1].Element;ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.Object);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.Object);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String,Microsoft.Extensions.Primitives.StringValues);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String,Microsoft.Extensions.Primitives.StringValues);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String[]);;Argument[0].Element;ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String[]);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String[],Microsoft.Extensions.Primitives.StringValues);;Argument[0].Element;ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Equals;(System.String[],Microsoft.Extensions.Primitives.StringValues);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;GetEnumerator;();;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;GetHashCode;();;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;IndexOf;(System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;IndexOf;(System.String);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Insert;(System.Int32,System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Insert;(System.Int32,System.String);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Insert;(System.Int32,System.String);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;IsNullOrEmpty;(Microsoft.Extensions.Primitives.StringValues);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Remove;(System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;Remove;(System.String);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;RemoveAt;(System.Int32);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;RemoveAt;(System.Int32);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;StringValues;(System.String);;Argument[0];Argument[this];taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;StringValues;(System.String[]);;Argument[0].Element;Argument[this];taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;ToArray;();;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;ToString;();;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;get_Count;();;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;get_IsReadOnly;();;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;get_Item;(System.Int32);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;get_Item;(System.Int32);;Argument[this];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;set_Item;(System.Int32,System.String);;Argument[0];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;set_Item;(System.Int32,System.String);;Argument[1];ReturnValue;taint;manual",
        "Microsoft.Extensions.Primitives;StringValues;false;set_Item;(System.Int32,System.String);;Argument[this];ReturnValue;taint;manual",
      ]
  }
}
