import python
import TestUtilities.dataflow.DataflowQueryTest
import semmle.python.security.dataflow.UnsafeShellCommandConstructionQuery
import FromTaintTrackingConfig<UnsafeShellCommandConstructionConfig>
