// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AvailabilitySpec`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.swift.generated.AvailabilitySpec

/**
 * INTERNAL: This module contains the customizable definition of `AvailabilitySpec` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * An availability spec, that is, part of an `AvailabilityInfo` condition. For example `iOS 12` and `*` in:
   * ```
   * if #available(iOS 12, *)
   * ```
   */
  class AvailabilitySpec extends Generated::AvailabilitySpec { }
}
