// Code generated by https://github.com/gagliardetto. DO NOT EDIT.

package main

import (
	"clevergo.tech/clevergo"
	"io"
	"net/http"
)

func main()              {}
func sink(v interface{}) {}

func link(from interface{}, into interface{}) {}

func source() interface{} {
	return nil
}

// Package clevergo.tech/clevergo@v0.5.2
func ClevergoTechClevergov052() {
	// Taint-tracking through functions.
	{
		// func CleanPath(p string) string
		{
			fromString599 := source().(string)
			intoString409 := clevergo.CleanPath(fromString599)
			sink(intoString409) // $SinkingSource
		}
	}
	// Taint-tracking through interface method calls.
	{
		// Taint-tracking through method calls on clevergo.tech/clevergo.Decoder interface.
		{
			// func (Decoder).Decode(req *net/http.Request, v interface{}) error
			{
				fromRequest246 := source().(*http.Request)
				var intoInterface898 interface{}
				var mediumObjCQL clevergo.Decoder
				mediumObjCQL.Decode(fromRequest246, intoInterface898)
				sink(intoInterface898) // $SinkingSource
			}
		}
		// Taint-tracking through method calls on clevergo.tech/clevergo.Renderer interface.
		{
			// func (Renderer).Render(w io.Writer, name string, data interface{}, c *Context) error
			{
				fromInterface598 := source().(interface{})
				var intoWriter631 io.Writer
				var mediumObjCQL clevergo.Renderer
				mediumObjCQL.Render(intoWriter631, "", fromInterface598, nil)
				sink(intoWriter631) // $SinkingSource
			}
		}
	}
}

//go:generate depstubber -vendor clevergo.tech/clevergo Context,Decoder,Renderer CleanPath
//go:generate depstubber -write_module_txt
