import fsExtra from 'fs-extra'
import cpy from 'cpy'
import npmMoveFile from '@npmcli/move-file'

fsExtra.createFile()
fsExtra.createFileSync()
fsExtra.createLink()
fsExtra.createLinkSync()
fsExtra.createSymlink()
fsExtra.createSymlinkSync()
fsExtra.emptyDir()
fsExtra.emptyDirSync()
fsExtra.emptydir()
fsExtra.emptydirSync()
fsExtra.ensureFile()
fsExtra.ensureFileSync()
fsExtra.ensureLink()
fsExtra.ensureLinkSync()
fsExtra.ensureSymlink()
fsExtra.ensureSymlinkSync()
fsExtra.outputFile()
fsExtra.outputFileSync()
fsExtra.outputJSON()
fsExtra.outputJSONSync()
fsExtra.outputJson()
fsExtra.outputJsonSync()
cpy()
npmMoveFile()
npmMoveFile.sync()
fsExtra.accessSync()
