// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AnyAttr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.AnyAttr

/**
 * INTERNAL: This module contains the customizable definition of `AnyAttr` and should not
 * be referenced directly.
 */
module Impl {
  class AnyAttr extends Generated::AnyAttr { }
}
