// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ArgList`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ArgList

/**
 * INTERNAL: This module contains the customizable definition of `ArgList` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ArgList. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ArgList extends Generated::ArgList { }
}
