// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AsmDirSpec`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.AsmDirSpec

/**
 * INTERNAL: This module contains the customizable definition of `AsmDirSpec` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * An inline assembly direction specifier.
   *
   * For example:
   * ```rust
   * use core::arch::asm;
   * asm!("mov {input:x}, {input:x}", output = out(reg) x, input = in(reg) y);
   * //                                        ^^^                 ^^
   * ```
   */
  class AsmDirSpec extends Generated::AsmDirSpec { }
}
