// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AssocItemList`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.AssocItemList

/**
 * INTERNAL: This module contains the customizable definition of `AssocItemList` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A list of  `AssocItem` elements, as appearing for example in a `Trait`.
   */
  class AssocItemList extends Generated::AssocItemList { }
}
