// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `AssocTypeArg`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.AssocTypeArg

/**
 * INTERNAL: This module contains the customizable definition of `AssocTypeArg` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * An associated type argument in a path.
   *
   * For example:
   * ```rust
   * <T as Iterator>::Item
   * //               ^^^^
   * ```
   */
  class AssocTypeArg extends Generated::AssocTypeArg { }
}
