// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `BinaryExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.BinaryExpr

/**
 * INTERNAL: This module contains the customizable definition of `BinaryExpr` and should not
 * be referenced directly.
 */
module Impl {
  class BinaryExpr extends Generated::BinaryExpr { }
}
