// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ClosureBinder`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ClosureBinder

/**
 * INTERNAL: This module contains the customizable definition of `ClosureBinder` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ClosureBinder. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ClosureBinder extends Generated::ClosureBinder { }
}
