// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Comment`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.Comment

/**
 * INTERNAL: This module contains the customizable definition of `Comment` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A comment. For example:
   * ```rust
   * // this is a comment
   * /// This is a doc comment
   * ```
   */
  class Comment extends Generated::Comment { }
}
