// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ConstExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ConstExpr

/**
 * INTERNAL: This module contains the customizable definition of `ConstExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A `const` block expression. For example:
   * ```rust
   * if const { SRC::IS_ZST || DEST::IS_ZST || mem::align_of::<SRC>() != mem::align_of::<DEST>() } {
   *     return false;
   * }
   * ```
   */
  class ConstExpr extends Generated::ConstExpr { }
}
