// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Declaration`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.internal.generated.Declaration

/**
 * INTERNAL: This module contains the customizable definition of `Declaration` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * The base class for declarations.
   */
  class Declaration extends Generated::Declaration { }
}
