// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ExpandableItem`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ExpandableItem

/**
 * INTERNAL: This module contains the customizable definition of `ExpandableItem` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * Something that can be expanded by an attribute macro
   */
  class ExpandableItem extends Generated::ExpandableItem { }
}
