// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ExternItemList`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ExternItemList

/**
 * INTERNAL: This module contains the customizable definition of `ExternItemList` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ExternItemList. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ExternItemList extends Generated::ExternItemList { }
}
