// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `FnPtrType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.FnPtrType

/**
 * INTERNAL: This module contains the customizable definition of `FnPtrType` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A FnPtrType. For example:
   * ```rust
   * todo!()
   * ```
   */
  class FnPtrType extends Generated::FnPtrType { }
}
