// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ForType`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ForType

/**
 * INTERNAL: This module contains the customizable definition of `ForType` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ForType. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ForType extends Generated::ForType { }
}
