// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ForTypeRepr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ForTypeRepr

/**
 * INTERNAL: This module contains the customizable definition of `ForTypeRepr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ForTypeRepr. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ForTypeRepr extends Generated::ForTypeRepr { }
}
