// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `FunctionOrMethodCallExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.FunctionOrMethodCallExpr

/**
 * INTERNAL: This module contains the customizable definition of `FunctionOrMethodCallExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A function or method call expression. See `CallExpr` and `MethodCallExpr` for further details.
   */
  class FunctionOrMethodCallExpr extends Generated::FunctionOrMethodCallExpr { }
}
