// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ImplTraitTypeRef`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ImplTraitTypeRef

/**
 * INTERNAL: This module contains the customizable definition of `ImplTraitTypeRef` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ImplTraitTypeRef. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ImplTraitTypeRef extends Generated::ImplTraitTypeRef { }
}
