// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `LifetimeArg`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.LifetimeArg

/**
 * INTERNAL: This module contains the customizable definition of `LifetimeArg` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A LifetimeArg. For example:
   * ```rust
   * todo!()
   * ```
   */
  class LifetimeArg extends Generated::LifetimeArg { }
}
