// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `MacroDef`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.MacroDef

/**
 * INTERNAL: This module contains the customizable definition of `MacroDef` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A MacroDef. For example:
   * ```rust
   * todo!()
   * ```
   */
  class MacroDef extends Generated::MacroDef { }
}
