// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `MacroBlockExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.MacroBlockExpr

/**
 * INTERNAL: This module contains the customizable definition of `MacroBlockExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A sequence of statements generated by a `MacroCall`. For example:
   * ```rust
   * macro_rules! my_macro {
   *     () => {
   *         let mut x = 40;
   *         x += 2;
   *         x
   *     };
   * }
   *
   * my_macro!();  // this macro expands to a sequence of statements (and an expression)
   * ```
   */
  class MacroBlockExpr extends Generated::MacroBlockExpr { }
}
