// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Missing`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.Missing

/**
 * INTERNAL: This module contains the customizable definition of `Missing` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * The base class marking errors during parsing or resolution.
   */
  class Missing extends Generated::Missing { }
}
