// generated by codegen, do not edit
/**
 * This module provides the class `NamedCrate`.
 */

private import NamedCrateImpl
import codeql.rust.elements.Crate
import codeql.rust.elements.Element

/**
 * INTERNAL: Do not use.
 */
final class NamedCrate = Impl::NamedCrate;
