// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Path`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.Path

/**
 * INTERNAL: This module contains the customizable definition of `Path` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A path. For example:
   * ```rust
   * foo::bar;
   * ```
   */
  class Path extends Generated::Path { }
}
