// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `RecordPatFieldList`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.RecordPatFieldList

/**
 * INTERNAL: This module contains the customizable definition of `RecordPatFieldList` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A RecordPatFieldList. For example:
   * ```rust
   * todo!()
   * ```
   */
  class RecordPatFieldList extends Generated::RecordPatFieldList { }
}
