// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `RetTypeRepr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.RetTypeRepr

/**
 * INTERNAL: This module contains the customizable definition of `RetTypeRepr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A RetTypeRepr. For example:
   * ```rust
   * todo!()
   * ```
   */
  class RetTypeRepr extends Generated::RetTypeRepr { }
}
