// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `ReturnTypeSyntax`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.ReturnTypeSyntax

/**
 * INTERNAL: This module contains the customizable definition of `ReturnTypeSyntax` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A ReturnTypeSyntax. For example:
   * ```rust
   * todo!()
   * ```
   */
  class ReturnTypeSyntax extends Generated::ReturnTypeSyntax { }
}
