// generated by codegen, remove this comment if you wish to edit this file
/**
 *  This module defines the hook used internally to tweak the characteristic predicate of
 *  `SourceFile` synthesized instances.
 *  INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.Raw

/**
 *  The characteristic predicate of `SourceFile` synthesized instances.
 *  INTERNAL: Do not use.
 */
predicate constructSourceFile(Raw::SourceFile id) { any() }
