// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Static`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.Static

/**
 * INTERNAL: This module contains the customizable definition of `Static` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A Static. For example:
   * ```rust
   * todo!()
   * ```
   */
  class Static extends Generated::Static { }
}
