// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `StructFieldList`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.StructFieldList

/**
 * INTERNAL: This module contains the customizable definition of `StructFieldList` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A field list of a struct expression. For example:
   * ```rust
   * todo!()
   * ```
   */
  class StructFieldList extends Generated::StructFieldList { }
}
