// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `TraitTypeBound`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.TraitTypeBound

/**
 * INTERNAL: This module contains the customizable definition of `TraitTypeBound` and should not
 * be referenced directly.
 */
module Impl {
  class TraitTypeBound extends Generated::TraitTypeBound { }
}
