// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `TuplePat`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.TuplePat

/**
 * INTERNAL: This module contains the customizable definition of `TuplePat` and should not
 * be referenced directly.
 */
module Impl {
  class TuplePat extends Generated::TuplePat { }
}
