// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `TypeRef`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.TypeRef

/**
 * INTERNAL: This module contains the customizable definition of `TypeRef` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * The base class for type references.
   * ```rust
   * let x: i32;
   * let y: Vec<i32>;
   * let z: Option<i32>;
   * ```
   */
  class TypeRef extends Generated::TypeRef { }
}
