// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `TypeBound`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.TypeBound

/**
 * INTERNAL: This module contains the customizable definition of `TypeBound` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A TypeBound. For example:
   * ```rust
   * todo!()
   * ```
   */
  class TypeBound extends Generated::TypeBound { }
}
