// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `UnderscoreExpr`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.UnderscoreExpr

/**
 * INTERNAL: This module contains the customizable definition of `UnderscoreExpr` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * An underscore expression. For example:
   * ```rust
   * _ = 42;
   * ```
   */
  class UnderscoreExpr extends Generated::UnderscoreExpr { }
}
