// generated by codegen, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `Use`.
 *
 * INTERNAL: Do not use.
 */

private import codeql.rust.elements.internal.generated.Use

/**
 * INTERNAL: This module contains the customizable definition of `Use` and should not
 * be referenced directly.
 */
module Impl {
  /**
   * A Use. For example:
   * ```rust
   * todo!()
   * ```
   */
  class Use extends Generated::Use { }
}
