// Package main implements a generator that turns a repository's Actions lockfile
// (`.github/workflows/actions.lock`) into a CodeQL data extension populating the
// `pinnedByLockfileDataModel` extensible predicate consumed by the
// `actions/unpinned-tag` query.
//
// The generator is deliberately transport-agnostic: it parses the lockfile and
// emits the same `[workflow_path, nwo, ref]` rows the query already matches on.
// Today those rows are shipped as a data-extension model pack (applied at
// analysis time via `--model-packs`, exactly like `codeql/immutable-actions-list`).
// The same parsing core can later feed an extractor-native TRAP relation without
// changing the query.
//
// The lockfile format is owned by `github.com/github/actions-lockfile`; this
// generator parses the minimal, stable core it needs directly (see lockfile.go)
// so it has no dependency on that (currently private) module and builds anywhere
// the Go toolchain is available.
package main

import (
	"fmt"
	"sort"
	"strings"
)

// row is a single `pinnedByLockfileDataModel` tuple: the reference
// `nwo`@`ref` in the workflow or composite action file at `workflowPath` is
// pinned by the repository's Actions lockfile.
type row struct {
	workflowPath string
	nwo          string
	ref          string
}

// rowsFromLockfile parses lockfile `contents` and returns the deduplicated,
// sorted set of `pinnedByLockfileDataModel` rows it implies.
//
// A lockfile records the *resolved* ref for each dependency (the CLI prefers a
// full semver tag such as `v4.3.1`), but a workflow author usually writes a
// shorter, mutable tag such as `v4` or `v4.3` in `uses:`. The query matches on
// the ref exactly as written, so for every full-semver resolved ref we also
// emit its major-only (`v4`) and major.minor (`v4.3`) forms. This lets a
// `uses: owner/action@v4` be recognized as pinned by a lockfile entry that
// resolved to `v4.3.1`, which is the common real-world case.
func rowsFromLockfile(contents []byte) ([]row, error) {
	doc, err := parseLockfile(contents)
	if err != nil {
		return nil, err
	}

	seen := make(map[row]struct{})
	for workflowPath, pinKeys := range doc.Workflows {
		for _, key := range pinKeys {
			nwo, keyRef, ok := parsePin(key)
			if !ok {
				continue
			}
			// Prefer the resolved ref recorded in the dependency metadata; fall
			// back to the ref embedded in the pin key.
			ref := keyRef
			if dep, ok := doc.Dependencies[key]; ok && dep.Ref != "" {
				ref = dep.Ref
			}
			for _, r := range refVariants(ref) {
				seen[row{workflowPath: workflowPath, nwo: nwo, ref: r}] = struct{}{}
			}
		}
	}

	rows := make([]row, 0, len(seen))
	for r := range seen {
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].workflowPath != rows[j].workflowPath {
			return rows[i].workflowPath < rows[j].workflowPath
		}
		if rows[i].nwo != rows[j].nwo {
			return rows[i].nwo < rows[j].nwo
		}
		return rows[i].ref < rows[j].ref
	})
	return rows, nil
}

// refVariants returns every ref string a workflow author might have written in
// `uses:` that the resolved `ref` covers. For a full semver tag (e.g. `v4.3.1`)
// this is the tag itself plus its major.minor (`v4.3`) and major-only (`v4`)
// forms; for anything else (a branch, a partial tag, a SHA) it is just the ref.
func refVariants(ref string) []string {
	sv, ok := parseSemVer(ref)
	if !ok || !sv.isFull() {
		return []string{ref}
	}
	variants := []string{ref}
	if minor := sv.minorTag(); minor != ref {
		variants = append(variants, minor)
	}
	if major := sv.majorTag(); major != ref {
		variants = append(variants, major)
	}
	return variants
}

// renderExtension serializes `rows` as a CodeQL data-extension YAML document that
// adds to the `pinnedByLockfileDataModel` extensible predicate in
// `codeql/actions-all`.
func renderExtension(rows []row) string {
	var b strings.Builder
	b.WriteString("# Generated by lockfile-extension-generator from .github/workflows/actions.lock.\n")
	b.WriteString("# Do not edit by hand; regenerate from the repository's Actions lockfile.\n")
	b.WriteString("extensions:\n")
	b.WriteString("  - addsTo:\n")
	b.WriteString("      pack: codeql/actions-all\n")
	b.WriteString("      extensible: pinnedByLockfileDataModel\n")
	// `data` must be a YAML sequence. When there are no rows we must emit an
	// explicit empty list (`data: []`); a bare `data:` parses as null, which
	// CodeQL's extension loader rejects (`resolve extensions-by-pack` fails and
	// aborts the whole analysis). Zero rows is reachable whenever a lockfile is
	// present but pins no repo-level actions (e.g. only sub-path actions such as
	// `github/codeql-action/init@v3`, which `parsePin` intentionally skips).
	if len(rows) == 0 {
		b.WriteString("    data: []\n")
		return b.String()
	}
	b.WriteString("    data:\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "      - [%q, %q, %q]\n", r.workflowPath, r.nwo, r.ref)
	}
	return b.String()
}
