// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `TypedPattern`.
 */

private import internal.TypedPatternImpl
import codeql.swift.elements.pattern.Pattern
import codeql.swift.elements.type.TypeRepr

final class TypedPattern = Impl::TypedPattern;
