// Generated automatically from com.fasterxml.jackson.databind.MapperFeature for testing purposes

package com.fasterxml.jackson.databind;


public enum MapperFeature
{
    ACCEPT_CASE_INSENSITIVE_PROPERTIES, ALLOW_EXPLICIT_PROPERTY_RENAMING, ALLOW_FINAL_FIELDS_AS_MUTATORS, AUTO_DETECT_CREATORS, AUTO_DETECT_FIELDS, AUTO_DETECT_GETTERS, AUTO_DETECT_IS_GETTERS, AUTO_DETECT_SETTERS, CAN_OVERRIDE_ACCESS_MODIFIERS, DEFAULT_VIEW_INCLUSION, IGNORE_DUPLICATE_MODULE_REGISTRATIONS, INFER_PROPERTY_MUTATORS, OVERRIDE_PUBLIC_ACCESS_MODIFIERS, PROPAGATE_TRANSIENT_MARKER, REQUIRE_SETTERS_FOR_GETTERS, SORT_PROPERTIES_ALPHABETICALLY, USE_ANNOTATIONS, USE_GETTERS_AS_SETTERS, USE_STATIC_TYPING, USE_STD_BEAN_NAMING, USE_WRAPPER_NAME_AS_PROPERTY_NAME;
    private MapperFeature() {}
    public boolean enabledByDefault(){ return false; }
    public boolean enabledIn(int p0){ return false; }
    public int getMask(){ return 0; }
}
