...
  buf = malloc(intSize);
...
  free(buf); 
  buf = NULL; // GOOD
...

...
  buf = malloc(intSize);
...
  free(buf); 
  if(buf) free(buf); // BAD: the cleanup function does not zero out the pointer
...
