// Generated automatically from org.apache.velocity.runtime.parser.node.ParserVisitor for testing purposes

package org.apache.velocity.runtime.parser.node;

import org.apache.velocity.runtime.parser.node.ASTAddNode;
import org.apache.velocity.runtime.parser.node.ASTAndNode;
import org.apache.velocity.runtime.parser.node.ASTAssignment;
import org.apache.velocity.runtime.parser.node.ASTBlock;
import org.apache.velocity.runtime.parser.node.ASTComment;
import org.apache.velocity.runtime.parser.node.ASTDirective;
import org.apache.velocity.runtime.parser.node.ASTDirectiveAssign;
import org.apache.velocity.runtime.parser.node.ASTDivNode;
import org.apache.velocity.runtime.parser.node.ASTEQNode;
import org.apache.velocity.runtime.parser.node.ASTElseIfStatement;
import org.apache.velocity.runtime.parser.node.ASTElseStatement;
import org.apache.velocity.runtime.parser.node.ASTEscape;
import org.apache.velocity.runtime.parser.node.ASTEscapedDirective;
import org.apache.velocity.runtime.parser.node.ASTExpression;
import org.apache.velocity.runtime.parser.node.ASTFalse;
import org.apache.velocity.runtime.parser.node.ASTFloatingPointLiteral;
import org.apache.velocity.runtime.parser.node.ASTGENode;
import org.apache.velocity.runtime.parser.node.ASTGTNode;
import org.apache.velocity.runtime.parser.node.ASTIdentifier;
import org.apache.velocity.runtime.parser.node.ASTIfStatement;
import org.apache.velocity.runtime.parser.node.ASTIndex;
import org.apache.velocity.runtime.parser.node.ASTIntegerLiteral;
import org.apache.velocity.runtime.parser.node.ASTIntegerRange;
import org.apache.velocity.runtime.parser.node.ASTLENode;
import org.apache.velocity.runtime.parser.node.ASTLTNode;
import org.apache.velocity.runtime.parser.node.ASTMap;
import org.apache.velocity.runtime.parser.node.ASTMethod;
import org.apache.velocity.runtime.parser.node.ASTModNode;
import org.apache.velocity.runtime.parser.node.ASTMulNode;
import org.apache.velocity.runtime.parser.node.ASTNENode;
import org.apache.velocity.runtime.parser.node.ASTNotNode;
import org.apache.velocity.runtime.parser.node.ASTObjectArray;
import org.apache.velocity.runtime.parser.node.ASTOrNode;
import org.apache.velocity.runtime.parser.node.ASTReference;
import org.apache.velocity.runtime.parser.node.ASTSetDirective;
import org.apache.velocity.runtime.parser.node.ASTStringLiteral;
import org.apache.velocity.runtime.parser.node.ASTSubtractNode;
import org.apache.velocity.runtime.parser.node.ASTText;
import org.apache.velocity.runtime.parser.node.ASTTextblock;
import org.apache.velocity.runtime.parser.node.ASTTrue;
import org.apache.velocity.runtime.parser.node.ASTWord;
import org.apache.velocity.runtime.parser.node.ASTprocess;
import org.apache.velocity.runtime.parser.node.SimpleNode;

public interface ParserVisitor
{
    Object visit(ASTAddNode p0, Object p1);
    Object visit(ASTAndNode p0, Object p1);
    Object visit(ASTAssignment p0, Object p1);
    Object visit(ASTBlock p0, Object p1);
    Object visit(ASTComment p0, Object p1);
    Object visit(ASTDirective p0, Object p1);
    Object visit(ASTDirectiveAssign p0, Object p1);
    Object visit(ASTDivNode p0, Object p1);
    Object visit(ASTEQNode p0, Object p1);
    Object visit(ASTElseIfStatement p0, Object p1);
    Object visit(ASTElseStatement p0, Object p1);
    Object visit(ASTEscape p0, Object p1);
    Object visit(ASTEscapedDirective p0, Object p1);
    Object visit(ASTExpression p0, Object p1);
    Object visit(ASTFalse p0, Object p1);
    Object visit(ASTFloatingPointLiteral p0, Object p1);
    Object visit(ASTGENode p0, Object p1);
    Object visit(ASTGTNode p0, Object p1);
    Object visit(ASTIdentifier p0, Object p1);
    Object visit(ASTIfStatement p0, Object p1);
    Object visit(ASTIndex p0, Object p1);
    Object visit(ASTIntegerLiteral p0, Object p1);
    Object visit(ASTIntegerRange p0, Object p1);
    Object visit(ASTLENode p0, Object p1);
    Object visit(ASTLTNode p0, Object p1);
    Object visit(ASTMap p0, Object p1);
    Object visit(ASTMethod p0, Object p1);
    Object visit(ASTModNode p0, Object p1);
    Object visit(ASTMulNode p0, Object p1);
    Object visit(ASTNENode p0, Object p1);
    Object visit(ASTNotNode p0, Object p1);
    Object visit(ASTObjectArray p0, Object p1);
    Object visit(ASTOrNode p0, Object p1);
    Object visit(ASTReference p0, Object p1);
    Object visit(ASTSetDirective p0, Object p1);
    Object visit(ASTStringLiteral p0, Object p1);
    Object visit(ASTSubtractNode p0, Object p1);
    Object visit(ASTText p0, Object p1);
    Object visit(ASTTextblock p0, Object p1);
    Object visit(ASTTrue p0, Object p1);
    Object visit(ASTWord p0, Object p1);
    Object visit(ASTprocess p0, Object p1);
    Object visit(SimpleNode p0, Object p1);
}
