import python
import experimental.dataflow.TestUtil.DataflowQueryTest
import semmle.python.security.dataflow.PathInjectionQuery
import MakeQueryTest<IgnoreAbsolutePaths<GetQueryTest::FromTaintTrackingStateConfig<PathInjectionConfig>>>
