/** Provides functionality for inferring types. */

/*
 * Known limitations:
 * - Implicit constructors in classes and structs are not generated by the extractor
 * - Pattern matching, including enum destructuring
 * - Inferred qualifiers `.foo`
 * - Type parameter bounds (`foo<T : Protocol>(x : T)`)
 * - Type parameter constraints (`foo<T>(x : T) where T: Protocol`); are currently not extracted
 * - Associated types on type parameters, e.g. `func foo<T : Protocol>(x : T) -> T.AssociatedType`
 * - `Self` inside protocol extensions
 * - Type parameters inherited in extensions (extractor change?)
 * - Primary associated types
 * - Key paths
 * - Overloading (both arity based and type based)
 * - Indexing expressions
 * - Operations
 * - Inherited constructors
 * - Closure short-hand parameters `$0`, `$1`, etc (extractor change?)
 */

private import codeql.util.Unit
private import codeql.typeinference.internal.TypeInference
private import codeql.unified.internal.ExprPositions
private import codeql.unified.internal.NameBinding
private import utils.test.InlineExpectationsTest
private import Type
private import Type as T
private import TypeAbstraction
private import TypeAbstraction as TA
private import TypeMention
private import TypeInferencePlugin
private import TypeInferencePlugin as Plugin

class Type = T::Type;

private module Input1 implements InputSig1<Location> {
  private import Type as T

  class Type = T::Type;

  class PseudoType = T::PseudoType;

  class TypeParameter = T::TypeParameter;

  class TypeAbstraction = TA::TypeAbstraction;

  int getTypeParameterId(TypeParameter tp) {
    CachedStage::ref() and
    tp =
      rank[result](TypeParameter tp0, int kind, int id1, int id2 |
        kind = 1 and
        id1 = idOfTypeParameterAstNode(tp0.(TypeParameterType).getTypeParameter()) and
        id2 = 0
        or
        kind = 2 and
        exists(ClassLikeDeclaration c, AssociatedTypeDeclaration a |
          tp0 = TAssociatedTypeParameterType(c, a, _) and
          id1 = idOfTypeParameterAstNode(c) and
          id2 = idOfTypeParameterAstNode(a)
        )
        or
        kind = 3 and
        tp0 = TUnknownTypeTypeParameter(id1) and
        id2 = 0
      |
        tp0 order by kind, id1, id2
      )
  }
}

private import Input1

private module M1 = Make1<Location, Input1>;

import M1

predicate getTypePathLimit = Input1::getTypePathLimit/0;

predicate getTypeParameterId = Input1::getTypeParameterId/1;

class TypePath = M1::TypePath;

module TypePath = M1::TypePath;

private module Input2 implements InputSig2<TypeMention> {
  TypeMention getATypeParameterConstraint(TypeParameter tp) {
    result = tp.(TypeParameterType).getTypeParameter().getBound()
  }

  predicate conditionSatisfiesConstraint(
    TypeAbstraction abs, TypeMention condition, TypeMention constraint, boolean transitive
  ) {
    transitive = true and
    abs =
      any(ClassLikeDeclaration c |
        condition = getClassLikeDeclarationTypeMention(c) and
        constraint = c.getABaseType().getType()
      )
  }

  predicate typeParameterIsFunctionallyDetermined(TypeParameter tp) {
    tp instanceof AssociatedTypeParameterType
  }

  predicate typeAbstractionHasAmbiguousConstraintAt(
    TypeAbstraction abs, Type constraint, TypePath path
  ) {
    none() // todo
  }
}

private import Input2

private module M2 = Make2<TypeMention, Input2>;

import M2

private module Input3 implements InputSig3 {
  private import unified as Unified

  predicate cacheRevRef() {
    (exists(resolveFieldAccess(_)) implies any())
    or
    (exists(resolveCallTarget(_)) implies any())
  }

  predicate inferTypeForDefaults = M3::inferType/2;

  class UnknownType = T::UnknownType;

  class BoolType = Plugin::BoolType;

  class AstNode = Unified::AstNode;

  class Expr extends Unified::Expr {
    Expr() { isInAssignmentContext(this, _) or hasResultValue(this) }
  }

  class Cast extends Expr, TypeCastExpr {
    TypeMention getType() { result = TypeCastExpr.super.getType() }
  }

  class Switch extends Expr, SwitchExpr {
    Expr getExpr() { result = super.getValue() }

    Case getCase(int index) { result = super.getCase(index) }
  }

  class Case extends SwitchCase {
    AstNode getAPattern() { result = super.getPattern() }

    AstNode getBody() { result = super.getBody() }
  }

  class ConditionalExpr extends Expr instanceof IfExpr {
    Expr getCondition() { result = super.getCondition() }

    Expr getThen() { result = super.getThen() }

    Expr getElse() { result = super.getElse() }
  }

  class BinaryExpr extends Expr, Unified::BinaryExpr {
    Expr getLeftOperand() { result = super.getLeft() }

    Expr getRightOperand() { result = super.getRight() }
  }

  class LogicalAndExpr extends BinaryExpr, Unified::LogicalAndExpr { }

  class LogicalOrExpr extends BinaryExpr, Unified::LogicalOrExpr { }

  class Assignment extends BinaryExpr, Unified::Assignment { }

  class AssignExpr extends Assignment, Unified::AssignExpr { }

  class ParenExpr extends Expr {
    ParenExpr() { none() }

    Expr getExpr() { none() }
  }

  /**
   * Provides declarations with explicit AST node representations.
   *
   * Most declarations are explicitly declared, but for example implicit
   * receiver parameters are not.
   */
  private module AstDeclaration {
    abstract class Declaration extends AstNode {
      abstract TypeMention getDeclaringType();

      abstract TypeMention getType();

      abstract Identifier getNameNode();

      pragma[nomagic]
      predicate isMemberOf(ClassLikeDeclaration cls, Identifier i, string name) {
        exists(NamespaceNode ns |
          ns.isInstanceMemberNamespace(cls) and
          ns.getMember(name).isIdentifier(i) and
          i = this.getNameNode()
        )
      }
    }

    abstract class VariableDeclaration extends Declaration {
      abstract AstNode getPattern();

      abstract AstNode getInitializer();

      predicate isCoercionSite() { none() }

      override TypeMention getDeclaringType() { none() }

      override Identifier getNameNode() { result = this.getPattern() }
    }

    private class OrdinaryVariableDeclaration extends VariableDeclaration instanceof Unified::VariableDeclaration
    {
      override AstNode getPattern() { result = Unified::VariableDeclaration.super.getPattern() }

      override AstNode getInitializer() { result = super.getValue() }

      override TypeMention getType() { result = Unified::VariableDeclaration.super.getType() }
    }

    class Field extends OrdinaryVariableDeclaration {
      ClassLikeDeclaration cls;

      Field() { this = cls.getAMember() }

      override TypeMention getDeclaringType() { result = getClassLikeDeclarationTypeMention(cls) }
    }

    private class EnumField_ extends Field instanceof EnumField {
      override TypeMention getType() { result = super.getEnum().getNameNode() }
    }

    class Parameter extends VariableDeclaration instanceof Unified::Parameter {
      override AstNode getInitializer() { none() }

      override AstNode getPattern() { result = Unified::Parameter.super.getPattern() }

      override TypeMention getType() { result = Unified::Parameter.super.getType() }
    }

    abstract class Callable extends Declaration instanceof Unified::Callable {
      abstract TypeMention getAdditionalTypeParameterConstraint(TypeParameter tp);

      override TypeMention getDeclaringType() {
        exists(ClassLikeDeclaration c |
          result = getClassLikeDeclarationTypeMention(c) and
          this = c.getAMember()
        )
      }

      abstract TypeParameter getTypeParameter(int i);

      abstract Parameter getParameter(int i);

      abstract AstNode getBody();
    }

    private class FunctionDeclarationCallable extends Callable instanceof FunctionDeclaration {
      override TypeMention getAdditionalTypeParameterConstraint(TypeParameter tp) {
        // todo: type equalities?
        exists(BoundTypeConstraint constraint |
          constraint = super.getATypeConstraint() and
          tp = constraint.getType().(TypeMention).getType() and
          result = constraint.getBound()
        )
      }

      override TypeParameterType getTypeParameter(int i) {
        result.getTypeParameter() = FunctionDeclaration.super.getTypeParameter(i)
      }

      override Parameter getParameter(int i) { result = FunctionDeclaration.super.getParameter(i) }

      override TypeMention getType() { result = super.getReturnType() }

      override AstNode getBody() { result = FunctionDeclaration.super.getBody() }

      override Identifier getNameNode() { result = FunctionDeclaration.super.getNameNode() }
    }

    class ConstructorDeclarationCallable extends Callable instanceof ConstructorDeclaration {
      override TypeMention getAdditionalTypeParameterConstraint(TypeParameter tp) { none() }

      override TypeParameterType getTypeParameter(int i) { none() }

      override Parameter getParameter(int i) {
        result = ConstructorDeclaration.super.getParameter(i)
      }

      override TypeMention getType() { result = this.getDeclaringType() }

      override AstNode getBody() { result = ConstructorDeclaration.super.getBody() }

      override Identifier getNameNode() { result = ConstructorDeclaration.super.getNameNode() }

      override predicate isMemberOf(ClassLikeDeclaration cls, Identifier i, string name) {
        // todo: constructors can be inherited
        this = cls.getAMember() and
        i = this.getNameNode() and
        name = i.getValue()
      }
    }

    private class EnumConstructorCallable extends ConstructorDeclarationCallable instanceof EnumConstructor
    {
      override TypeMention getDeclaringType() { result = super.getEnum().getNameNode() }

      override Identifier getNameNode() { result = EnumConstructor.super.getNameNode() }
    }

    class Closure extends Expr, Callable instanceof Unified::FunctionExpr {
      override TypeMention getAdditionalTypeParameterConstraint(TypeParameter tp) { none() }

      override TypeParameterType getTypeParameter(int i) { none() }

      override Parameter getParameter(int i) { result = FunctionExpr.super.getParameter(i) }

      override TypeMention getType() { result = super.getReturnType() }

      override AstNode getBody() { result = FunctionExpr.super.getBody() }

      override Identifier getNameNode() { none() }
    }
  }

  private newtype TDeclaration =
    TExplicitDeclaration(AstDeclaration::Declaration decl) or
    TImplicitParameterDeclaration(LocalVariable v) { v.isImplicitReceiverParameter(_) }

  final class Declaration = DeclarationImpl;

  abstract private class DeclarationImpl extends TDeclaration {
    abstract TypeMention getDeclaringType();

    abstract TypeMention getType();

    abstract Identifier getNameNode();

    abstract string toString();

    abstract Location getLocation();
  }

  private class ExplicitDeclarationImpl extends DeclarationImpl, TExplicitDeclaration {
    AstDeclaration::Declaration decl;

    ExplicitDeclarationImpl() { this = TExplicitDeclaration(decl) }

    AstDeclaration::Declaration getAstNode() { result = decl }

    override TypeMention getDeclaringType() { result = decl.getDeclaringType() }

    override TypeMention getType() { result = decl.getType() }

    override Identifier getNameNode() { result = decl.getNameNode() }

    override string toString() { result = decl.toString() }

    override Location getLocation() { result = decl.getLocation() }
  }

  class Variable extends LocalNameBindingOutput::Local {
    Expr getAnAccess() { result = super.getAnAccess() }
  }

  final class VariableDeclaration = VariableDeclarationImpl;

  abstract private class VariableDeclarationImpl extends DeclarationImpl {
    abstract AstNode getPattern();

    abstract AstNode getInitializer();

    predicate preservesInitializerType() { any() }
  }

  private class ExplicitVariableDeclarationImpl extends VariableDeclarationImpl,
    ExplicitDeclarationImpl
  {
    override AstDeclaration::VariableDeclaration decl;

    override AstNode getPattern() { result = decl.getPattern() }

    override AstNode getInitializer() { result = decl.getInitializer() }
  }

  class Field extends ExplicitDeclarationImpl {
    override AstDeclaration::Field decl;
  }

  abstract class FieldAccess extends Expr {
    abstract Expr getReceiver();

    abstract Field getField();
  }

  pragma[nomagic]
  private predicate lookupMember0(MemberAccessExpr mae, ClassLikeDeclaration cls, string name) {
    cls = inferType(mae.getBase()).(ClassLikeDeclarationType).getClassLikeDeclaration() and
    name = mae.getMemberName()
  }

  pragma[nomagic]
  private Identifier lookupMember(MemberAccessExpr mae) {
    exists(ClassLikeDeclaration cls, ExplicitDeclarationImpl decl, string name |
      lookupMember0(mae, cls, name) and
      decl.getAstNode().isMemberOf(cls, result, name)
    )
  }

  private class MemberAccessExprFieldAccess extends FieldAccess, MemberAccessExpr {
    override Expr getReceiver() { result = this.getBase() }

    pragma[nomagic]
    private predicate isTupleProjection(TupleType tuple, string name) {
      tuple = inferType(this.getBase()) and
      name = this.getMemberName()
    }

    override Field getField() {
      // mutual recursion; resolving qualified fields requires resolving types and vice versa
      result.getNameNode() = lookupMember(this)
      or
      // also mutual recursion
      exists(TupleType tuple, string name |
        this.isTupleProjection(tuple, name) and
        result.getAstNode() = tuple.getField(name)
      )
      or
      // no mutual recursion; can be resolved directly with static name binding
      result.getNameNode() = getStaticBindingTargetFromRef(this)
    }
  }

  private Type getImplicitReceiverType(UnqualifiedMemberAccess uma, TypePath path) {
    exists(ImplicitParameterDeclarationImpl p |
      p.getVariable() = uma.getImplicitQualifierVariable() and
      result = p.getType().getTypeAt(path)
    )
  }

  private class UnqualifiedMemberAccessFieldAccess extends FieldAccess, UnqualifiedMemberAccess {
    override Expr getReceiver() { none() }

    override Field getField() { result.getNameNode() = this.getTarget() }
  }

  Type inferFieldAccessReceiverType(FieldAccess fa, TypePath path) {
    // instance field with explicit receiver
    result = inferType(fa.getReceiver(), path)
    or
    // static field with type qualifier
    result = fa.(MemberAccessExpr).getBase().(TypeMention).getTypeAt(path)
    or
    // field with implicit receiver
    result = getImplicitReceiverType(fa, path)
  }

  Type inferFieldAccessReceiverTypeContextual(Expr receiver, TypePath path) {
    result = M3::inferFieldAccessReceiverTypeContextualDefault(_, receiver, path)
  }

  class Return extends ReturnExpr {
    Expr getExpr() { result = this.getValue() }
  }

  final class Parameter = ParameterImpl;

  abstract private class ParameterImpl extends VariableDeclarationImpl { }

  private class ExplicitParameterImpl extends ParameterImpl, ExplicitDeclarationImpl {
    override AstDeclaration::Parameter decl;

    override AstNode getPattern() { result = decl.getPattern() }

    override AstNode getInitializer() { result = decl.getInitializer() }
  }

  private class ImplicitParameterDeclarationImpl extends ParameterImpl,
    TImplicitParameterDeclaration
  {
    LocalVariable v;

    ImplicitParameterDeclarationImpl() { this = TImplicitParameterDeclaration(v) }

    LocalVariable getVariable() { result = v }

    override AstNode getPattern() { none() }

    override AstNode getInitializer() { none() }

    override TypeMention getDeclaringType() { none() }

    override TypeMention getType() {
      result = v.getDeclaringCallable().(AstDeclaration::Callable).getDeclaringType()
    }

    override Identifier getNameNode() { none() }

    override string toString() { result = v.toString() }

    override Location getLocation() { result = v.getLocation() }
  }

  predicate implicitParameterDecl(Parameter p, Variable v) {
    v = p.(ImplicitParameterDeclarationImpl).getVariable()
  }

  class Callable extends ExplicitDeclarationImpl {
    override AstDeclaration::Callable decl;

    TypeParameter getTypeParameter(int i) { result = decl.getTypeParameter(i) }

    TypeMention getAdditionalTypeParameterConstraint(TypeParameter tp) {
      result = decl.getAdditionalTypeParameterConstraint(tp)
    }

    Parameter getParameter(int i) {
      result = TExplicitDeclaration(decl.getParameter(i - 1))
      or
      i = 0 and
      exists(LocalVariable v |
        result = TImplicitParameterDeclaration(v) and
        v.isImplicitReceiverParameter(decl)
      )
    }

    AstNode getBody() { result = decl.getBody() }
  }

  Callable getEnclosingCallable(AstNode node) {
    result = TExplicitDeclaration(node.getEnclosingCallable())
  }

  class InvocationResolutionContext = Unit;

  class Invocation extends Expr, CallExpr {
    Type getTypeQualifier(TypePath path) {
      exists(TypeMention tm | result = tm.getTypeAt(path) |
        tm = super.getCallee()
        or
        not super.getCallee() instanceof TypeMention and
        tm = super.getCallee().(MemberAccessExpr).getBase()
      )
    }

    Type getTypeArgument(int i, TypePath path) { none() }

    int getNumberOfArguments() { result = CallExpr.super.getNumberOfArguments() + 1 }

    Expr getArgument(int i) {
      i = 0 and
      exists(boolean isFunctionExprInvoke | exists(this.getTargetImpl(isFunctionExprInvoke)) |
        if isFunctionExprInvoke = true
        then result = CallExpr.super.getCallee()
        else result = CallExpr.super.getCallee().(MemberAccessExpr).getBase()
      )
      or
      result = CallExpr.super.getArgument(i - 1).getValue()
    }

    /** Gets the special `invoke` target when the callee evaluates to a function expression. */
    pragma[nomagic]
    Unified::Callable getInvokeTarget(Type t) {
      t = inferType(this.getCallee()) and
      result = getFunctionInvoke(t)
    }

    private Unified::Callable getTargetViaStaticNameBinding() {
      exists(NameBinding b | b = getStaticBindingTargetFromRef(this.getCallee()) |
        // object creation (including enum constructors): `String(42)`, `Optional.Some(42)`
        exists(ClassLikeDeclaration cls, ConstructorDeclaration init |
          cls.getNameNode() = b and
          init = cls.getAMember() and
          result = init
        )
        or
        // call without explicit receiver: `foo(42)`
        result.(AstDeclaration::Declaration).getNameNode() = b
      )
    }

    Unified::Callable getTargetImpl(boolean isFunctionExprInvoke) {
      // mutual recursion; call with explicit receiver: `obj.foo(42)`
      result.(AstDeclaration::Declaration).getNameNode() = lookupMember(this.getCallee()) and
      isFunctionExprInvoke = false
      or
      // mutual recursion; call to a function expression: `callback(42)`
      result = this.getInvokeTarget(_) and
      isFunctionExprInvoke = true
      or
      // no mutual recursion; can be resolved directly with static name binding
      result = this.getTargetViaStaticNameBinding() and
      isFunctionExprInvoke = false
    }

    Callable getTarget(InvocationResolutionContext c) {
      result.getAstNode() = this.getTargetImpl(_) and
      exists(c)
    }

    Callable getATargetForTypeQualifierMatching() {
      result.getAstNode() = this.getTargetViaStaticNameBinding()
    }
  }

  Type inferInvocationArgumentType(
    Invocation invocation, InvocationResolutionContext ctx, int i, TypePath path
  ) {
    exists(ctx) and
    (
      // A call to a function expression
      exists(Type t | exists(invocation.getInvokeTarget(t)) |
        i = 0 and
        result = inferType(invocation.(CallExpr).getCallee(), path)
        or
        exists(TypePath prefix, TypePath suffix, int j |
          functionInvokeSignature(t, invocation.getNumberOfArguments() - 1, j, i, prefix) and
          result = inferType(invocation.getArgument(j + 1), suffix) and
          path = prefix.append(suffix)
        )
      )
      or
      // A call to a regular function or method
      exists(invocation.getTargetImpl(false)) and
      (
        result = inferType(invocation.getArgument(i), path)
        or
        i = 0 and
        result = getImplicitReceiverType(invocation.(CallExpr).getCallee(), path)
      )
    )
  }

  Type inferInvocationArgumentTypeContextual(Expr arg, TypePath path) {
    result = M3::inferInvocationArgumentTypeContextualDefault(_, _, _, arg, path)
  }

  Type inferInvocationType(Invocation invocation, TypePath path) {
    result = M3::inferInvocationTypeDefault(invocation, _, path)
  }

  class Closure extends Callable, ExplicitDeclarationImpl {
    override AstDeclaration::Closure decl;

    Expr getDefiningExpr() { result = decl }
  }

  class ClosureParameterPseudoType extends T::ClosureParameterPseudoType {
    Parameter getParameter() { result = TExplicitDeclaration(this.getParam()) }
  }

  pragma[nomagic]
  Type getClosureType(Closure c) { result = getFunctionExprType(c.getAstNode()) }

  pragma[nomagic]
  TypePath getClosureParameterTypePath(Parameter p) {
    exists(FunctionExpr fe, Type t, int i |
      p = TExplicitDeclaration(fe.getParameter(i)) and
      t = getFunctionExprType(fe) and
      result = getFunctionExprParameterTypePath(t, fe.getNumberOfParameters(), i)
    )
  }

  pragma[nomagic]
  TypePath getClosureReturnTypePath(Closure c) {
    result = getFunctionExprReturnTypePath(getClosureType(c))
  }

  predicate stepLanguageSpecific(AstNode n1, TypePath prefix1, AstNode n2, TypePath prefix2) {
    n1 = n2.(Block).getLastStmt() and
    prefix1.isEmpty() and
    prefix2.isEmpty()
    or
    hasResultValue(n2) and
    n1 = n2.(ArrayLiteral).getAnElement() and
    prefix1.isEmpty() and
    prefix2 = TypePath::singleton(getArrayElementTypeParameter())
    or
    hasResultValue(n2) and
    n2 =
      any(TupleExpr te |
        exists(int i, int arity, TupleType tt |
          n1 = te.getElement(i).getValue() and
          arity = te.getNumberOfElements() and
          tt.getArity() = arity and
          prefix1.isEmpty() and
          prefix2 = TypePath::singleton(tt.getPositionalTypeParameter(i))
        )
      )
  }

  Type inferTypeLanguageSpecific(AstNode n, TypePath path) {
    result = Plugin::inferType(n, path)
    or
    n instanceof BooleanLiteral and
    result instanceof BoolType and
    path.isEmpty()
    or
    n instanceof IntLiteral and
    result instanceof IntType and
    path.isEmpty()
    or
    n instanceof FloatLiteral and
    result instanceof FloatType and
    path.isEmpty()
    or
    n instanceof StringLiteral and
    result instanceof StringType and
    path.isEmpty()
    or
    exists(ClassLikeDeclaration c |
      c = n.(SuperExpr).getEnclosingClass() and
      result = c.getBaseType(0).getType().(TypeMention).getTypeAt(path)
    )
    or
    // `Optional.none` has an unknown `Wrapper` type
    exists(Field f, TypeParameter tp |
      n.(FieldAccess).getField() = f and
      f.(ExplicitDeclarationImpl).getAstNode() instanceof EnumField and
      tp = f.getType().getType().getATypeParameter() and
      path = TypePath::singleton(tp) and
      // `Optional<String>.none` does not have an unknown `Wrapper` type
      not exists(n.(MemberAccessExpr).getBase().(TypeMention).getTypeAt(path))
    ) and
    result instanceof UnknownType
  }

  pragma[nomagic]
  Type inferTypeCertainLanguageSpecific(AstNode n, TypePath path) { none() }
}

private module M3 = Make3<Input3>;

predicate inferType = M3::inferType/1;

predicate inferType = M3::inferType/2;

predicate inferTypeCertain = M3::inferTypeCertain/2;

module Consistency = M3::Consistency;

module CachedStage = M3::CachedStage;

/**
 * Gets the field that is accessed by the given expression.
 *
 * `access` is either a `MemberAccessExpr` or an `Identifier` (when
 * the field is accessed with an implicit receiver).
 */
cached
VariableDeclaration resolveFieldAccess(Expr access) {
  CachedStage::ref() and
  result = access.(Input3::FieldAccess).getField().getAstNode()
}

/**
 * Gets the static call target of the given call expression.
 *
 * Does not yet take overloading into account.
 */
cached
Callable resolveCallTarget(CallExpr ce) {
  CachedStage::ref() and
  result = ce.(Input3::Invocation).getTargetImpl(_)
}

private predicate typeTestAstNodeRepr(AstNode n, string repr) {
  repr = [n.toString(), n.(Identifier).getValue(), "." + n.(MemberAccessExpr).getMemberName()]
}

module TypeTest implements TestSig {
  private module M = M3::TypeTest<typeTestAstNodeRepr/2>;

  import M

  predicate hasOptionalResult = M::hasOptionalResult/4;
}

/** Provides predicates for debugging the type inference implementation. */
private module Debug {
  AstNode getRelevantNode() {
    exists(string filepath, int startline, int startcolumn, int endline, int endcolumn |
      result.getLocation().hasLocationInfo(filepath, startline, startcolumn, endline, endcolumn) and
      filepath.matches("%/test.swift") and
      startline = 1
    )
  }

  Type debugInferType(AstNode n, TypePath path) {
    n = getRelevantNode() and
    result = inferType(n, path)
  }

  Callable debugResolveCallTarget(CallExpr ce) {
    ce = getRelevantNode() and
    result = resolveCallTarget(ce)
  }

  predicate debugTypeMention(TypeMention tm, TypePath path, Type type) {
    tm = getRelevantNode() and
    tm.getTypeAt(path) = type
  }

  predicate atLimit = M3::Debug::atLimit/1;

  predicate inferTypeForNodeAtLimit = M3::Debug::inferTypeForNodeAtLimit/2;

  predicate countTypesForNodeAtLimit = M3::Debug::countTypesForNodeAtLimit/2;

  predicate maxTypes = M3::Debug::maxTypes/4;

  predicate maxTypePath = M3::Debug::maxTypePath/4;

  predicate maxTypePaths = M3::Debug::maxTypePaths/4;

  Type debugInferTypeCertain(AstNode n, TypePath path) {
    n = getRelevantNode() and
    result = inferTypeCertain(n, path)
  }

  Type debugInferCertainNonUniqueType(AstNode n, TypePath path) {
    n = getRelevantNode() and
    Consistency::nonUniqueCertainType(n, path) and
    result = inferTypeCertain(n, path)
  }
}
