load(
    "//misc/bazel:csharp.bzl",
    "codeql_csharp_library",
)

codeql_csharp_library(
    name = "Semmle.Extraction",
    srcs = glob([
        "Entities/**/*.cs",
        "Extractor/**/*.cs",
        "*.cs",
    ]),
    visibility = ["//powershell:__subpackages__"],
    deps = [
        "//powershell/extractor/Semmle.Util",
        "@paket.powershell//microsoft.codeanalysis",
    ],
)
