#Copyright Wikipedia

#THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE COMMONS PUBLIC LICENSE ("CCPL" OR "LICENSE").
#THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER
# THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
#BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE.
#TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE
# IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.

class A(object): pass

class B(object): pass

class C(object): pass

class D(object): pass

class E(object): pass

class K1(A, B, C): pass

class K2(D, B, E): pass

class K3(D, A): pass

class M(K1, K2, K3): pass

#>>> M.mro()
# [M, K1, K2, K3, D, A, B, C, E, object]
