// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"bufio"
	"io"
)

func TaintStepTest_BufioNewReadWriter_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader656 := sourceCQL.(*bufio.Reader)
	intoReadWriter414 := bufio.NewReadWriter(fromReader656, nil)
	return intoReadWriter414
}

func TaintStepTest_BufioNewReadWriter_B1I0O0(sourceCQL interface{}) interface{} {
	fromReadWriter518 := sourceCQL.(*bufio.ReadWriter)
	var intoWriter650 *bufio.Writer
	intermediateCQL := bufio.NewReadWriter(nil, intoWriter650)
	link(fromReadWriter518, intermediateCQL)
	return intoWriter650
}

func TaintStepTest_BufioNewReader_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader784 := sourceCQL.(io.Reader)
	intoReader957 := bufio.NewReader(fromReader784)
	return intoReader957
}

func TaintStepTest_BufioNewReaderSize_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader520 := sourceCQL.(io.Reader)
	intoReader443 := bufio.NewReaderSize(fromReader520, 0)
	return intoReader443
}

func TaintStepTest_BufioNewScanner_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader127 := sourceCQL.(io.Reader)
	intoScanner483 := bufio.NewScanner(fromReader127)
	return intoScanner483
}

func TaintStepTest_BufioNewWriter_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter989 := sourceCQL.(*bufio.Writer)
	var intoWriter982 io.Writer
	intermediateCQL := bufio.NewWriter(intoWriter982)
	link(fromWriter989, intermediateCQL)
	return intoWriter982
}

func TaintStepTest_BufioNewWriterSize_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter417 := sourceCQL.(*bufio.Writer)
	var intoWriter584 io.Writer
	intermediateCQL := bufio.NewWriterSize(intoWriter584, 0)
	link(fromWriter417, intermediateCQL)
	return intoWriter584
}

func TaintStepTest_BufioScanBytes_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte991 := sourceCQL.([]byte)
	_, intoByte881, _ := bufio.ScanBytes(fromByte991, false)
	return intoByte881
}

func TaintStepTest_BufioScanLines_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte186 := sourceCQL.([]byte)
	_, intoByte284, _ := bufio.ScanLines(fromByte186, false)
	return intoByte284
}

func TaintStepTest_BufioScanRunes_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte908 := sourceCQL.([]byte)
	_, intoByte137, _ := bufio.ScanRunes(fromByte908, false)
	return intoByte137
}

func TaintStepTest_BufioScanWords_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte494 := sourceCQL.([]byte)
	_, intoByte873, _ := bufio.ScanWords(fromByte494, false)
	return intoByte873
}

func TaintStepTest_BufioReaderPeek_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader599 := sourceCQL.(bufio.Reader)
	intoByte409, _ := fromReader599.Peek(0)
	return intoByte409
}

func TaintStepTest_BufioReaderRead_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader246 := sourceCQL.(bufio.Reader)
	var intoByte898 []byte
	fromReader246.Read(intoByte898)
	return intoByte898
}

func TaintStepTest_BufioReaderReadBytes_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader598 := sourceCQL.(bufio.Reader)
	intoByte631, _ := fromReader598.ReadBytes(0)
	return intoByte631
}

func TaintStepTest_BufioReaderReadLine_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader165 := sourceCQL.(bufio.Reader)
	intoByte150, _, _ := fromReader165.ReadLine()
	return intoByte150
}

func TaintStepTest_BufioReaderReadSlice_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader340 := sourceCQL.(bufio.Reader)
	intoByte471, _ := fromReader340.ReadSlice(0)
	return intoByte471
}

func TaintStepTest_BufioReaderReadString_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader290 := sourceCQL.(bufio.Reader)
	intoString758, _ := fromReader290.ReadString(0)
	return intoString758
}

func TaintStepTest_BufioReaderReset_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader396 := sourceCQL.(io.Reader)
	var intoReader707 bufio.Reader
	intoReader707.Reset(fromReader396)
	return intoReader707
}

func TaintStepTest_BufioReaderWriteTo_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader912 := sourceCQL.(bufio.Reader)
	var intoWriter718 io.Writer
	fromReader912.WriteTo(intoWriter718)
	return intoWriter718
}

func TaintStepTest_BufioScannerBytes_B0I0O0(sourceCQL interface{}) interface{} {
	fromScanner972 := sourceCQL.(bufio.Scanner)
	intoByte633 := fromScanner972.Bytes()
	return intoByte633
}

func TaintStepTest_BufioScannerText_B0I0O0(sourceCQL interface{}) interface{} {
	fromScanner316 := sourceCQL.(bufio.Scanner)
	intoString145 := fromScanner316.Text()
	return intoString145
}

func TaintStepTest_BufioWriterReadFrom_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader817 := sourceCQL.(io.Reader)
	var intoWriter474 bufio.Writer
	intoWriter474.ReadFrom(fromReader817)
	return intoWriter474
}

func TaintStepTest_BufioWriterReset_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter832 := sourceCQL.(bufio.Writer)
	var intoWriter378 io.Writer
	fromWriter832.Reset(intoWriter378)
	return intoWriter378
}

func TaintStepTest_BufioWriterWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte541 := sourceCQL.([]byte)
	var intoWriter139 bufio.Writer
	intoWriter139.Write(fromByte541)
	return intoWriter139
}

func TaintStepTest_BufioWriterWriteString_B0I0O0(sourceCQL interface{}) interface{} {
	fromString814 := sourceCQL.(string)
	var intoWriter768 bufio.Writer
	intoWriter768.WriteString(fromString814)
	return intoWriter768
}

func RunAllTaints_Bufio() {
	{
		source := newSource(0)
		out := TaintStepTest_BufioNewReadWriter_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_BufioNewReadWriter_B1I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_BufioNewReader_B0I0O0(source)
		sink(2, out)
	}
	{
		source := newSource(3)
		out := TaintStepTest_BufioNewReaderSize_B0I0O0(source)
		sink(3, out)
	}
	{
		source := newSource(4)
		out := TaintStepTest_BufioNewScanner_B0I0O0(source)
		sink(4, out)
	}
	{
		source := newSource(5)
		out := TaintStepTest_BufioNewWriter_B0I0O0(source)
		sink(5, out)
	}
	{
		source := newSource(6)
		out := TaintStepTest_BufioNewWriterSize_B0I0O0(source)
		sink(6, out)
	}
	{
		source := newSource(7)
		out := TaintStepTest_BufioScanBytes_B0I0O0(source)
		sink(7, out)
	}
	{
		source := newSource(8)
		out := TaintStepTest_BufioScanLines_B0I0O0(source)
		sink(8, out)
	}
	{
		source := newSource(9)
		out := TaintStepTest_BufioScanRunes_B0I0O0(source)
		sink(9, out)
	}
	{
		source := newSource(10)
		out := TaintStepTest_BufioScanWords_B0I0O0(source)
		sink(10, out)
	}
	{
		source := newSource(11)
		out := TaintStepTest_BufioReaderPeek_B0I0O0(source)
		sink(11, out)
	}
	{
		source := newSource(12)
		out := TaintStepTest_BufioReaderRead_B0I0O0(source)
		sink(12, out)
	}
	{
		source := newSource(13)
		out := TaintStepTest_BufioReaderReadBytes_B0I0O0(source)
		sink(13, out)
	}
	{
		source := newSource(14)
		out := TaintStepTest_BufioReaderReadLine_B0I0O0(source)
		sink(14, out)
	}
	{
		source := newSource(15)
		out := TaintStepTest_BufioReaderReadSlice_B0I0O0(source)
		sink(15, out)
	}
	{
		source := newSource(16)
		out := TaintStepTest_BufioReaderReadString_B0I0O0(source)
		sink(16, out)
	}
	{
		source := newSource(17)
		out := TaintStepTest_BufioReaderReset_B0I0O0(source)
		sink(17, out)
	}
	{
		source := newSource(18)
		out := TaintStepTest_BufioReaderWriteTo_B0I0O0(source)
		sink(18, out)
	}
	{
		source := newSource(19)
		out := TaintStepTest_BufioScannerBytes_B0I0O0(source)
		sink(19, out)
	}
	{
		source := newSource(20)
		out := TaintStepTest_BufioScannerText_B0I0O0(source)
		sink(20, out)
	}
	{
		source := newSource(21)
		out := TaintStepTest_BufioWriterReadFrom_B0I0O0(source)
		sink(21, out)
	}
	{
		source := newSource(22)
		out := TaintStepTest_BufioWriterReset_B0I0O0(source)
		sink(22, out)
	}
	{
		source := newSource(23)
		out := TaintStepTest_BufioWriterWrite_B0I0O0(source)
		sink(23, out)
	}
	{
		source := newSource(24)
		out := TaintStepTest_BufioWriterWriteString_B0I0O0(source)
		sink(24, out)
	}
}
