// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"compress/flate"
	"io"
)

func TaintStepTest_CompressFlateNewReader_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader656 := sourceCQL.(io.Reader)
	intoReadCloser414 := flate.NewReader(fromReader656)
	return intoReadCloser414
}

func TaintStepTest_CompressFlateNewReaderDict_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader518 := sourceCQL.(io.Reader)
	intoReadCloser650 := flate.NewReaderDict(fromReader518, nil)
	return intoReadCloser650
}

func TaintStepTest_CompressFlateNewWriter_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter784 := sourceCQL.(*flate.Writer)
	var intoWriter957 io.Writer
	intermediateCQL, _ := flate.NewWriter(intoWriter957, 0)
	link(fromWriter784, intermediateCQL)
	return intoWriter957
}

func TaintStepTest_CompressFlateNewWriterDict_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter520 := sourceCQL.(*flate.Writer)
	var intoWriter443 io.Writer
	intermediateCQL, _ := flate.NewWriterDict(intoWriter443, 0, nil)
	link(fromWriter520, intermediateCQL)
	return intoWriter443
}

func TaintStepTest_CompressFlateWriterReset_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter127 := sourceCQL.(flate.Writer)
	var intoWriter483 io.Writer
	fromWriter127.Reset(intoWriter483)
	return intoWriter483
}

func TaintStepTest_CompressFlateWriterWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte989 := sourceCQL.([]byte)
	var intoWriter982 flate.Writer
	intoWriter982.Write(fromByte989)
	return intoWriter982
}

func TaintStepTest_CompressFlateResetterReset_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader417 := sourceCQL.(io.Reader)
	var intoResetter584 flate.Resetter
	intoResetter584.Reset(fromReader417, nil)
	return intoResetter584
}

func RunAllTaints_CompressFlate() {
	{
		source := newSource(0)
		out := TaintStepTest_CompressFlateNewReader_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_CompressFlateNewReaderDict_B0I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_CompressFlateNewWriter_B0I0O0(source)
		sink(2, out)
	}
	{
		source := newSource(3)
		out := TaintStepTest_CompressFlateNewWriterDict_B0I0O0(source)
		sink(3, out)
	}
	{
		source := newSource(4)
		out := TaintStepTest_CompressFlateWriterReset_B0I0O0(source)
		sink(4, out)
	}
	{
		source := newSource(5)
		out := TaintStepTest_CompressFlateWriterWrite_B0I0O0(source)
		sink(5, out)
	}
	{
		source := newSource(6)
		out := TaintStepTest_CompressFlateResetterReset_B0I0O0(source)
		sink(6, out)
	}
}
