// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"encoding/binary"
	"io"
)

func TaintStepTest_EncodingBinaryRead_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader656 := sourceCQL.(io.Reader)
	var intoInterface414 interface{}
	binary.Read(fromReader656, nil, intoInterface414)
	return intoInterface414
}

func TaintStepTest_EncodingBinaryWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface518 := sourceCQL.(interface{})
	var intoWriter650 io.Writer
	binary.Write(intoWriter650, nil, fromInterface518)
	return intoWriter650
}

func RunAllTaints_EncodingBinary() {
	{
		source := newSource(0)
		out := TaintStepTest_EncodingBinaryRead_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_EncodingBinaryWrite_B0I0O0(source)
		sink(1, out)
	}
}
