// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"bytes"
	"encoding/json"
	"io"
)

func TaintStepTest_EncodingJsonCompact_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte656 := sourceCQL.([]byte)
	var intoBuffer414 *bytes.Buffer
	json.Compact(intoBuffer414, fromByte656)
	return intoBuffer414
}

func TaintStepTest_EncodingJsonHTMLEscape_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte518 := sourceCQL.([]byte)
	var intoBuffer650 *bytes.Buffer
	json.HTMLEscape(intoBuffer650, fromByte518)
	return intoBuffer650
}

func TaintStepTest_EncodingJsonIndent_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte784 := sourceCQL.([]byte)
	var intoBuffer957 *bytes.Buffer
	json.Indent(intoBuffer957, fromByte784, "", "")
	return intoBuffer957
}

func TaintStepTest_EncodingJsonIndent_B0I1O0(sourceCQL interface{}) interface{} {
	fromString520 := sourceCQL.(string)
	var intoBuffer443 *bytes.Buffer
	json.Indent(intoBuffer443, nil, fromString520, "")
	return intoBuffer443
}

func TaintStepTest_EncodingJsonIndent_B0I2O0(sourceCQL interface{}) interface{} {
	fromString127 := sourceCQL.(string)
	var intoBuffer483 *bytes.Buffer
	json.Indent(intoBuffer483, nil, "", fromString127)
	return intoBuffer483
}

func TaintStepTest_EncodingJsonMarshal_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface989 := sourceCQL.(interface{})
	intoByte982, _ := json.Marshal(fromInterface989)
	return intoByte982
}

func TaintStepTest_EncodingJsonMarshalIndent_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface417 := sourceCQL.(interface{})
	intoByte584, _ := json.MarshalIndent(fromInterface417, "", "")
	return intoByte584
}

func TaintStepTest_EncodingJsonMarshalIndent_B0I1O0(sourceCQL interface{}) interface{} {
	fromString991 := sourceCQL.(string)
	intoByte881, _ := json.MarshalIndent(nil, fromString991, "")
	return intoByte881
}

func TaintStepTest_EncodingJsonMarshalIndent_B0I2O0(sourceCQL interface{}) interface{} {
	fromString186 := sourceCQL.(string)
	intoByte284, _ := json.MarshalIndent(nil, "", fromString186)
	return intoByte284
}

func TaintStepTest_EncodingJsonNewDecoder_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader908 := sourceCQL.(io.Reader)
	intoDecoder137 := json.NewDecoder(fromReader908)
	return intoDecoder137
}

func TaintStepTest_EncodingJsonNewEncoder_B0I0O0(sourceCQL interface{}) interface{} {
	fromEncoder494 := sourceCQL.(*json.Encoder)
	var intoWriter873 io.Writer
	intermediateCQL := json.NewEncoder(intoWriter873)
	link(fromEncoder494, intermediateCQL)
	return intoWriter873
}

func TaintStepTest_EncodingJsonUnmarshal_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte599 := sourceCQL.([]byte)
	var intoInterface409 interface{}
	json.Unmarshal(fromByte599, intoInterface409)
	return intoInterface409
}

func TaintStepTest_EncodingJsonDecoderBuffered_B0I0O0(sourceCQL interface{}) interface{} {
	fromDecoder246 := sourceCQL.(json.Decoder)
	intoReader898 := fromDecoder246.Buffered()
	return intoReader898
}

func TaintStepTest_EncodingJsonDecoderDecode_B0I0O0(sourceCQL interface{}) interface{} {
	fromDecoder598 := sourceCQL.(json.Decoder)
	var intoInterface631 interface{}
	fromDecoder598.Decode(intoInterface631)
	return intoInterface631
}

func TaintStepTest_EncodingJsonDecoderToken_B0I0O0(sourceCQL interface{}) interface{} {
	fromDecoder165 := sourceCQL.(json.Decoder)
	intoToken150, _ := fromDecoder165.Token()
	return intoToken150
}

func TaintStepTest_EncodingJsonEncoderEncode_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface340 := sourceCQL.(interface{})
	var intoEncoder471 json.Encoder
	intoEncoder471.Encode(fromInterface340)
	return intoEncoder471
}

func TaintStepTest_EncodingJsonEncoderSetIndent_B0I0O0(sourceCQL interface{}) interface{} {
	fromString290 := sourceCQL.(string)
	var intoEncoder758 json.Encoder
	intoEncoder758.SetIndent(fromString290, "")
	return intoEncoder758
}

func TaintStepTest_EncodingJsonEncoderSetIndent_B0I1O0(sourceCQL interface{}) interface{} {
	fromString396 := sourceCQL.(string)
	var intoEncoder707 json.Encoder
	intoEncoder707.SetIndent("", fromString396)
	return intoEncoder707
}

func TaintStepTest_EncodingJsonRawMessageMarshalJSON_B0I0O0(sourceCQL interface{}) interface{} {
	fromRawMessage912 := sourceCQL.(json.RawMessage)
	intoByte718, _ := fromRawMessage912.MarshalJSON()
	return intoByte718
}

func TaintStepTest_EncodingJsonRawMessageUnmarshalJSON_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte972 := sourceCQL.([]byte)
	var intoRawMessage633 json.RawMessage
	intoRawMessage633.UnmarshalJSON(fromByte972)
	return intoRawMessage633
}

func TaintStepTest_EncodingJsonMarshalerMarshalJSON_B0I0O0(sourceCQL interface{}) interface{} {
	fromMarshaler316 := sourceCQL.(json.Marshaler)
	intoByte145, _ := fromMarshaler316.MarshalJSON()
	return intoByte145
}

func TaintStepTest_EncodingJsonUnmarshalerUnmarshalJSON_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte817 := sourceCQL.([]byte)
	var intoUnmarshaler474 json.Unmarshaler
	intoUnmarshaler474.UnmarshalJSON(fromByte817)
	return intoUnmarshaler474
}

func RunAllTaints_EncodingJson() {
	{
		source := newSource(0)
		out := TaintStepTest_EncodingJsonCompact_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_EncodingJsonHTMLEscape_B0I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_EncodingJsonIndent_B0I0O0(source)
		sink(2, out)
	}
	{
		source := newSource(3)
		out := TaintStepTest_EncodingJsonIndent_B0I1O0(source)
		sink(3, out)
	}
	{
		source := newSource(4)
		out := TaintStepTest_EncodingJsonIndent_B0I2O0(source)
		sink(4, out)
	}
	{
		source := newSource(5)
		out := TaintStepTest_EncodingJsonMarshal_B0I0O0(source)
		sink(5, out)
	}
	{
		source := newSource(6)
		out := TaintStepTest_EncodingJsonMarshalIndent_B0I0O0(source)
		sink(6, out)
	}
	{
		source := newSource(7)
		out := TaintStepTest_EncodingJsonMarshalIndent_B0I1O0(source)
		sink(7, out)
	}
	{
		source := newSource(8)
		out := TaintStepTest_EncodingJsonMarshalIndent_B0I2O0(source)
		sink(8, out)
	}
	{
		source := newSource(9)
		out := TaintStepTest_EncodingJsonNewDecoder_B0I0O0(source)
		sink(9, out)
	}
	{
		source := newSource(10)
		out := TaintStepTest_EncodingJsonNewEncoder_B0I0O0(source)
		sink(10, out)
	}
	{
		source := newSource(11)
		out := TaintStepTest_EncodingJsonUnmarshal_B0I0O0(source)
		sink(11, out)
	}
	{
		source := newSource(12)
		out := TaintStepTest_EncodingJsonDecoderBuffered_B0I0O0(source)
		sink(12, out)
	}
	{
		source := newSource(13)
		out := TaintStepTest_EncodingJsonDecoderDecode_B0I0O0(source)
		sink(13, out)
	}
	{
		source := newSource(14)
		out := TaintStepTest_EncodingJsonDecoderToken_B0I0O0(source)
		sink(14, out)
	}
	{
		source := newSource(15)
		out := TaintStepTest_EncodingJsonEncoderEncode_B0I0O0(source)
		sink(15, out)
	}
	{
		source := newSource(16)
		out := TaintStepTest_EncodingJsonEncoderSetIndent_B0I0O0(source)
		sink(16, out)
	}
	{
		source := newSource(17)
		out := TaintStepTest_EncodingJsonEncoderSetIndent_B0I1O0(source)
		sink(17, out)
	}
	{
		source := newSource(18)
		out := TaintStepTest_EncodingJsonRawMessageMarshalJSON_B0I0O0(source)
		sink(18, out)
	}
	{
		source := newSource(19)
		out := TaintStepTest_EncodingJsonRawMessageUnmarshalJSON_B0I0O0(source)
		sink(19, out)
	}
	{
		source := newSource(20)
		out := TaintStepTest_EncodingJsonMarshalerMarshalJSON_B0I0O0(source)
		sink(20, out)
	}
	{
		source := newSource(21)
		out := TaintStepTest_EncodingJsonUnmarshalerUnmarshalJSON_B0I0O0(source)
		sink(21, out)
	}
}
