// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"fmt"
	"io"
)

func TaintStepTest_FmtErrorf_B0I0O0(sourceCQL interface{}) interface{} {
	fromString656 := sourceCQL.(string)
	intoError414 := fmt.Errorf(fromString656, nil)
	return intoError414
}

func TaintStepTest_FmtErrorf_B0I1O0(sourceCQL interface{}) interface{} {
	fromInterface518 := sourceCQL.(interface{})
	intoError650 := fmt.Errorf("", fromInterface518)
	return intoError650
}

func TaintStepTest_FmtFprint_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface784 := sourceCQL.(interface{})
	var intoWriter957 io.Writer
	fmt.Fprint(intoWriter957, fromInterface784)
	return intoWriter957
}

func TaintStepTest_FmtFprintf_B0I0O0(sourceCQL interface{}) interface{} {
	fromString520 := sourceCQL.(string)
	var intoWriter443 io.Writer
	fmt.Fprintf(intoWriter443, fromString520, nil)
	return intoWriter443
}

func TaintStepTest_FmtFprintf_B0I1O0(sourceCQL interface{}) interface{} {
	fromInterface127 := sourceCQL.(interface{})
	var intoWriter483 io.Writer
	fmt.Fprintf(intoWriter483, "", fromInterface127)
	return intoWriter483
}

func TaintStepTest_FmtFprintln_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface989 := sourceCQL.(interface{})
	var intoWriter982 io.Writer
	fmt.Fprintln(intoWriter982, fromInterface989)
	return intoWriter982
}

func TaintStepTest_FmtFscan_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader417 := sourceCQL.(io.Reader)
	var intoInterface584 interface{}
	fmt.Fscan(fromReader417, intoInterface584)
	return intoInterface584
}

func TaintStepTest_FmtFscanf_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader991 := sourceCQL.(io.Reader)
	var intoInterface881 interface{}
	fmt.Fscanf(fromReader991, "", intoInterface881)
	return intoInterface881
}

func TaintStepTest_FmtFscanf_B0I1O0(sourceCQL interface{}) interface{} {
	fromString186 := sourceCQL.(string)
	var intoInterface284 interface{}
	fmt.Fscanf(nil, fromString186, intoInterface284)
	return intoInterface284
}

func TaintStepTest_FmtFscanln_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader908 := sourceCQL.(io.Reader)
	var intoInterface137 interface{}
	fmt.Fscanln(fromReader908, intoInterface137)
	return intoInterface137
}

func TaintStepTest_FmtSprint_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface494 := sourceCQL.(interface{})
	intoString873 := fmt.Sprint(fromInterface494)
	return intoString873
}

func TaintStepTest_FmtSprintf_B0I0O0(sourceCQL interface{}) interface{} {
	fromString599 := sourceCQL.(string)
	intoString409 := fmt.Sprintf(fromString599, nil)
	return intoString409
}

func TaintStepTest_FmtSprintf_B0I1O0(sourceCQL interface{}) interface{} {
	fromInterface246 := sourceCQL.(interface{})
	intoString898 := fmt.Sprintf("", fromInterface246)
	return intoString898
}

func TaintStepTest_FmtSprintln_B0I0O0(sourceCQL interface{}) interface{} {
	fromInterface598 := sourceCQL.(interface{})
	intoString631 := fmt.Sprintln(fromInterface598)
	return intoString631
}

func TaintStepTest_FmtSscan_B0I0O0(sourceCQL interface{}) interface{} {
	fromString165 := sourceCQL.(string)
	var intoInterface150 interface{}
	fmt.Sscan(fromString165, intoInterface150)
	return intoInterface150
}

func TaintStepTest_FmtSscanf_B0I0O0(sourceCQL interface{}) interface{} {
	fromString340 := sourceCQL.(string)
	var intoInterface471 interface{}
	fmt.Sscanf(fromString340, "", intoInterface471)
	return intoInterface471
}

func TaintStepTest_FmtSscanf_B0I1O0(sourceCQL interface{}) interface{} {
	fromString290 := sourceCQL.(string)
	var intoInterface758 interface{}
	fmt.Sscanf("", fromString290, intoInterface758)
	return intoInterface758
}

func TaintStepTest_FmtSscanln_B0I0O0(sourceCQL interface{}) interface{} {
	fromString396 := sourceCQL.(string)
	var intoInterface707 interface{}
	fmt.Sscanln(fromString396, intoInterface707)
	return intoInterface707
}

func TaintStepTest_FmtGoStringerGoString_B0I0O0(sourceCQL interface{}) interface{} {
	fromGoStringer912 := sourceCQL.(fmt.GoStringer)
	intoString718 := fromGoStringer912.GoString()
	return intoString718
}

func TaintStepTest_FmtScanStateRead_B0I0O0(sourceCQL interface{}) interface{} {
	fromScanState972 := sourceCQL.(fmt.ScanState)
	var intoByte633 []byte
	fromScanState972.Read(intoByte633)
	return intoByte633
}

func TaintStepTest_FmtStringerString_B0I0O0(sourceCQL interface{}) interface{} {
	fromStringer316 := sourceCQL.(fmt.Stringer)
	intoString145 := fromStringer316.String()
	return intoString145
}

func TaintStepTest_FmtScanStateToken_B0I0O0(sourceCQL interface{}) interface{} {
	fromScanState817 := sourceCQL.(fmt.ScanState)
	intoByte474, _ := fromScanState817.Token(false, nil)
	return intoByte474
}

func TaintStepTest_FmtStateWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte832 := sourceCQL.([]byte)
	var intoState378 fmt.State
	intoState378.Write(fromByte832)
	return intoState378
}

func RunAllTaints_Fmt() {
	{
		source := newSource(0)
		out := TaintStepTest_FmtErrorf_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_FmtErrorf_B0I1O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_FmtFprint_B0I0O0(source)
		sink(2, out)
	}
	{
		source := newSource(3)
		out := TaintStepTest_FmtFprintf_B0I0O0(source)
		sink(3, out)
	}
	{
		source := newSource(4)
		out := TaintStepTest_FmtFprintf_B0I1O0(source)
		sink(4, out)
	}
	{
		source := newSource(5)
		out := TaintStepTest_FmtFprintln_B0I0O0(source)
		sink(5, out)
	}
	{
		source := newSource(6)
		out := TaintStepTest_FmtFscan_B0I0O0(source)
		sink(6, out)
	}
	{
		source := newSource(7)
		out := TaintStepTest_FmtFscanf_B0I0O0(source)
		sink(7, out)
	}
	{
		source := newSource(8)
		out := TaintStepTest_FmtFscanf_B0I1O0(source)
		sink(8, out)
	}
	{
		source := newSource(9)
		out := TaintStepTest_FmtFscanln_B0I0O0(source)
		sink(9, out)
	}
	{
		source := newSource(10)
		out := TaintStepTest_FmtSprint_B0I0O0(source)
		sink(10, out)
	}
	{
		source := newSource(11)
		out := TaintStepTest_FmtSprintf_B0I0O0(source)
		sink(11, out)
	}
	{
		source := newSource(12)
		out := TaintStepTest_FmtSprintf_B0I1O0(source)
		sink(12, out)
	}
	{
		source := newSource(13)
		out := TaintStepTest_FmtSprintln_B0I0O0(source)
		sink(13, out)
	}
	{
		source := newSource(14)
		out := TaintStepTest_FmtSscan_B0I0O0(source)
		sink(14, out)
	}
	{
		source := newSource(15)
		out := TaintStepTest_FmtSscanf_B0I0O0(source)
		sink(15, out)
	}
	{
		source := newSource(16)
		out := TaintStepTest_FmtSscanf_B0I1O0(source)
		sink(16, out)
	}
	{
		source := newSource(17)
		out := TaintStepTest_FmtSscanln_B0I0O0(source)
		sink(17, out)
	}
	{
		source := newSource(18)
		out := TaintStepTest_FmtGoStringerGoString_B0I0O0(source)
		sink(18, out)
	}
	{
		source := newSource(19)
		out := TaintStepTest_FmtScanStateRead_B0I0O0(source)
		sink(19, out)
	}
	{
		source := newSource(20)
		out := TaintStepTest_FmtStringerString_B0I0O0(source)
		sink(20, out)
	}
	{
		source := newSource(21)
		out := TaintStepTest_FmtScanStateToken_B0I0O0(source)
		sink(21, out)
	}
	{
		source := newSource(22)
		out := TaintStepTest_FmtStateWrite_B0I0O0(source)
		sink(22, out)
	}
}
