// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `AstNode`.
 */

private import internal.AstNodeImpl
import codeql.swift.elements.Locatable

final class AstNode = Impl::AstNode;
