// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `DbLocation`.
 */

private import codeql.swift.generated.DbLocation

class DbLocation extends Generated::DbLocation { }
