// generated by codegen/codegen.py, do not edit
/**
 * This module provides the public class `UnknownLocation`.
 */

private import UnknownLocationImpl
import codeql.swift.elements.Location

final class UnknownLocation = Impl::UnknownLocation;
