import semmle.code.powershell.File
import semmle.code.powershell.Location
import semmle.code.powershell.SourceLocation
import semmle.code.powershell.Ast
import semmle.code.powershell.Statement
import semmle.code.powershell.Expression
import semmle.code.powershell.CommandBase
import semmle.code.powershell.AttributeBase
import semmle.code.powershell.PipelineBase
import semmle.code.powershell.BaseConstantExpression
import semmle.code.powershell.ConstantExpression
import semmle.code.powershell.MemberExpressionBase
import semmle.code.powershell.Attribute
import semmle.code.powershell.NamedAttributeArgument
import semmle.code.powershell.TypeConstraint
import semmle.code.powershell.VariableExpression
import semmle.code.powershell.Parameter
import semmle.code.powershell.ModuleSpecification
import semmle.code.powershell.ParamBlock
import semmle.code.powershell.NamedBlock
import semmle.code.powershell.ScriptBlock
import semmle.code.powershell.StringLiteral
import semmle.code.powershell.AssignmentStatement
import semmle.code.powershell.BinaryExpression
import semmle.code.powershell.ScriptBlockExpr
import semmle.code.powershell.TernaryExpression
import semmle.code.powershell.UsingExpression
import semmle.code.powershell.TrapStatement
import semmle.code.powershell.StatementBlock
import semmle.code.powershell.ArrayExpression
import semmle.code.powershell.ArrayLiteral
import semmle.code.powershell.CommandElement
import semmle.code.powershell.Redirection
import semmle.code.powershell.FileRedirection
import semmle.code.powershell.MergingRedirection
import semmle.code.powershell.LoopStmt
import semmle.code.powershell.DoWhileStmt
import semmle.code.powershell.DoUntilStmt
import semmle.code.powershell.WhileStmt
import semmle.code.powershell.ForStmt
import semmle.code.powershell.ForEachStmt
import semmle.code.powershell.GotoStmt
import semmle.code.powershell.ContinueStmt
import semmle.code.powershell.BreakStmt
import semmle.code.powershell.ReturnStmt
import semmle.code.powershell.UsingStmt
import semmle.code.powershell.Type
import semmle.code.powershell.Member
import semmle.code.powershell.PropertyMember
import semmle.code.powershell.Function
import semmle.code.powershell.TryStmt
import semmle.code.powershell.IfStmt
import semmle.code.powershell.ExitStmt
import semmle.code.powershell.LabeledStmt
import semmle.code.powershell.DynamicStmt
import semmle.code.powershell.DataStmt
import semmle.code.powershell.Configuration
import semmle.code.powershell.CatchClause
import semmle.code.powershell.Command
import semmle.code.powershell.CommandExpression
import semmle.code.powershell.CommandParameter
import semmle.code.powershell.ExpandableStringExpression
import semmle.code.powershell.TypeExpression
import semmle.code.powershell.ParenExpression
import semmle.code.powershell.Chainable
import semmle.code.powershell.Pipeline
import semmle.code.powershell.StringConstantExpression
import semmle.code.powershell.InvokeMemberExpression
import semmle.code.powershell.CommentEntity
