description: Downgrade from rust-analyzer 0.0.328 to 0.0.301
compatibility: full

block_expr_try_block_modifiers.rel: delete
block_expr_is_try.rel: run upgrade.ql new_block_expr_is_try
cfg_atoms.rel: delete
cfg_attr_meta.rel: delete
cfg_attr_meta_cfg_predicates.rel: delete
cfg_attr_meta_metas.rel: delete
cfg_composites.rel: delete
cfg_composite_cfg_predicates.rel: delete
cfg_meta.rel: delete
cfg_meta_cfg_predicates.rel: delete
comments.rel: run upgrade.ql new_comments
const_args.rel: run upgrade.ql new_const_args
const_arg_exprs.rel: run upgrade.ql new_const_arg_exprs
format_args_arg_arg_names.rel: delete
format_args_arg_names.rel: run upgrade.ql new_format_args_arg_names
key_value_meta.rel: delete
key_value_meta_exprs.rel: delete
key_value_meta_paths.rel: delete
locatable_locations.rel: run upgrade.ql new_locatable_locations
meta.rel: run upgrade.ql new_meta
meta_exprs.rel: run upgrade.ql new_meta_exprs
meta_is_unsafe.rel: run upgrade.ql new_meta_is_unsafe
meta_paths.rel: run upgrade.ql new_meta_paths
meta_token_trees.rel: run upgrade.ql new_meta_token_trees
names.rel: run upgrade.ql new_names
path_meta.rel: delete
path_meta_paths.rel: delete
struct_field_default_vals.rel: delete
struct_field_defaults.rel: run upgrade.ql new_struct_field_defaults
token_tree_meta.rel: delete
token_tree_meta_paths.rel: delete
token_tree_meta_token_trees.rel: delete
trait_assoc_item_lists.rel: run upgrade.ql new_trait_assoc_item_lists
trait_attrs.rel: run upgrade.ql new_trait_attrs
trait_generic_param_lists.rel: run upgrade.ql new_trait_generic_param_lists
trait_is_auto.rel: run upgrade.ql new_trait_is_auto
trait_is_unsafe.rel: run upgrade.ql new_trait_is_unsafe
trait_names.rel: run upgrade.ql new_trait_names
trait_type_bound_lists.rel: run upgrade.ql new_trait_type_bound_lists
trait_visibilities.rel: run upgrade.ql new_trait_visibilities
trait_where_clauses.rel: run upgrade.ql new_trait_where_clauses
trait_aliases.rel: run upgrade.ql new_trait_aliases
trait_alias_attrs.rel: run upgrade.ql new_trait_alias_attrs
trait_alias_generic_param_lists.rel: run upgrade.ql new_trait_alias_generic_param_lists
trait_alias_names.rel: run upgrade.ql new_trait_alias_names
trait_alias_type_bound_lists.rel: run upgrade.ql new_trait_alias_type_bound_lists
trait_alias_visibilities.rel: run upgrade.ql new_trait_alias_visibilities
trait_alias_where_clauses.rel: run upgrade.ql new_trait_alias_where_clauses
traits.rel: run upgrade.ql new_traits
try_block_modifier_is_try.rel: delete
try_block_modifiers.rel: delete
try_block_modifier_type_reprs.rel: delete
unsafe_meta.rel: delete
unsafe_meta_is_unsafe.rel: delete
unsafe_meta_meta.rel: delete
variant_const_args.rel: delete
variant_discriminants.rel: run upgrade.ql new_variant_discriminants
