// Generated automatically from javax.jdo.Query for testing purposes

package javax.jdo;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import javax.jdo.Extent;
import javax.jdo.FetchPlan;
import javax.jdo.PersistenceManager;

public interface Query<T> extends AutoCloseable, Serializable
{
    <R> R executeResultUnique(java.lang.Class<R> p0);
    <R> java.util.List<R> executeResultList(java.lang.Class<R> p0);
    Boolean getSerializeRead();
    FetchPlan getFetchPlan();
    Integer getDatastoreReadTimeoutMillis();
    Integer getDatastoreWriteTimeoutMillis();
    List<Object> executeResultList();
    Object execute();
    Object execute(Object p0);
    Object execute(Object p0, Object p1);
    Object execute(Object p0, Object p1, Object p2);
    Object executeResultUnique();
    Object executeWithArray(Object... p0);
    Object executeWithMap(Map p0);
    PersistenceManager getPersistenceManager();
    Query<T> datastoreReadTimeoutMillis(Integer p0);
    Query<T> datastoreWriteTimeoutMillis(Integer p0);
    Query<T> extension(String p0, Object p1);
    Query<T> extensions(Map p0);
    Query<T> filter(String p0);
    Query<T> groupBy(String p0);
    Query<T> ignoreCache(boolean p0);
    Query<T> imports(String p0);
    Query<T> orderBy(String p0);
    Query<T> parameters(String p0);
    Query<T> range(String p0);
    Query<T> range(long p0, long p1);
    Query<T> result(String p0);
    Query<T> saveAsNamedQuery(String p0);
    Query<T> serializeRead(Boolean p0);
    Query<T> setNamedParameters(Map<String, ? extends Object> p0);
    Query<T> setParameters(Object... p0);
    Query<T> subquery(Query p0, String p1, String p2);
    Query<T> subquery(Query p0, String p1, String p2, Map p3);
    Query<T> subquery(Query p0, String p1, String p2, String p3);
    Query<T> subquery(Query p0, String p1, String p2, String... p3);
    Query<T> unmodifiable();
    Query<T> variables(String p0);
    T executeUnique();
    boolean getIgnoreCache();
    boolean isUnmodifiable();
    java.util.List<T> executeList();
    long deletePersistentAll();
    long deletePersistentAll(Map p0);
    long deletePersistentAll(Object... p0);
    static String JDOQL = null;
    static String SQL = null;
    void addExtension(String p0, Object p1);
    void addSubquery(Query p0, String p1, String p2);
    void addSubquery(Query p0, String p1, String p2, Map p3);
    void addSubquery(Query p0, String p1, String p2, String p3);
    void addSubquery(Query p0, String p1, String p2, String... p3);
    void cancel(Thread p0);
    void cancelAll();
    void close(Object p0);
    void closeAll();
    void compile();
    void declareImports(String p0);
    void declareParameters(String p0);
    void declareVariables(String p0);
    void setCandidates(java.util.Collection<T> p0);
    void setCandidates(javax.jdo.Extent<T> p0);
    void setClass(java.lang.Class<T> p0);
    void setDatastoreReadTimeoutMillis(Integer p0);
    void setDatastoreWriteTimeoutMillis(Integer p0);
    void setExtensions(Map p0);
    void setFilter(String p0);
    void setGrouping(String p0);
    void setIgnoreCache(boolean p0);
    void setOrdering(String p0);
    void setRange(String p0);
    void setRange(long p0, long p1);
    void setResult(String p0);
    void setResultClass(Class p0);
    void setSerializeRead(Boolean p0);
    void setUnique(boolean p0);
    void setUnmodifiable();
}
