name: ATM Check Queries Run

# This check is required, therefore we must run it on all PRs, even if only Markdown has changed.
on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: foo
        run: echo "Hello world"
