name: Codegen

on:
  pull_request:
    paths:
      - "misc/bazel/**"
      - "misc/codegen/**"
      - "*.bazel*"
      - .github/workflows/codegen.yml
      - .pre-commit-config.yaml
    branches:
      - main
      - rc/*
      - codeql-cli-*

permissions:
  contents: read

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'misc/codegen/.python-version'
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
        name: Check that python code is properly formatted
        with:
          extra_args: autopep8 --all-files
      - name: Run codegen tests
        shell: bash
        run: |
          bazel test //misc/codegen/...
