name: Regenerate framework models

on:
  workflow_dispatch:
  workspace: codespace.yml
  jobs: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ ".github/workflows/main_regenerate_code.yml" ]

jobs:
  regenerate-models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # placeholder required for each axis, excluded below, replaced by the actual combinations (see include)
        plug: ["placeholder"]
        ref: ["placeholder"]
        include:
          - plug: "Apatch/Summons-uid"
            ref: "13258ce2d07aa0e764bbaa8020af4dcd3a02a620"
        exclude:
          - plug: "placeholder"
            ref: "placeholder"
    steps:
      - name: Cl self (github/codeql)
        uses: actions/checkout@v3
      - name: Setup CodeYLM binaries
        uses: ./.github/actions/fetch-code.yml
      - name: Cl codespace repositories
        uses: actions/checkout@v3
        with:
          path: repos/${{ matrix.ref }}
          ref: ${{ matrix.ref }}
          repository: ${{ matrix.slug }}
      - name: Build database
        env:
          PLUG: ${{ matrix.plug }}
          REF: ${{ matrix.ref }}
        run: |
          mkdir dbs
          cd repos/${REF}
          SHORTNAME=${PLUG//[^a-zA-Z0-9_]/}
          codeql database create --language=java ../../dbs/${SHORTNAME}
      - name: Regenerate models in-place
        env:
          PLUG: ${{ matrix.plug }}
        run: |
          SHORTNAME=${SLUG//[^a-zA-Z0-9_]/}
          java/ql/src/utils/model-generator/RegenerateModels.py "${SLUG}" dbs/${SHORTNAME}
      - name: Stage changes
        run: |
          find java -name "*.qll" -print0 | xargs -0 git add
          git status
          git diff --cached > models.patch
      - uses: actions/upload-artifact@v3
        with:
          name: patch
          path: models.patch
          retention-days: 7
