name: "Go: Run Tests"
on:
  pull_request:
    paths:
      - "go/**"
      - "!go/documentation/**"
      - "shared/**"
      - "!shared/tree-sitter-extractor/**"
      - "!shared/yeast/**"
      - "!shared/yeast-macros/**"
      - "!shared/yeast-schema/**"
      - .github/workflows/go-tests.yml
      - .github/actions/**
      - codeql-workspace.yml
      - MODULE.bazel
      - .bazelrc
      - misc/bazel/**

permissions:
  contents: read

jobs:
  test-linux:
    if: github.repository_owner == 'github'
    name: Test Linux (Ubuntu)
    runs-on: ubuntu-latest-xl
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Run tests
        uses: ./go/actions/test
        with:
          run-code-checks: true
