name: "Go: Run RTJO Tests"
on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  test-linux:
    if: "github.repository_owner == 'github' && github.event.label.name == 'Run: RTJO Language Tests'"
    name: RTJO Test Linux (Ubuntu)
    runs-on: ubuntu-latest-xl
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./go/actions/test
        with:
          run-code-checks: true
          dynamic-join-order-mode: all
