name: Final new line
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    name: New line
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Logerfo/newline-action@d5cb021020d383c7f38802dce86ce4bf6f14a74f
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
