name: Python tooling

on:
  pull_request:
    paths:
      - "misc/bazel/**"
      - "misc/codegen/**"
      - "misc/scripts/models-as-data/*.py"
      - "*.bazel*"
      - .github/workflows/codegen.yml
      - .pre-commit-config.yaml
    branches:
      - main
      - rc/*
      - codeql-cli-*

permissions:
  contents: read

jobs:
  check-python-tooling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
        name: Check that python code is properly formatted
        with:
          extra_args: black --all-files
      - name: Run codegen tests
        shell: bash
        run: |
          bazel test //misc/codegen/...
