name: "Swift: Run Integration Tests"

on:
  pull_request:
    paths:
      - "swift/**"
      - "misc/bazel/**"
      - "*.bazel*"
      - .github/workflows/swift-integration-tests.yml
      - .github/actions/fetch-codeql/action.yml
      - codeql-workspace.yml
    branches:
      - main
defaults:
  run:
    working-directory: swift

jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
#          - macos-latest  TODO
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fetch-codeql
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'swift/.python-version'
      - name: Build Swift extractor
        run: |
          bazel run //swift:create-extractor-pack
      - name: Get Swift version
        id: get_swift_version
        run: |
          VERSION=$(bazel run //swift/extractor -- --version | sed -ne 's/.*version \(\S*\).*/\1/p')
          echo "::set-output name=version::$VERSION"
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "${{steps.get_swift_version.outputs.version}}"
      - name: Run integration tests
        run: |
          python integration-tests/runner.py
