// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"compress/gzip"
	"io"
)

func TaintStepTest_CompressGzipNewReader_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader656 := sourceCQL.(io.Reader)
	intoReader414, _ := gzip.NewReader(fromReader656)
	return intoReader414
}

func TaintStepTest_CompressGzipNewWriter_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter518 := sourceCQL.(*gzip.Writer)
	var intoWriter650 io.Writer
	intermediateCQL := gzip.NewWriter(intoWriter650)
	link(fromWriter518, intermediateCQL)
	return intoWriter650
}

func TaintStepTest_CompressGzipNewWriterLevel_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter784 := sourceCQL.(*gzip.Writer)
	var intoWriter957 io.Writer
	intermediateCQL, _ := gzip.NewWriterLevel(intoWriter957, 0)
	link(fromWriter784, intermediateCQL)
	return intoWriter957
}

func TaintStepTest_CompressGzipReaderRead_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader520 := sourceCQL.(gzip.Reader)
	var intoByte443 []byte
	fromReader520.Read(intoByte443)
	return intoByte443
}

func TaintStepTest_CompressGzipReaderReset_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader127 := sourceCQL.(io.Reader)
	var intoReader483 gzip.Reader
	intoReader483.Reset(fromReader127)
	return intoReader483
}

func TaintStepTest_CompressGzipWriterReset_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter989 := sourceCQL.(gzip.Writer)
	var intoWriter982 io.Writer
	fromWriter989.Reset(intoWriter982)
	return intoWriter982
}

func TaintStepTest_CompressGzipWriterWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte417 := sourceCQL.([]byte)
	var intoWriter584 gzip.Writer
	intoWriter584.Write(fromByte417)
	return intoWriter584
}

func RunAllTaints_CompressGzip() {
	{
		source := newSource(0)
		out := TaintStepTest_CompressGzipNewReader_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_CompressGzipNewWriter_B0I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_CompressGzipNewWriterLevel_B0I0O0(source)
		sink(2, out)
	}
	{
		source := newSource(3)
		out := TaintStepTest_CompressGzipReaderRead_B0I0O0(source)
		sink(3, out)
	}
	{
		source := newSource(4)
		out := TaintStepTest_CompressGzipReaderReset_B0I0O0(source)
		sink(4, out)
	}
	{
		source := newSource(5)
		out := TaintStepTest_CompressGzipWriterReset_B0I0O0(source)
		sink(5, out)
	}
	{
		source := newSource(6)
		out := TaintStepTest_CompressGzipWriterWrite_B0I0O0(source)
		sink(6, out)
	}
}
