// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"encoding/hex"
	"io"
)

func TaintStepTest_EncodingHexDecode_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte656 := sourceCQL.([]byte)
	var intoByte414 []byte
	hex.Decode(intoByte414, fromByte656)
	return intoByte414
}

func TaintStepTest_EncodingHexDecodeString_B0I0O0(sourceCQL interface{}) interface{} {
	fromString518 := sourceCQL.(string)
	intoByte650, _ := hex.DecodeString(fromString518)
	return intoByte650
}

func TaintStepTest_EncodingHexNewDecoder_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader784 := sourceCQL.(io.Reader)
	intoReader957 := hex.NewDecoder(fromReader784)
	return intoReader957
}

func RunAllTaints_EncodingHex() {
	{
		source := newSource(0)
		out := TaintStepTest_EncodingHexDecode_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_EncodingHexDecodeString_B0I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_EncodingHexNewDecoder_B0I0O0(source)
		sink(2, out)
	}
}
