// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"io"
	"io/ioutil"
)

func TaintStepTest_IoIoutilNopCloser_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader656 := sourceCQL.(io.Reader)
	intoReadCloser414 := ioutil.NopCloser(fromReader656)
	return intoReadCloser414
}

func TaintStepTest_IoIoutilReadAll_B0I0O0(sourceCQL interface{}) interface{} {
	fromReader518 := sourceCQL.(io.Reader)
	intoByte650, _ := ioutil.ReadAll(fromReader518)
	return intoByte650
}

func TaintStepTest_IoWriterWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte784 := sourceCQL.([]byte)
	var intoWriter957 io.Writer
	intoWriter957.Write(fromByte784)
	return intoWriter957
}

func RunAllTaints_IoIoutil() {
	{
		source := newSource(0)
		out := TaintStepTest_IoIoutilNopCloser_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_IoIoutilReadAll_B0I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_IoWriterWrite_B0I0O0(source)
		sink(2, out)
	}
}
