// Code generated by https://github.com/gagliardetto/codebox. DO NOT EDIT.

package main

import (
	"io"
	"text/tabwriter"
)

func TaintStepTest_TextTabwriterNewWriter_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter656 := sourceCQL.(*tabwriter.Writer)
	var intoWriter414 io.Writer
	intermediateCQL := tabwriter.NewWriter(intoWriter414, 0, 0, 0, 0, 0)
	link(fromWriter656, intermediateCQL)
	return intoWriter414
}

func TaintStepTest_TextTabwriterWriterInit_B0I0O0(sourceCQL interface{}) interface{} {
	fromWriter518 := sourceCQL.(tabwriter.Writer)
	var intoWriter650 io.Writer
	fromWriter518.Init(intoWriter650, 0, 0, 0, 0, 0)
	return intoWriter650
}

func TaintStepTest_TextTabwriterWriterInit_B0I1O0(sourceCQL interface{}) interface{} {
	fromWriter784 := sourceCQL.(*tabwriter.Writer)
	var intoWriter957 io.Writer
	var mediumObjCQL tabwriter.Writer
	intermediateCQL := mediumObjCQL.Init(intoWriter957, 0, 0, 0, 0, 0)
	link(fromWriter784, intermediateCQL)
	return intoWriter957
}

func TaintStepTest_TextTabwriterWriterWrite_B0I0O0(sourceCQL interface{}) interface{} {
	fromByte520 := sourceCQL.([]byte)
	var intoWriter443 tabwriter.Writer
	intoWriter443.Write(fromByte520)
	return intoWriter443
}

func RunAllTaints_TextTabwriter() {
	{
		source := newSource(0)
		out := TaintStepTest_TextTabwriterNewWriter_B0I0O0(source)
		sink(0, out)
	}
	{
		source := newSource(1)
		out := TaintStepTest_TextTabwriterWriterInit_B0I0O0(source)
		sink(1, out)
	}
	{
		source := newSource(2)
		out := TaintStepTest_TextTabwriterWriterInit_B0I1O0(source)
		sink(2, out)
	}
	{
		source := newSource(3)
		out := TaintStepTest_TextTabwriterWriterWrite_B0I0O0(source)
		sink(3, out)
	}
}
